-- Catalogue policy assertions run as real API personas, never an elevated inspection connection.
select no_plan();
create function tests.affected_rows(statement text)
returns bigint language plpgsql set search_path = '' as $$
declare affected bigint;
begin execute statement; get diagnostics affected = row_count; return affected; end;
$$;

select tests.create_catalogue_fixture();
reset role;
select tests.act_as_public();
select is((select count(*) from public.effects), 1::bigint, 'public sees only published effects');
select is((select count(*) from public.effect_versions), 1::bigint, 'public sees only current published effect versions');
select is((select count(*) from public.poster_renders), 1::bigint, 'public sees only ready current posters');
reset role;
select tests.act_as('anonymous_shopper');
select is((select count(*) from public.effects), 1::bigint, 'anonymous_shopper sees only published effects');
select is((select count(*) from public.effect_versions), 1::bigint, 'anonymous_shopper sees only current published effect versions');
select is((select count(*) from public.poster_renders), 1::bigint, 'anonymous_shopper sees only ready current posters');
reset role;
select tests.act_as('signed_in_shopper');
select is((select count(*) from public.effects), 1::bigint, 'signed_in_shopper sees only published effects');
select is((select count(*) from public.effect_versions), 1::bigint, 'signed_in_shopper sees only current published effect versions');
select is((select count(*) from public.poster_renders), 1::bigint, 'signed_in_shopper sees only ready current posters');
reset role;
select tests.act_as('organisation_owner');
select is((select count(*) from public.effects), 1::bigint, 'organisation_owner sees only published effects');
select is((select count(*) from public.effect_versions), 1::bigint, 'organisation_owner sees only current published effect versions');
select is((select count(*) from public.poster_renders), 1::bigint, 'organisation_owner sees only ready current posters');
reset role;
select tests.act_as('organisation_manager');
select is((select count(*) from public.effects), 1::bigint, 'organisation_manager sees only published effects');
select is((select count(*) from public.effect_versions), 1::bigint, 'organisation_manager sees only current published effect versions');
select is((select count(*) from public.poster_renders), 1::bigint, 'organisation_manager sees only ready current posters');
reset role;
select tests.act_as('other_organisation_member');
select is((select count(*) from public.effects), 1::bigint, 'other_organisation_member sees only published effects');
select is((select count(*) from public.effect_versions), 1::bigint, 'other_organisation_member sees only current published effect versions');
select is((select count(*) from public.poster_renders), 1::bigint, 'other_organisation_member sees only ready current posters');
reset role;
select tests.act_as('supplier_member');
select is((select count(*) from public.effects), 1::bigint, 'supplier_member sees only published effects');
select is((select count(*) from public.effect_versions), 1::bigint, 'supplier_member sees only current published effect versions');
select is((select count(*) from public.poster_renders), 1::bigint, 'supplier_member sees only ready current posters');
reset role;
select tests.act_as('platform_staff');
select is((select count(*) from public.effects), 3::bigint, 'catalogue staff can read all effects');
select is((select count(*) from public.effect_versions), 4::bigint, 'catalogue staff can read all effect_versions');
select is((select count(*) from public.poster_renders), 3::bigint, 'catalogue staff can read all poster_renders');
select is((select count(*) from public.media), 4::bigint, 'catalogue staff can read all media');
reset role;
select tests.act_as('supplier_member');
select is((select count(*) from public.media), 1::bigint, 'supplier_member media visibility is scoped');
select is((select count(*) from public.media where id = '30000000-0000-0000-0000-000000000001'), 1::bigint, 'supplier_member reads own media');
select is((select count(*) from public.media where id = '30000000-0000-0000-0000-000000000002'), 0::bigint, 'supplier_member cannot read foreign media');
reset role;
select tests.act_as('organisation_owner');
select is((select count(*) from public.media), 1::bigint, 'organisation_owner media visibility is scoped');
select is((select count(*) from public.media where id = '30000000-0000-0000-0000-000000000003'), 1::bigint, 'organisation_owner reads own media');
select is((select count(*) from public.media where id = '30000000-0000-0000-0000-000000000001'), 0::bigint, 'organisation_owner cannot read foreign media');
reset role;
select tests.act_as('organisation_manager');
select is((select count(*) from public.media), 1::bigint, 'organisation_manager media visibility is scoped');
select is((select count(*) from public.media where id = '30000000-0000-0000-0000-000000000003'), 1::bigint, 'organisation_manager reads own media');
select is((select count(*) from public.media where id = '30000000-0000-0000-0000-000000000001'), 0::bigint, 'organisation_manager cannot read foreign media');
reset role;
select tests.act_as('other_organisation_member');
select is((select count(*) from public.media), 1::bigint, 'other_organisation_member media visibility is scoped');
select is((select count(*) from public.media where id = '30000000-0000-0000-0000-000000000004'), 1::bigint, 'other_organisation_member reads own media');
select is((select count(*) from public.media where id = '30000000-0000-0000-0000-000000000001'), 0::bigint, 'other_organisation_member cannot read foreign media');
reset role;
select tests.act_as('anonymous_shopper');
select is((select count(*) from public.media), 0::bigint, 'anonymous_shopper media visibility is scoped');
select is((select count(*) from public.media where id = '30000000-0000-0000-0000-000000000001'), 0::bigint, 'anonymous_shopper cannot read foreign media');
reset role;
select tests.act_as('signed_in_shopper');
select is((select count(*) from public.media), 0::bigint, 'signed_in_shopper media visibility is scoped');
select is((select count(*) from public.media where id = '30000000-0000-0000-0000-000000000001'), 0::bigint, 'signed_in_shopper cannot read foreign media');
reset role;
select tests.act_as('other_organisation_member');
select throws_ok($query$insert into public.media(bucket,path,kind,mime,bytes,sha256,supplier_id,uploaded_by) values ('catalogue-media','new/clip.mp4','video','video/mp4',1,repeat('e',64),'20000000-0000-0000-0000-000000000001',tests.get_supabase_uid('supplier_member'))$query$, '42501', null, 'media insert denies another organisation');
reset role;
select tests.act_as('supplier_member');
select is((select tests.affected_rows($query$insert into public.media(bucket,path,kind,mime,bytes,sha256,supplier_id,uploaded_by) values ('catalogue-media','new/clip.mp4','video','video/mp4',1,repeat('e',64),'20000000-0000-0000-0000-000000000001',tests.get_supabase_uid('supplier_member'))$query$)), 1::bigint, 'supplier inserts own media');
select throws_ok($query$insert into public.media(bucket,path,kind,mime,bytes,sha256,supplier_id,uploaded_by) values ('catalogue-media','foreign/clip.mp4','video','video/mp4',1,repeat('e',64),'20000000-0000-0000-0000-000000000002',tests.get_supabase_uid('supplier_member'))$query$, '42501', null, 'supplier cannot insert for another supplier');
reset role;
select tests.act_as('platform_staff');
select is((select tests.affected_rows($query$insert into public.media(bucket,path,kind,mime,bytes,sha256,supplier_id,uploaded_by) values ('catalogue-media','staff/clip.mp4','video','video/mp4',1,repeat('e',64),'20000000-0000-0000-0000-000000000001',tests.get_supabase_uid('platform_staff'))$query$)), 1::bigint, 'staff inserts catalogue media');
select throws_ok($query$insert into public.media(bucket,path,kind,mime,bytes,sha256,supplier_id,uploaded_by) values ('catalogue-media','spoof/clip.mp4','video','video/mp4',1,repeat('e',64),'20000000-0000-0000-0000-000000000001',tests.get_supabase_uid('supplier_member'))$query$, '42501', null, 'staff cannot spoof uploader identity');
reset role;
select tests.act_as('other_organisation_member');
select throws_ok($query$insert into public.poster_renders(effect_version_id,renderer,framing,width,height,t_ms,path) values ('50000000-0000-0000-0000-000000000001','next','square',100,100,1000,'fixture/next.webp')$query$, '42501', null, 'poster insert denies another organisation');
reset role;
select tests.act_as('platform_staff');
select is((select tests.affected_rows($query$insert into public.poster_renders(effect_version_id,renderer,framing,width,height,t_ms,path) values ('50000000-0000-0000-0000-000000000001','next','square',100,100,1000,'fixture/next.webp')$query$)), 1::bigint, 'poster insert allows catalogue editor');
reset role;
select tests.act_as('other_organisation_member');
select is((select tests.affected_rows($query$update public.poster_renders set status = 'ready' where renderer = 'next'$query$)), 0::bigint, 'poster update denies another organisation');
reset role;
select tests.act_as('platform_staff');
select is((select tests.affected_rows($query$update public.poster_renders set status = 'ready' where renderer = 'next'$query$)), 1::bigint, 'poster update allows catalogue editor');
reset role;
select tests.act_as_public();
select throws_ok($query$select * from public.media$query$, '42501', null, 'public requests cannot read private media metadata');
reset role;
select * from finish();
