-- Catalogue policy assertions run as real API personas, never an elevated inspection connection.
select no_plan();
create function tests.affected_rows(statement text)
returns bigint language plpgsql set search_path = '' as $$
declare affected bigint;
begin execute statement; get diagnostics affected = row_count; return affected; end;
$$;

select tests.create_catalogue_fixture();
reset role;
select tests.act_as_public();
select is((select count(*) from public.products), 2::bigint, 'public reads only published products');
select is((select count(*) from public.product_versions), 1::bigint, 'public reads only published product_versions');
select is((select count(*) from public.product_version_effects), 1::bigint, 'public reads only published product_version_effects');
select is((select count(*) from public.pack_items), 1::bigint, 'public reads only published pack_items');
select is((select count(*) from public.product_markets), 2::bigint, 'public reads only published product_markets');
select is((select count(*) from public.product_media), 1::bigint, 'public reads only published product_media');
reset role;
select tests.act_as('anonymous_shopper');
select is((select count(*) from public.products), 2::bigint, 'anonymous_shopper reads only published products');
select is((select count(*) from public.product_versions), 1::bigint, 'anonymous_shopper reads only published product_versions');
select is((select count(*) from public.product_version_effects), 1::bigint, 'anonymous_shopper reads only published product_version_effects');
select is((select count(*) from public.pack_items), 1::bigint, 'anonymous_shopper reads only published pack_items');
select is((select count(*) from public.product_markets), 2::bigint, 'anonymous_shopper reads only published product_markets');
select is((select count(*) from public.product_media), 1::bigint, 'anonymous_shopper reads only published product_media');
reset role;
select tests.act_as('signed_in_shopper');
select is((select count(*) from public.products), 2::bigint, 'signed_in_shopper reads only published products');
select is((select count(*) from public.product_versions), 1::bigint, 'signed_in_shopper reads only published product_versions');
select is((select count(*) from public.product_version_effects), 1::bigint, 'signed_in_shopper reads only published product_version_effects');
select is((select count(*) from public.pack_items), 1::bigint, 'signed_in_shopper reads only published pack_items');
select is((select count(*) from public.product_markets), 2::bigint, 'signed_in_shopper reads only published product_markets');
select is((select count(*) from public.product_media), 1::bigint, 'signed_in_shopper reads only published product_media');
reset role;
select tests.act_as('organisation_owner');
select is((select count(*) from public.products), 2::bigint, 'organisation_owner reads only published products');
select is((select count(*) from public.product_versions), 1::bigint, 'organisation_owner reads only published product_versions');
select is((select count(*) from public.product_version_effects), 1::bigint, 'organisation_owner reads only published product_version_effects');
select is((select count(*) from public.pack_items), 1::bigint, 'organisation_owner reads only published pack_items');
select is((select count(*) from public.product_markets), 2::bigint, 'organisation_owner reads only published product_markets');
select is((select count(*) from public.product_media), 1::bigint, 'organisation_owner reads only published product_media');
reset role;
select tests.act_as('organisation_manager');
select is((select count(*) from public.products), 2::bigint, 'organisation_manager reads only published products');
select is((select count(*) from public.product_versions), 1::bigint, 'organisation_manager reads only published product_versions');
select is((select count(*) from public.product_version_effects), 1::bigint, 'organisation_manager reads only published product_version_effects');
select is((select count(*) from public.pack_items), 1::bigint, 'organisation_manager reads only published pack_items');
select is((select count(*) from public.product_markets), 2::bigint, 'organisation_manager reads only published product_markets');
select is((select count(*) from public.product_media), 1::bigint, 'organisation_manager reads only published product_media');
reset role;
select tests.act_as('other_organisation_member');
select is((select count(*) from public.products), 2::bigint, 'other_organisation_member reads only published products');
select is((select count(*) from public.product_versions), 1::bigint, 'other_organisation_member reads only published product_versions');
select is((select count(*) from public.product_version_effects), 1::bigint, 'other_organisation_member reads only published product_version_effects');
select is((select count(*) from public.pack_items), 1::bigint, 'other_organisation_member reads only published pack_items');
select is((select count(*) from public.product_markets), 2::bigint, 'other_organisation_member reads only published product_markets');
select is((select count(*) from public.product_media), 1::bigint, 'other_organisation_member reads only published product_media');
reset role;
select tests.act_as('supplier_member');
select is((select count(*) from public.products), 2::bigint, 'supplier_member reads only published products');
select is((select count(*) from public.product_versions), 1::bigint, 'supplier_member reads only published product_versions');
select is((select count(*) from public.product_version_effects), 1::bigint, 'supplier_member reads only published product_version_effects');
select is((select count(*) from public.pack_items), 1::bigint, 'supplier_member reads only published pack_items');
select is((select count(*) from public.product_markets), 2::bigint, 'supplier_member reads only published product_markets');
select is((select count(*) from public.product_media), 1::bigint, 'supplier_member reads only published product_media');
reset role;
select tests.act_as('supplier_member');
select is((select count(*) from public.suppliers where id = '20000000-0000-0000-0000-000000000001'), 1::bigint, 'supplier reads own suppliers');
select is((select count(*) from public.suppliers where id = '20000000-0000-0000-0000-000000000002'), 0::bigint, 'supplier cannot read foreign suppliers');
reset role;
select tests.act_as('other_organisation_member');
select is((select count(*) from public.suppliers), 0::bigint, 'another organisation cannot read suppliers');
reset role;
select tests.act_as('platform_staff');
select is((select count(*) from public.suppliers), 2::bigint, 'staff reads suppliers');
reset role;
select tests.act_as('supplier_member');
select is((select count(*) from public.supplier_members where supplier_id = '20000000-0000-0000-0000-000000000001'), 1::bigint, 'supplier reads own supplier_members');
select is((select count(*) from public.supplier_members where supplier_id = '20000000-0000-0000-0000-000000000002'), 0::bigint, 'supplier cannot read foreign supplier_members');
reset role;
select tests.act_as('other_organisation_member');
select is((select count(*) from public.supplier_members), 0::bigint, 'another organisation cannot read supplier_members');
reset role;
select tests.act_as('platform_staff');
select is((select count(*) from public.supplier_members), 2::bigint, 'staff reads supplier_members');
reset role;
select tests.act_as('supplier_member');
select is((select count(*) from public.supplier_products where supplier_id = '20000000-0000-0000-0000-000000000001'), 1::bigint, 'supplier reads own supplier_products');
select is((select count(*) from public.supplier_products where supplier_id = '20000000-0000-0000-0000-000000000002'), 0::bigint, 'supplier cannot read foreign supplier_products');
reset role;
select tests.act_as('other_organisation_member');
select is((select count(*) from public.supplier_products), 0::bigint, 'another organisation cannot read supplier_products');
reset role;
select tests.act_as('platform_staff');
select is((select count(*) from public.supplier_products), 2::bigint, 'staff reads supplier_products');
reset role;
select tests.act_as('platform_staff');
select is((select count(*) from public.products), 4::bigint, 'staff reads unpublished products');
select is((select count(*) from public.product_versions), 2::bigint, 'staff reads unpublished product_versions');
select is((select count(*) from public.product_version_effects), 2::bigint, 'staff reads unpublished product_version_effects');
select is((select count(*) from public.pack_items), 2::bigint, 'staff reads unpublished pack_items');
select is((select count(*) from public.product_markets), 3::bigint, 'staff reads unpublished product_markets');
select is((select count(*) from public.product_media), 2::bigint, 'staff reads unpublished product_media');
reset role;
select tests.act_as('other_organisation_member');
select throws_ok($query$insert into public.suppliers(id,name,slug) values ('20000000-0000-0000-0000-000000000003','New supplier','new-supplier')$query$, '42501', null, 'suppliers insert denies other_organisation_member');
reset role;
select tests.act_as('supplier_member');
select throws_ok($query$insert into public.suppliers(id,name,slug) values ('20000000-0000-0000-0000-000000000003','New supplier','new-supplier')$query$, '42501', null, 'suppliers insert denies supplier_member');
reset role;
select tests.act_as('platform_staff');
select is((select tests.affected_rows($query$insert into public.suppliers(id,name,slug) values ('20000000-0000-0000-0000-000000000003','New supplier','new-supplier')$query$)), 1::bigint, 'suppliers insert allows catalogue editor');
reset role;
select tests.act_as('other_organisation_member');
select is((select tests.affected_rows($query$update public.suppliers set name = 'Edited supplier' where id = '20000000-0000-0000-0000-000000000003'$query$)), 0::bigint, 'suppliers update denies other_organisation_member');
reset role;
select tests.act_as('supplier_member');
select is((select tests.affected_rows($query$update public.suppliers set name = 'Edited supplier' where id = '20000000-0000-0000-0000-000000000003'$query$)), 0::bigint, 'suppliers update denies supplier_member');
reset role;
select tests.act_as('platform_staff');
select is((select tests.affected_rows($query$update public.suppliers set name = 'Edited supplier' where id = '20000000-0000-0000-0000-000000000003'$query$)), 1::bigint, 'suppliers update allows catalogue editor');
reset role;
select tests.act_as('other_organisation_member');
select is((select tests.affected_rows($query$delete from public.suppliers where id = '20000000-0000-0000-0000-000000000003'$query$)), 0::bigint, 'suppliers delete denies other_organisation_member');
reset role;
select tests.act_as('supplier_member');
select is((select tests.affected_rows($query$delete from public.suppliers where id = '20000000-0000-0000-0000-000000000003'$query$)), 0::bigint, 'suppliers delete denies supplier_member');
reset role;
select tests.act_as('platform_staff');
select is((select tests.affected_rows($query$delete from public.suppliers where id = '20000000-0000-0000-0000-000000000003'$query$)), 1::bigint, 'suppliers delete allows catalogue editor');
reset role;
select tests.act_as('other_organisation_member');
select throws_ok($query$insert into public.supplier_members(supplier_id,profile_id,role) values ('20000000-0000-0000-0000-000000000001',tests.get_supabase_uid('signed_in_shopper'),'member')$query$, '42501', null, 'supplier_members insert denies other_organisation_member');
reset role;
select tests.act_as('supplier_member');
select throws_ok($query$insert into public.supplier_members(supplier_id,profile_id,role) values ('20000000-0000-0000-0000-000000000001',tests.get_supabase_uid('signed_in_shopper'),'member')$query$, '42501', null, 'supplier_members insert denies supplier_member');
reset role;
select tests.act_as('platform_staff');
select is((select tests.affected_rows($query$insert into public.supplier_members(supplier_id,profile_id,role) values ('20000000-0000-0000-0000-000000000001',tests.get_supabase_uid('signed_in_shopper'),'member')$query$)), 1::bigint, 'supplier_members insert allows catalogue editor');
reset role;
select tests.act_as('other_organisation_member');
select is((select tests.affected_rows($query$update public.supplier_members set role = 'owner' where profile_id = tests.get_supabase_uid('signed_in_shopper')$query$)), 0::bigint, 'supplier_members update denies other_organisation_member');
reset role;
select tests.act_as('supplier_member');
select is((select tests.affected_rows($query$update public.supplier_members set role = 'owner' where profile_id = tests.get_supabase_uid('signed_in_shopper')$query$)), 0::bigint, 'supplier_members update denies supplier_member');
reset role;
select tests.act_as('platform_staff');
select is((select tests.affected_rows($query$update public.supplier_members set role = 'owner' where profile_id = tests.get_supabase_uid('signed_in_shopper')$query$)), 1::bigint, 'supplier_members update allows catalogue editor');
reset role;
select tests.act_as('other_organisation_member');
select is((select tests.affected_rows($query$delete from public.supplier_members where profile_id = tests.get_supabase_uid('signed_in_shopper')$query$)), 0::bigint, 'supplier_members delete denies other_organisation_member');
reset role;
select tests.act_as('supplier_member');
select is((select tests.affected_rows($query$delete from public.supplier_members where profile_id = tests.get_supabase_uid('signed_in_shopper')$query$)), 0::bigint, 'supplier_members delete denies supplier_member');
reset role;
select tests.act_as('platform_staff');
select is((select tests.affected_rows($query$delete from public.supplier_members where profile_id = tests.get_supabase_uid('signed_in_shopper')$query$)), 1::bigint, 'supplier_members delete allows catalogue editor');
reset role;
select tests.act_as('other_organisation_member');
select throws_ok($query$insert into public.supplier_products(supplier_id,supplier_code,name_raw) values ('20000000-0000-0000-0000-000000000001','NEW','New listing')$query$, '42501', null, 'supplier_products insert denies other_organisation_member');
reset role;
select tests.act_as('supplier_member');
select throws_ok($query$insert into public.supplier_products(supplier_id,supplier_code,name_raw) values ('20000000-0000-0000-0000-000000000001','NEW','New listing')$query$, '42501', null, 'supplier_products insert denies supplier_member');
reset role;
select tests.act_as('platform_staff');
select is((select tests.affected_rows($query$insert into public.supplier_products(supplier_id,supplier_code,name_raw) values ('20000000-0000-0000-0000-000000000001','NEW','New listing')$query$)), 1::bigint, 'supplier_products insert allows catalogue editor');
reset role;
select tests.act_as('other_organisation_member');
select is((select tests.affected_rows($query$update public.supplier_products set name_raw = 'Edited listing' where supplier_code = 'NEW'$query$)), 0::bigint, 'supplier_products update denies other_organisation_member');
reset role;
select tests.act_as('supplier_member');
select is((select tests.affected_rows($query$update public.supplier_products set name_raw = 'Edited listing' where supplier_code = 'NEW'$query$)), 0::bigint, 'supplier_products update denies supplier_member');
reset role;
select tests.act_as('platform_staff');
select is((select tests.affected_rows($query$update public.supplier_products set name_raw = 'Edited listing' where supplier_code = 'NEW'$query$)), 1::bigint, 'supplier_products update allows catalogue editor');
reset role;
select tests.act_as('other_organisation_member');
select is((select tests.affected_rows($query$delete from public.supplier_products where supplier_code = 'NEW'$query$)), 0::bigint, 'supplier_products delete denies other_organisation_member');
reset role;
select tests.act_as('supplier_member');
select is((select tests.affected_rows($query$delete from public.supplier_products where supplier_code = 'NEW'$query$)), 0::bigint, 'supplier_products delete denies supplier_member');
reset role;
select tests.act_as('platform_staff');
select is((select tests.affected_rows($query$delete from public.supplier_products where supplier_code = 'NEW'$query$)), 1::bigint, 'supplier_products delete allows catalogue editor');
reset role;
select tests.act_as('other_organisation_member');
select throws_ok($query$insert into public.product_media(product_id,media_id,role) values ('60000000-0000-0000-0000-000000000001','30000000-0000-0000-0000-000000000002','photo')$query$, '42501', null, 'product_media insert denies other_organisation_member');
reset role;
select tests.act_as('supplier_member');
select throws_ok($query$insert into public.product_media(product_id,media_id,role) values ('60000000-0000-0000-0000-000000000001','30000000-0000-0000-0000-000000000002','photo')$query$, '42501', null, 'product_media insert denies supplier_member');
reset role;
select tests.act_as('platform_staff');
select is((select tests.affected_rows($query$insert into public.product_media(product_id,media_id,role) values ('60000000-0000-0000-0000-000000000001','30000000-0000-0000-0000-000000000002','photo')$query$)), 1::bigint, 'product_media insert allows catalogue editor');
reset role;
select tests.act_as('other_organisation_member');
select is((select tests.affected_rows($query$update public.product_media set sort = 1 where product_id = '60000000-0000-0000-0000-000000000001' and media_id = '30000000-0000-0000-0000-000000000002'$query$)), 0::bigint, 'product_media update denies other_organisation_member');
reset role;
select tests.act_as('supplier_member');
select is((select tests.affected_rows($query$update public.product_media set sort = 1 where product_id = '60000000-0000-0000-0000-000000000001' and media_id = '30000000-0000-0000-0000-000000000002'$query$)), 0::bigint, 'product_media update denies supplier_member');
reset role;
select tests.act_as('platform_staff');
select is((select tests.affected_rows($query$update public.product_media set sort = 1 where product_id = '60000000-0000-0000-0000-000000000001' and media_id = '30000000-0000-0000-0000-000000000002'$query$)), 1::bigint, 'product_media update allows catalogue editor');
reset role;
select tests.act_as('other_organisation_member');
select is((select tests.affected_rows($query$delete from public.product_media where product_id = '60000000-0000-0000-0000-000000000001' and media_id = '30000000-0000-0000-0000-000000000002'$query$)), 0::bigint, 'product_media delete denies other_organisation_member');
reset role;
select tests.act_as('supplier_member');
select is((select tests.affected_rows($query$delete from public.product_media where product_id = '60000000-0000-0000-0000-000000000001' and media_id = '30000000-0000-0000-0000-000000000002'$query$)), 0::bigint, 'product_media delete denies supplier_member');
reset role;
select tests.act_as('platform_staff');
select is((select tests.affected_rows($query$delete from public.product_media where product_id = '60000000-0000-0000-0000-000000000001' and media_id = '30000000-0000-0000-0000-000000000002'$query$)), 1::bigint, 'product_media delete allows catalogue editor');
reset role;
select tests.act_as_public();
select throws_ok($query$select * from public.suppliers$query$, '42501', null, 'public cannot read private suppliers');
reset role;
select tests.act_as_public();
select throws_ok($query$select * from public.supplier_members$query$, '42501', null, 'public cannot read private supplier_members');
reset role;
select tests.act_as_public();
select throws_ok($query$select * from public.supplier_products$query$, '42501', null, 'public cannot read private supplier_products');
reset role;
select tests.act_as('organisation_owner');
select throws_ok($query$select public.create_pack('unauthorised','Unauthorised pack')$query$, '42501', null, 'organisation_owner cannot call create_pack');
select throws_ok($query$select public.publish_effect_version('50000000-0000-0000-0000-000000000002')$query$, '42501', null, 'organisation_owner cannot call publish_effect_version');
select throws_ok($query$select public.publish_product_version('70000000-0000-0000-0000-000000000002')$query$, '42501', null, 'organisation_owner cannot call publish_product_version');
select throws_ok($query$select public.archive_effect('40000000-0000-0000-0000-000000000001')$query$, '42501', null, 'organisation_owner cannot call archive_effect');
select throws_ok($query$select public.archive_product('60000000-0000-0000-0000-000000000001')$query$, '42501', null, 'organisation_owner cannot call archive_product');
reset role;
select tests.act_as('organisation_manager');
select throws_ok($query$select public.create_pack('unauthorised','Unauthorised pack')$query$, '42501', null, 'organisation_manager cannot call create_pack');
select throws_ok($query$select public.publish_effect_version('50000000-0000-0000-0000-000000000002')$query$, '42501', null, 'organisation_manager cannot call publish_effect_version');
select throws_ok($query$select public.publish_product_version('70000000-0000-0000-0000-000000000002')$query$, '42501', null, 'organisation_manager cannot call publish_product_version');
select throws_ok($query$select public.archive_effect('40000000-0000-0000-0000-000000000001')$query$, '42501', null, 'organisation_manager cannot call archive_effect');
select throws_ok($query$select public.archive_product('60000000-0000-0000-0000-000000000001')$query$, '42501', null, 'organisation_manager cannot call archive_product');
reset role;
select tests.act_as('other_organisation_member');
select throws_ok($query$select public.create_pack('unauthorised','Unauthorised pack')$query$, '42501', null, 'other_organisation_member cannot call create_pack');
select throws_ok($query$select public.publish_effect_version('50000000-0000-0000-0000-000000000002')$query$, '42501', null, 'other_organisation_member cannot call publish_effect_version');
select throws_ok($query$select public.publish_product_version('70000000-0000-0000-0000-000000000002')$query$, '42501', null, 'other_organisation_member cannot call publish_product_version');
select throws_ok($query$select public.archive_effect('40000000-0000-0000-0000-000000000001')$query$, '42501', null, 'other_organisation_member cannot call archive_effect');
select throws_ok($query$select public.archive_product('60000000-0000-0000-0000-000000000001')$query$, '42501', null, 'other_organisation_member cannot call archive_product');
reset role;
select tests.act_as('anonymous_shopper');
select throws_ok($query$select public.create_pack('unauthorised','Unauthorised pack')$query$, '42501', null, 'anonymous_shopper cannot call create_pack');
select throws_ok($query$select public.publish_effect_version('50000000-0000-0000-0000-000000000002')$query$, '42501', null, 'anonymous_shopper cannot call publish_effect_version');
select throws_ok($query$select public.publish_product_version('70000000-0000-0000-0000-000000000002')$query$, '42501', null, 'anonymous_shopper cannot call publish_product_version');
select throws_ok($query$select public.archive_effect('40000000-0000-0000-0000-000000000001')$query$, '42501', null, 'anonymous_shopper cannot call archive_effect');
select throws_ok($query$select public.archive_product('60000000-0000-0000-0000-000000000001')$query$, '42501', null, 'anonymous_shopper cannot call archive_product');
reset role;
select tests.act_as('signed_in_shopper');
select throws_ok($query$select public.create_pack('unauthorised','Unauthorised pack')$query$, '42501', null, 'signed_in_shopper cannot call create_pack');
select throws_ok($query$select public.publish_effect_version('50000000-0000-0000-0000-000000000002')$query$, '42501', null, 'signed_in_shopper cannot call publish_effect_version');
select throws_ok($query$select public.publish_product_version('70000000-0000-0000-0000-000000000002')$query$, '42501', null, 'signed_in_shopper cannot call publish_product_version');
select throws_ok($query$select public.archive_effect('40000000-0000-0000-0000-000000000001')$query$, '42501', null, 'signed_in_shopper cannot call archive_effect');
select throws_ok($query$select public.archive_product('60000000-0000-0000-0000-000000000001')$query$, '42501', null, 'signed_in_shopper cannot call archive_product');
reset role;
select tests.act_as('supplier_member');
select throws_ok($query$select public.create_pack('unauthorised','Unauthorised pack')$query$, '42501', null, 'supplier_member cannot call create_pack');
select throws_ok($query$select public.publish_effect_version('50000000-0000-0000-0000-000000000002')$query$, '42501', null, 'supplier_member cannot call publish_effect_version');
select throws_ok($query$select public.publish_product_version('70000000-0000-0000-0000-000000000002')$query$, '42501', null, 'supplier_member cannot call publish_product_version');
select throws_ok($query$select public.archive_effect('40000000-0000-0000-0000-000000000001')$query$, '42501', null, 'supplier_member cannot call archive_effect');
select throws_ok($query$select public.archive_product('60000000-0000-0000-0000-000000000001')$query$, '42501', null, 'supplier_member cannot call archive_product');
reset role;
select tests.act_as('other_organisation_member');
select throws_ok($query$select public.create_effect_draft(null,'blocked','Blocked','peony',tests.design_fixture(),'fixture')$query$,'42501',null,'another organisation cannot call create_effect_draft');
select throws_ok($query$select public.save_effect_draft('50000000-0000-0000-0000-000000000002',tests.design_fixture(),'fixture')$query$,'42501',null,'another organisation cannot call save_effect_draft');
select throws_ok($query$select public.create_product_draft(null,'blocked','Blocked','cake',tests.composition_fixture(),'{"a":"40000000-0000-0000-0000-000000000001"}')$query$,'42501',null,'another organisation cannot call create_product_draft');
select throws_ok($query$select public.save_product_draft('70000000-0000-0000-0000-000000000002',tests.composition_fixture(),'{}')$query$,'42501',null,'another organisation cannot call save_product_draft');
select throws_ok($query$select public.confirm_product_safety('60000000-0000-0000-0000-000000000002',8::smallint,2::smallint,'[{"market":"GB","legal_category":"F2"}]')$query$,'42501',null,'another organisation cannot call confirm_product_safety');
select throws_ok($query$select public.save_pack_items('60000000-0000-0000-0000-000000000004','[]')$query$,'42501',null,'another organisation cannot call save_pack_items');
select throws_ok($query$select public.publish_pack('60000000-0000-0000-0000-000000000004')$query$,'42501',null,'another organisation cannot call publish_pack');
select throws_ok($query$select public.save_product_details('60000000-0000-0000-0000-000000000001','Blocked','Blocked','Blocked')$query$,'42501',null,'another organisation cannot call save_product_details');
select throws_ok($query$select public.save_effect_details('40000000-0000-0000-0000-000000000001','Blocked','Blocked',true)$query$,'42501',null,'another organisation cannot call save_effect_details');
reset role;
update public.staff_roles set role = 'reviewer' where profile_id = tests.get_supabase_uid('platform_staff');
select tests.act_as('platform_staff');
select is((select count(*) from public.effect_versions),4::bigint,'reviewers can inspect draft history');
select throws_ok($query$select public.create_pack('reviewer-pack','Reviewer pack')$query$,'42501',null,'reviewers cannot edit the catalogue');
reset role;
update public.staff_roles set role = 'super_admin' where profile_id = tests.get_supabase_uid('platform_staff');
select tests.act_as('platform_staff');
select lives_ok($query$select public.create_pack('admin-pack','Admin pack')$query$,'super admins have catalogue editing rights');
reset role;
update public.suppliers set status = 'paused' where id = '20000000-0000-0000-0000-000000000001';
select tests.act_as('supplier_member');
select is((select count(*) from public.suppliers),0::bigint,'paused supplier membership grants no supplier visibility');
select is((select count(*) from public.media),0::bigint,'paused supplier membership grants no media visibility');
reset role;
select * from finish();
