-- Library parts are immutable staff copies, validated as renderer documents.
select no_plan();
select tests.create_catalogue_fixture();
select tests.act_as('platform_staff');
select lives_ok($$select public.save_studio_library_part(' Shared stars ', 'stars', tests.design_fixture())$$, 'editor saves a part');
select is((select name from public.studio_library_parts), 'Shared stars', 'name is trimmed');
select is((select created_by from public.studio_library_parts), tests.get_supabase_uid('platform_staff'), 'creator is the verified caller');
select is((select design from public.studio_library_parts), tests.design_fixture(), 'source copied exactly');
select throws_ok($$select public.save_studio_library_part('', 'stars', tests.design_fixture())$$, '23514', null, 'blank name refused');
select throws_ok($$select public.save_studio_library_part('Invalid', 'stars', '{}'::jsonb)$$, '23514', null, 'invalid renderer document refused');
select throws_ok($$select public.save_studio_library_part('Invalid', 'unknown', tests.design_fixture())$$, '23514', null, 'unknown part kind refused');
select throws_ok($$select public.save_studio_library_part('Invalid', 'stars', jsonb_set(tests.design_fixture(), '{breaks,0,layers}', (tests.design_fixture()#>'{breaks,0,layers}') || (tests.design_fixture()#>'{breaks,0,layers}')))$$, '23514', null, 'part envelope must contain exactly one layer');
select ok(not has_table_privilege('authenticated', 'public.studio_library_parts', 'insert'), 'direct inserts denied');
select ok(not has_table_privilege('authenticated', 'public.studio_library_parts', 'update'), 'copies cannot be rewritten by clients');
select ok(not has_table_privilege('authenticated', 'public.studio_library_parts', 'delete'), 'copies cannot be deleted by clients');
select ok(not has_table_privilege('anon', 'public.studio_library_parts', 'select'), 'public callers have no library read grant');
select ok(not has_function_privilege('anon', 'public.save_studio_library_part(text,text,jsonb)', 'execute'), 'public callers have no save grant');
select ok(not has_function_privilege('anon', 'private.save_studio_library_part(text,text,jsonb)', 'execute'), 'public callers have no internal save grant');
reset role;
select tests.act_as('organisation_owner');
select is((select count(*) from public.studio_library_parts), 0::bigint, 'retailer cannot read library');
select throws_ok($$select public.save_studio_library_part('Denied', 'stars', tests.design_fixture())$$, '42501', null, 'retailer cannot save library parts');
reset role;
select tests.act_as('supplier_member');
select is((select count(*) from public.studio_library_parts), 0::bigint, 'supplier cannot read library');
select throws_ok($$select public.save_studio_library_part('Denied', 'stars', tests.design_fixture())$$, '42501', null, 'supplier cannot save');
reset role;
select tests.act_as('anonymous_shopper');
select is((select count(*) from public.studio_library_parts), 0::bigint, 'anonymous shopper cannot read library');
select throws_ok($$select public.save_studio_library_part('Denied', 'stars', tests.design_fixture())$$, '42501', null, 'anonymous shopper cannot save');
reset role;
select tests.act_as('organisation_manager');
select is((select count(*) from public.studio_library_parts), 0::bigint, 'manager cannot read library');
select throws_ok($$select public.save_studio_library_part('Denied', 'stars', tests.design_fixture())$$, '42501', null, 'manager cannot save');
reset role;
select tests.act_as('other_organisation_member');
select is((select count(*) from public.studio_library_parts), 0::bigint, 'other organisation cannot read library');
select throws_ok($$select public.save_studio_library_part('Denied', 'stars', tests.design_fixture())$$, '42501', null, 'other organisation cannot save');
reset role;
select tests.act_as('signed_in_shopper');
select is((select count(*) from public.studio_library_parts), 0::bigint, 'signed-in shopper cannot read library');
select throws_ok($$select public.save_studio_library_part('Denied', 'stars', tests.design_fixture())$$, '42501', null, 'signed-in shopper cannot save');
reset role;
update public.staff_roles set role = 'reviewer' where profile_id = tests.get_supabase_uid('platform_staff');
select tests.act_as('platform_staff');
select is((select count(*) from public.studio_library_parts), 0::bigint, 'reviewer cannot read library');
select throws_ok($$select public.save_studio_library_part('Denied', 'stars', tests.design_fixture())$$, '42501', null, 'reviewer cannot save');
reset role;
update public.staff_roles set role = 'super_admin' where profile_id = tests.get_supabase_uid('platform_staff');
select tests.act_as('platform_staff');
select is((select count(*) from public.studio_library_parts), 1::bigint, 'super admin sees staff copies');
select lives_ok($$select public.save_studio_library_part('Tail', 'tails', tests.design_fixture())$$, 'super admin saves launch tail');
reset role;
update public.profiles set status = 'suspended' where id = tests.get_supabase_uid('platform_staff');
select tests.act_as('platform_staff');
select is((select count(*) from public.studio_library_parts), 0::bigint, 'suspended staff cannot read');
select throws_ok($$select public.save_studio_library_part('Denied', 'stars', tests.design_fixture())$$, '42501', null, 'suspended staff cannot save');
select * from finish();
