-- Failed acceptance never leaves orphaned effects, product drafts or published changes.
select no_plan();
select tests.create_import_fixture();
insert into public.design_candidates(id,analysis_id,source,proposal,renderer) values ('83000000-0000-0000-0000-000000000003','82000000-0000-0000-0000-000000000002','fit',tests.candidate_proposal(),'fixture');
select tests.act_as('platform_staff');
select throws_ok($query$select public.accept_design_candidate('83000000-0000-0000-0000-000000000003')$query$, '23514', null, 'new product requires explicit metadata');
select throws_ok($query$select public.accept_design_candidate('83000000-0000-0000-0000-000000000003','new-reconstruction','New reconstruction','pack')$query$, '23514', null, 'selection packs cannot accept tube proposals');
reset role;
update public.design_candidates set proposal = '{}'::jsonb where id = '83000000-0000-0000-0000-000000000003';
select tests.act_as('platform_staff');
select throws_ok($query$select public.accept_design_candidate('83000000-0000-0000-0000-000000000003','new-reconstruction','New reconstruction','cake')$query$, '23514', null, 'empty proposal is rejected');
select is((select count(*) from public.effects), 3::bigint, 'failure creates no effect parents');
select is((select count(*) from public.effect_versions), 4::bigint, 'failure creates no effect drafts');
select is((select count(*) from public.products), 4::bigint, 'failure creates no product parents');
select is((select count(*) from public.product_versions), 2::bigint, 'failure creates no product drafts');
reset role;
update public.design_candidates set proposal = jsonb_set(tests.candidate_proposal(),'{effects,a,template}','"missing-template"') where id = '83000000-0000-0000-0000-000000000003';
select tests.act_as('platform_staff');
select throws_ok($query$select public.accept_design_candidate('83000000-0000-0000-0000-000000000003','new-reconstruction','New reconstruction','cake')$query$, '23514', null, 'missing template is rejected');
select is((select count(*) from public.effects), 3::bigint, 'failure creates no effect parents');
select is((select count(*) from public.effect_versions), 4::bigint, 'failure creates no effect drafts');
select is((select count(*) from public.products), 4::bigint, 'failure creates no product parents');
select is((select count(*) from public.product_versions), 2::bigint, 'failure creates no product drafts');
reset role;
update public.design_candidates set proposal = jsonb_set(tests.candidate_proposal(),'{effects,a,template}','"draft-effect"') where id = '83000000-0000-0000-0000-000000000003';
select tests.act_as('platform_staff');
select throws_ok($query$select public.accept_design_candidate('83000000-0000-0000-0000-000000000003','new-reconstruction','New reconstruction','cake')$query$, '23514', null, 'unpublished template is rejected');
select is((select count(*) from public.effects), 3::bigint, 'failure creates no effect parents');
select is((select count(*) from public.effect_versions), 4::bigint, 'failure creates no effect drafts');
select is((select count(*) from public.products), 4::bigint, 'failure creates no product parents');
select is((select count(*) from public.product_versions), 2::bigint, 'failure creates no product drafts');
reset role;
update public.design_candidates set proposal = jsonb_set(tests.candidate_proposal(),'{effects,a,overrides}','[]') where id = '83000000-0000-0000-0000-000000000003';
select tests.act_as('platform_staff');
select throws_ok($query$select public.accept_design_candidate('83000000-0000-0000-0000-000000000003','new-reconstruction','New reconstruction','cake')$query$, '23514', null, 'array overrides are rejected');
select is((select count(*) from public.effects), 3::bigint, 'failure creates no effect parents');
select is((select count(*) from public.effect_versions), 4::bigint, 'failure creates no effect drafts');
select is((select count(*) from public.products), 4::bigint, 'failure creates no product parents');
select is((select count(*) from public.product_versions), 2::bigint, 'failure creates no product drafts');
reset role;
update public.design_candidates set proposal = jsonb_set(tests.candidate_proposal(),'{effects,a,overrides}','{"unknown":1}') where id = '83000000-0000-0000-0000-000000000003';
select tests.act_as('platform_staff');
select throws_ok($query$select public.accept_design_candidate('83000000-0000-0000-0000-000000000003','new-reconstruction','New reconstruction','cake')$query$, '23514', null, 'unknown design fields are rejected');
select is((select count(*) from public.effects), 3::bigint, 'failure creates no effect parents');
select is((select count(*) from public.effect_versions), 4::bigint, 'failure creates no effect drafts');
select is((select count(*) from public.products), 4::bigint, 'failure creates no product parents');
select is((select count(*) from public.product_versions), 2::bigint, 'failure creates no product drafts');
reset role;
update public.design_candidates set proposal = jsonb_set(tests.candidate_proposal(),'{effects,a,overrides}','{"kind":"mine"}') where id = '83000000-0000-0000-0000-000000000003';
select tests.act_as('platform_staff');
select throws_ok($query$select public.accept_design_candidate('83000000-0000-0000-0000-000000000003','new-reconstruction','New reconstruction','cake')$query$, '23514', null, 'template kind cannot change');
select is((select count(*) from public.effects), 3::bigint, 'failure creates no effect parents');
select is((select count(*) from public.effect_versions), 4::bigint, 'failure creates no effect drafts');
select is((select count(*) from public.products), 4::bigint, 'failure creates no product parents');
select is((select count(*) from public.product_versions), 2::bigint, 'failure creates no product drafts');
reset role;
update public.design_candidates set proposal = jsonb_set(tests.candidate_proposal(),'{effects,a,overrides}','{"launch":{"height_m":-1}}') where id = '83000000-0000-0000-0000-000000000003';
select tests.act_as('platform_staff');
select throws_ok($query$select public.accept_design_candidate('83000000-0000-0000-0000-000000000003','new-reconstruction','New reconstruction','cake')$query$, '23514', null, 'out-of-bounds design is rejected');
select is((select count(*) from public.effects), 3::bigint, 'failure creates no effect parents');
select is((select count(*) from public.effect_versions), 4::bigint, 'failure creates no effect drafts');
select is((select count(*) from public.products), 4::bigint, 'failure creates no product parents');
select is((select count(*) from public.product_versions), 2::bigint, 'failure creates no product drafts');
reset role;
update public.design_candidates set proposal = jsonb_set(tests.candidate_proposal(),'{effects,a,overrides}','{"launch":null}') where id = '83000000-0000-0000-0000-000000000003';
select tests.act_as('platform_staff');
select throws_ok($query$select public.accept_design_candidate('83000000-0000-0000-0000-000000000003','new-reconstruction','New reconstruction','cake')$query$, '23514', null, 'explicit null override is validated');
select is((select count(*) from public.effects), 3::bigint, 'failure creates no effect parents');
select is((select count(*) from public.effect_versions), 4::bigint, 'failure creates no effect drafts');
select is((select count(*) from public.products), 4::bigint, 'failure creates no product parents');
select is((select count(*) from public.product_versions), 2::bigint, 'failure creates no product drafts');
reset role;
update public.design_candidates set proposal = jsonb_set(tests.candidate_proposal(),'{effects,a,extra}','true') where id = '83000000-0000-0000-0000-000000000003';
select tests.act_as('platform_staff');
select throws_ok($query$select public.accept_design_candidate('83000000-0000-0000-0000-000000000003','new-reconstruction','New reconstruction','cake')$query$, '23514', null, 'unknown effect proposal fields are rejected');
select is((select count(*) from public.effects), 3::bigint, 'failure creates no effect parents');
select is((select count(*) from public.effect_versions), 4::bigint, 'failure creates no effect drafts');
select is((select count(*) from public.products), 4::bigint, 'failure creates no product parents');
select is((select count(*) from public.product_versions), 2::bigint, 'failure creates no product drafts');
reset role;
update public.design_candidates set proposal = jsonb_set(tests.candidate_proposal(),'{composition}','{}') where id = '83000000-0000-0000-0000-000000000003';
select tests.act_as('platform_staff');
select throws_ok($query$select public.accept_design_candidate('83000000-0000-0000-0000-000000000003','new-reconstruction','New reconstruction','cake')$query$, '23514', null, 'invalid composition is rejected');
select is((select count(*) from public.effects), 3::bigint, 'failure creates no effect parents');
select is((select count(*) from public.effect_versions), 4::bigint, 'failure creates no effect drafts');
select is((select count(*) from public.products), 4::bigint, 'failure creates no product parents');
select is((select count(*) from public.product_versions), 2::bigint, 'failure creates no product drafts');
reset role;
update public.design_candidates set proposal = jsonb_set(tests.candidate_proposal(),'{composition,tubes}','[]') where id = '83000000-0000-0000-0000-000000000003';
select tests.act_as('platform_staff');
select throws_ok($query$select public.accept_design_candidate('83000000-0000-0000-0000-000000000003','new-reconstruction','New reconstruction','cake')$query$, '23514', null, 'empty composition is rejected');
select is((select count(*) from public.effects), 3::bigint, 'failure creates no effect parents');
select is((select count(*) from public.effect_versions), 4::bigint, 'failure creates no effect drafts');
select is((select count(*) from public.products), 4::bigint, 'failure creates no product parents');
select is((select count(*) from public.product_versions), 2::bigint, 'failure creates no product drafts');
reset role;
update public.design_candidates set proposal = jsonb_set(tests.candidate_proposal(),'{composition,tubes,0,letter}','"b"') where id = '83000000-0000-0000-0000-000000000003';
select tests.act_as('platform_staff');
select throws_ok($query$select public.accept_design_candidate('83000000-0000-0000-0000-000000000003','new-reconstruction','New reconstruction','cake')$query$, '23514', null, 'missing effect binding is rejected');
select is((select count(*) from public.effects), 3::bigint, 'failure creates no effect parents');
select is((select count(*) from public.effect_versions), 4::bigint, 'failure creates no effect drafts');
select is((select count(*) from public.products), 4::bigint, 'failure creates no product parents');
select is((select count(*) from public.product_versions), 2::bigint, 'failure creates no product drafts');
reset role;
update public.design_candidates set proposal = jsonb_set(tests.candidate_proposal(),'{effects,b}',jsonb_build_object('template','published-effect')) where id = '83000000-0000-0000-0000-000000000003';
select tests.act_as('platform_staff');
select throws_ok($query$select public.accept_design_candidate('83000000-0000-0000-0000-000000000003','new-reconstruction','New reconstruction','cake')$query$, '23514', null, 'unused binding is rejected');
select is((select count(*) from public.effects), 3::bigint, 'failure creates no effect parents');
select is((select count(*) from public.effect_versions), 4::bigint, 'failure creates no effect drafts');
select is((select count(*) from public.products), 4::bigint, 'failure creates no product parents');
select is((select count(*) from public.product_versions), 2::bigint, 'failure creates no product drafts');
reset role;
update public.design_candidates set proposal = jsonb_set(tests.candidate_proposal(),'{composition,tubes,0,t_ms}','null') where id = '83000000-0000-0000-0000-000000000003';
select tests.act_as('platform_staff');
select throws_ok($query$select public.accept_design_candidate('83000000-0000-0000-0000-000000000003','new-reconstruction','New reconstruction','cake')$query$, '23514', null, 'cake firing time is required');
select is((select count(*) from public.effects), 3::bigint, 'failure creates no effect parents');
select is((select count(*) from public.effect_versions), 4::bigint, 'failure creates no effect drafts');
select is((select count(*) from public.products), 4::bigint, 'failure creates no product parents');
select is((select count(*) from public.product_versions), 2::bigint, 'failure creates no product drafts');
reset role;
update public.design_candidates set proposal = tests.candidate_proposal() || '{"unexpected":true}'::jsonb where id = '83000000-0000-0000-0000-000000000003';
select tests.act_as('platform_staff');
select throws_ok($query$select public.accept_design_candidate('83000000-0000-0000-0000-000000000003','new-reconstruction','New reconstruction','cake')$query$, '23514', null, 'unknown proposal fields are rejected');
select is((select count(*) from public.effects), 3::bigint, 'failure creates no effect parents');
select is((select count(*) from public.effect_versions), 4::bigint, 'failure creates no effect drafts');
select is((select count(*) from public.products), 4::bigint, 'failure creates no product parents');
select is((select count(*) from public.product_versions), 2::bigint, 'failure creates no product drafts');
reset role;
update public.design_candidates set proposal = jsonb_set(tests.candidate_proposal(),'{composition,tubes}',(tests.composition_fixture()->'tubes') || (tests.composition_fixture()->'tubes')) where id = '83000000-0000-0000-0000-000000000003';
select tests.act_as('platform_staff');
select throws_ok($query$select public.accept_design_candidate('83000000-0000-0000-0000-000000000003','new-reconstruction','New reconstruction','cake')$query$, '23514', null, 'duplicate tube indices are rejected');
select is((select count(*) from public.effects), 3::bigint, 'failure creates no effect parents');
select is((select count(*) from public.effect_versions), 4::bigint, 'failure creates no effect drafts');
select is((select count(*) from public.products), 4::bigint, 'failure creates no product parents');
select is((select count(*) from public.product_versions), 2::bigint, 'failure creates no product drafts');
reset role;
update public.design_candidates set proposal = jsonb_build_object('effects',jsonb_build_object('a',jsonb_build_object('template','published-effect'),'b',jsonb_build_object('template','missing-template')),'composition',jsonb_build_object('tubes',(tests.composition_fixture()->'tubes') || jsonb_build_object('i',1,'letter','b','t_ms',1000,'angle_deg',0))) where id = '83000000-0000-0000-0000-000000000003';
select tests.act_as('platform_staff');
select throws_ok($query$select public.accept_design_candidate('83000000-0000-0000-0000-000000000003','new-reconstruction','New reconstruction','cake')$query$, '23514', null, 'invalid second effect rolls back the first draft');
select is((select count(*) from public.effects), 3::bigint, 'failure creates no effect parents');
select is((select count(*) from public.effect_versions), 4::bigint, 'failure creates no effect drafts');
select is((select count(*) from public.products), 4::bigint, 'failure creates no product parents');
select is((select count(*) from public.product_versions), 2::bigint, 'failure creates no product drafts');
reset role;
update public.design_candidates set proposal = tests.candidate_proposal() where id = '83000000-0000-0000-0000-000000000003';
update public.video_analyses set status = 'fitting' where id = '82000000-0000-0000-0000-000000000002';
select tests.act_as('platform_staff');
select throws_ok($query$select public.accept_design_candidate('83000000-0000-0000-0000-000000000003','new-reconstruction','New reconstruction','cake')$query$, '23514', null, 'unfinished analysis cannot be accepted');
select is((select count(*) from public.effects), 3::bigint, 'failure creates no effect parents');
select is((select count(*) from public.effect_versions), 4::bigint, 'failure creates no effect drafts');
select is((select count(*) from public.products), 4::bigint, 'failure creates no product parents');
select is((select count(*) from public.product_versions), 2::bigint, 'failure creates no product drafts');
reset role;
update public.video_analyses set status = 'ready', product_id = '60000000-0000-0000-0000-000000000002' where id = '82000000-0000-0000-0000-000000000002';
select tests.act_as('platform_staff');
select throws_ok($query$select public.accept_design_candidate('83000000-0000-0000-0000-000000000003','new-reconstruction','New reconstruction','cake')$query$, '23514', null, 'existing open draft is preserved');
select is((select count(*) from public.effects), 3::bigint, 'failure creates no effect parents');
select is((select count(*) from public.effect_versions), 4::bigint, 'failure creates no effect drafts');
select is((select count(*) from public.products), 4::bigint, 'failure creates no product parents');
select is((select count(*) from public.product_versions), 2::bigint, 'failure creates no product drafts');
reset role;
update public.video_analyses set product_id = null where id = '82000000-0000-0000-0000-000000000002';
select tests.act_as('platform_staff');
select throws_ok($query$select public.accept_design_candidate('83000000-0000-0000-0000-000000000003','published-product','New reconstruction','cake')$query$, '23505', null, 'product slug conflict rolls back created effects');
select is((select count(*) from public.effects), 3::bigint, 'failure creates no effect parents');
select is((select count(*) from public.effect_versions), 4::bigint, 'failure creates no effect drafts');
select is((select count(*) from public.products), 4::bigint, 'failure creates no product parents');
select is((select count(*) from public.product_versions), 2::bigint, 'failure creates no product drafts');
reset role;
update public.effects set is_template = false where slug = 'published-effect';
select tests.act_as('platform_staff');
select throws_ok($query$select public.accept_design_candidate('83000000-0000-0000-0000-000000000003','new-reconstruction','New reconstruction','cake')$query$, '23514', null, 'ordinary published effect cannot masquerade as a template');
select is((select count(*) from public.effects), 3::bigint, 'failure creates no effect parents');
select is((select count(*) from public.effect_versions), 4::bigint, 'failure creates no effect drafts');
select is((select count(*) from public.products), 4::bigint, 'failure creates no product parents');
select is((select count(*) from public.product_versions), 2::bigint, 'failure creates no product drafts');
reset role;
update public.effects set is_template = true where slug = 'published-effect';
update public.design_candidates set proposal = jsonb_set(tests.candidate_proposal(),'{effects,a}','[]') where id = '83000000-0000-0000-0000-000000000003';
select tests.act_as('platform_staff');
select throws_ok($query$select public.accept_design_candidate('83000000-0000-0000-0000-000000000003','new-reconstruction','New reconstruction','cake')$query$, '23514', null, 'scalar effect proposal is an explicit validation error');
reset role;
update public.design_candidates set proposal = jsonb_set(tests.candidate_proposal(),'{composition}',jsonb_build_object('box',jsonb_build_object('rows',1,'cols',1,'pitch_mm',40),'tubes',jsonb_build_array(jsonb_build_object('i',1,'letter','a','t_ms',0,'angle_deg',0)))) where id = '83000000-0000-0000-0000-000000000003';
select tests.act_as('platform_staff');
select throws_ok($query$select public.accept_design_candidate('83000000-0000-0000-0000-000000000003','new-reconstruction','New reconstruction','cake')$query$, '23514', null, 'tube outside the grid is rejected');
reset role;
update public.design_candidates set proposal = tests.candidate_proposal() where id = '83000000-0000-0000-0000-000000000003';
update public.video_analyses set product_id = '60000000-0000-0000-0000-000000000001' where id = '82000000-0000-0000-0000-000000000002';
update public.products set status = 'archived' where id = '60000000-0000-0000-0000-000000000001';
select tests.act_as('platform_staff');
select throws_ok($query$select public.accept_design_candidate('83000000-0000-0000-0000-000000000003')$query$, '23514', null, 'archived product is not rewritten');
reset role;
select is(private.merge_design_overrides('{"nested":{"a":1,"b":2},"array":[1,2]}','{"nested":{"a":3},"array":[9]}'),'{"nested":{"a":3,"b":2},"array":[9]}'::jsonb,'object merge preserves fields while arrays replace');
select * from finish();
