-- Allowed and denied shopper policy cases use real identities and two retailers.
select no_plan();
select tests.create_shoppers_fixture();
reset role;
select tests.act_as('platform_staff');
select is((select count(*) from public.plan_sessions),0::bigint,'platform_staff plan_sessions read boundary');
select is((select count(*) from public.plan_candidates),0::bigint,'platform_staff plan_candidates read boundary');
select is((select count(*) from public.plan_edits),0::bigint,'platform_staff plan_edits read boundary');
select is((select count(*) from public.lists),0::bigint,'platform_staff lists read boundary');
select is((select count(*) from public.list_items),0::bigint,'platform_staff list_items read boundary');
select is((select count(*) from public.follows),0::bigint,'platform_staff follows read boundary');
select is((select count(*) from public.privacy_requests),0::bigint,'platform_staff privacy_requests read boundary');
reset role;
select tests.act_as('organisation_owner');
select is((select count(*) from public.plan_sessions),0::bigint,'organisation_owner plan_sessions read boundary');
select is((select count(*) from public.plan_candidates),0::bigint,'organisation_owner plan_candidates read boundary');
select is((select count(*) from public.plan_edits),0::bigint,'organisation_owner plan_edits read boundary');
select is((select count(*) from public.lists),1::bigint,'organisation_owner lists read boundary');
select is((select count(*) from public.list_items),1::bigint,'organisation_owner list_items read boundary');
select is((select count(*) from public.follows),1::bigint,'organisation_owner follows read boundary');
select is((select count(*) from public.privacy_requests),0::bigint,'organisation_owner privacy_requests read boundary');
select is((select count(*) from public.lists where id = 'a2000000-0000-0000-0000-000000000004'),0::bigint,'organisation_owner cannot see another retailer redeemed list');
select is((select count(*) from public.lists where status = 'open'),0::bigint,'retailer cannot read open lists through table policy');
select is((select count(*) from public.follows where not visible_to_shop),0::bigint,'retailer cannot read hidden consent');
reset role;
select tests.act_as('organisation_manager');
select is((select count(*) from public.plan_sessions),0::bigint,'organisation_manager plan_sessions read boundary');
select is((select count(*) from public.plan_candidates),0::bigint,'organisation_manager plan_candidates read boundary');
select is((select count(*) from public.plan_edits),0::bigint,'organisation_manager plan_edits read boundary');
select is((select count(*) from public.lists),1::bigint,'organisation_manager lists read boundary');
select is((select count(*) from public.list_items),1::bigint,'organisation_manager list_items read boundary');
select is((select count(*) from public.follows),1::bigint,'organisation_manager follows read boundary');
select is((select count(*) from public.privacy_requests),0::bigint,'organisation_manager privacy_requests read boundary');
select is((select count(*) from public.lists where id = 'a2000000-0000-0000-0000-000000000004'),0::bigint,'organisation_manager cannot see another retailer redeemed list');
select is((select count(*) from public.lists where status = 'open'),0::bigint,'retailer cannot read open lists through table policy');
select is((select count(*) from public.follows where not visible_to_shop),0::bigint,'retailer cannot read hidden consent');
reset role;
select tests.act_as('other_organisation_member');
select is((select count(*) from public.plan_sessions),0::bigint,'other_organisation_member plan_sessions read boundary');
select is((select count(*) from public.plan_candidates),0::bigint,'other_organisation_member plan_candidates read boundary');
select is((select count(*) from public.plan_edits),0::bigint,'other_organisation_member plan_edits read boundary');
select is((select count(*) from public.lists),1::bigint,'other_organisation_member lists read boundary');
select is((select count(*) from public.list_items),1::bigint,'other_organisation_member list_items read boundary');
select is((select count(*) from public.follows),1::bigint,'other_organisation_member follows read boundary');
select is((select count(*) from public.privacy_requests),0::bigint,'other_organisation_member privacy_requests read boundary');
select is((select count(*) from public.lists where id = 'a2000000-0000-0000-0000-000000000003'),0::bigint,'other_organisation_member cannot see another retailer redeemed list');
select is((select count(*) from public.lists where status = 'open'),0::bigint,'retailer cannot read open lists through table policy');
select is((select count(*) from public.follows where not visible_to_shop),0::bigint,'retailer cannot read hidden consent');
reset role;
select tests.act_as('anonymous_shopper');
select is((select count(*) from public.plan_sessions),1::bigint,'anonymous_shopper plan_sessions read boundary');
select is((select count(*) from public.plan_candidates),1::bigint,'anonymous_shopper plan_candidates read boundary');
select is((select count(*) from public.plan_edits),1::bigint,'anonymous_shopper plan_edits read boundary');
select is((select count(*) from public.lists),2::bigint,'anonymous_shopper lists read boundary');
select is((select count(*) from public.list_items),2::bigint,'anonymous_shopper list_items read boundary');
select is((select count(*) from public.follows),2::bigint,'anonymous_shopper follows read boundary');
select is((select count(*) from public.privacy_requests),1::bigint,'anonymous_shopper privacy_requests read boundary');
select is((select count(*) from public.plan_sessions where id = 'a0000000-0000-0000-0000-000000000001'),0::bigint,'anonymous_shopper cannot read another shopper session');
select is((select count(*) from public.plan_candidates where session_id = 'a0000000-0000-0000-0000-000000000001'),0::bigint,'anonymous_shopper cannot read another shopper candidate');
select is((select count(*) from public.plan_edits where session_id = 'a0000000-0000-0000-0000-000000000001'),0::bigint,'anonymous_shopper cannot read another shopper edits');
reset role;
select tests.act_as('signed_in_shopper');
select is((select count(*) from public.plan_sessions),1::bigint,'signed_in_shopper plan_sessions read boundary');
select is((select count(*) from public.plan_candidates),1::bigint,'signed_in_shopper plan_candidates read boundary');
select is((select count(*) from public.plan_edits),1::bigint,'signed_in_shopper plan_edits read boundary');
select is((select count(*) from public.lists),2::bigint,'signed_in_shopper lists read boundary');
select is((select count(*) from public.list_items),2::bigint,'signed_in_shopper list_items read boundary');
select is((select count(*) from public.follows),1::bigint,'signed_in_shopper follows read boundary');
select is((select count(*) from public.privacy_requests),1::bigint,'signed_in_shopper privacy_requests read boundary');
select is((select count(*) from public.plan_sessions where id = 'a0000000-0000-0000-0000-000000000002'),0::bigint,'signed_in_shopper cannot read another shopper session');
select is((select count(*) from public.plan_candidates where session_id = 'a0000000-0000-0000-0000-000000000002'),0::bigint,'signed_in_shopper cannot read another shopper candidate');
select is((select count(*) from public.plan_edits where session_id = 'a0000000-0000-0000-0000-000000000002'),0::bigint,'signed_in_shopper cannot read another shopper edits');
reset role;
select tests.act_as('supplier_member');
select is((select count(*) from public.plan_sessions),0::bigint,'supplier_member plan_sessions read boundary');
select is((select count(*) from public.plan_candidates),0::bigint,'supplier_member plan_candidates read boundary');
select is((select count(*) from public.plan_edits),0::bigint,'supplier_member plan_edits read boundary');
select is((select count(*) from public.lists),0::bigint,'supplier_member lists read boundary');
select is((select count(*) from public.list_items),0::bigint,'supplier_member list_items read boundary');
select is((select count(*) from public.follows),0::bigint,'supplier_member follows read boundary');
select is((select count(*) from public.privacy_requests),0::bigint,'supplier_member privacy_requests read boundary');
reset role;
select tests.act_as('signed_in_shopper');
select lives_ok($$insert into public.follows(shopper_id,organisation_id,consent_text_version) values (auth.uid(),'10000000-0000-0000-0000-000000000002','new')$$,'signed_in_shopper can insert own consent');
select lives_ok($$update public.follows set visible_to_shop = true,marketing_opt_in = true where organisation_id = '10000000-0000-0000-0000-000000000002'$$,'signed_in_shopper can update own consent');
select lives_ok($$insert into public.privacy_requests(shopper_id,kind) values (auth.uid(),'export')$$,'signed_in_shopper can request own export');
select throws_ok($$insert into public.privacy_requests(shopper_id,kind) values (tests.get_supabase_uid('organisation_owner'),'export')$$,'42501',null,'signed_in_shopper cannot request another account export');
select lives_ok($$delete from public.follows where organisation_id = '10000000-0000-0000-0000-000000000002'$$,'signed_in_shopper can delete own follow');
reset role;
select tests.act_as('anonymous_shopper');
select lives_ok($$delete from public.follows where organisation_id = '10000000-0000-0000-0000-000000000001'$$,'anonymous shopper can withdraw own consent');
select lives_ok($$insert into public.follows(shopper_id,organisation_id,consent_text_version) values (auth.uid(),'10000000-0000-0000-0000-000000000001','new')$$,'anonymous_shopper can insert own consent');
select lives_ok($$update public.follows set visible_to_shop = true,marketing_opt_in = true where organisation_id = '10000000-0000-0000-0000-000000000001'$$,'anonymous_shopper can update own consent');
select lives_ok($$insert into public.privacy_requests(shopper_id,kind) values (auth.uid(),'export')$$,'anonymous_shopper can request own export');
select throws_ok($$insert into public.privacy_requests(shopper_id,kind) values (tests.get_supabase_uid('organisation_owner'),'export')$$,'42501',null,'anonymous_shopper cannot request another account export');
select lives_ok($$delete from public.follows where organisation_id = '10000000-0000-0000-0000-000000000001'$$,'anonymous_shopper can delete own follow');
reset role;
select tests.act_as('platform_staff');
select throws_ok($$insert into public.follows(shopper_id,organisation_id,consent_text_version) values (tests.get_supabase_uid('signed_in_shopper'),'10000000-0000-0000-0000-000000000002','forged')$$,'42501',null,'platform_staff cannot create shopper consent');
with changed as (update public.follows set visible_to_shop = false returning *) select is((select count(*) from changed),0::bigint,'platform_staff cannot change shopper consent');
with removed as (delete from public.follows returning *) select is((select count(*) from removed),0::bigint,'platform_staff cannot delete shopper consent');
reset role;
select tests.act_as('organisation_owner');
select throws_ok($$insert into public.follows(shopper_id,organisation_id,consent_text_version) values (tests.get_supabase_uid('signed_in_shopper'),'10000000-0000-0000-0000-000000000002','forged')$$,'42501',null,'organisation_owner cannot create shopper consent');
with changed as (update public.follows set visible_to_shop = false returning *) select is((select count(*) from changed),0::bigint,'organisation_owner cannot change shopper consent');
with removed as (delete from public.follows returning *) select is((select count(*) from removed),0::bigint,'organisation_owner cannot delete shopper consent');
reset role;
select tests.act_as('organisation_manager');
select throws_ok($$insert into public.follows(shopper_id,organisation_id,consent_text_version) values (tests.get_supabase_uid('signed_in_shopper'),'10000000-0000-0000-0000-000000000002','forged')$$,'42501',null,'organisation_manager cannot create shopper consent');
with changed as (update public.follows set visible_to_shop = false returning *) select is((select count(*) from changed),0::bigint,'organisation_manager cannot change shopper consent');
with removed as (delete from public.follows returning *) select is((select count(*) from removed),0::bigint,'organisation_manager cannot delete shopper consent');
reset role;
select tests.act_as('other_organisation_member');
select throws_ok($$insert into public.follows(shopper_id,organisation_id,consent_text_version) values (tests.get_supabase_uid('signed_in_shopper'),'10000000-0000-0000-0000-000000000002','forged')$$,'42501',null,'other_organisation_member cannot create shopper consent');
with changed as (update public.follows set visible_to_shop = false returning *) select is((select count(*) from changed),0::bigint,'other_organisation_member cannot change shopper consent');
with removed as (delete from public.follows returning *) select is((select count(*) from removed),0::bigint,'other_organisation_member cannot delete shopper consent');
reset role;
select tests.act_as('supplier_member');
select throws_ok($$insert into public.follows(shopper_id,organisation_id,consent_text_version) values (tests.get_supabase_uid('signed_in_shopper'),'10000000-0000-0000-0000-000000000002','forged')$$,'42501',null,'supplier_member cannot create shopper consent');
with changed as (update public.follows set visible_to_shop = false returning *) select is((select count(*) from changed),0::bigint,'supplier_member cannot change shopper consent');
with removed as (delete from public.follows returning *) select is((select count(*) from removed),0::bigint,'supplier_member cannot delete shopper consent');
reset role;
select tests.act_as('signed_in_shopper');
with changed as (update public.follows set visible_to_shop = true where shopper_id = tests.get_supabase_uid('anonymous_shopper') returning *) select is((select count(*) from changed),0::bigint,'shopper cannot update another shopper consent');
with removed as (delete from public.follows where shopper_id = tests.get_supabase_uid('anonymous_shopper') returning *) select is((select count(*) from removed),0::bigint,'shopper cannot delete another shopper consent');
reset role;
select tests.act_as('signed_in_shopper');
select throws_ok($$delete from public.plan_sessions$$,'42501',null,'signed_in_shopper cannot delete trusted plan_sessions snapshots');
select throws_ok($$update public.plan_sessions set created_at = now()$$,'42501',null,'signed_in_shopper cannot rewrite trusted plan_sessions snapshots');
select throws_ok($$delete from public.plan_candidates$$,'42501',null,'signed_in_shopper cannot delete trusted plan_candidates snapshots');
select throws_ok($$update public.plan_candidates set created_at = now()$$,'42501',null,'signed_in_shopper cannot rewrite trusted plan_candidates snapshots');
select throws_ok($$delete from public.plan_edits$$,'42501',null,'signed_in_shopper cannot delete trusted plan_edits snapshots');
select throws_ok($$update public.plan_edits set created_at = now()$$,'42501',null,'signed_in_shopper cannot rewrite trusted plan_edits snapshots');
select throws_ok($$delete from public.lists$$,'42501',null,'signed_in_shopper cannot delete trusted lists snapshots');
select throws_ok($$update public.lists set created_at = now()$$,'42501',null,'signed_in_shopper cannot rewrite trusted lists snapshots');
select throws_ok($$delete from public.list_items$$,'42501',null,'signed_in_shopper cannot delete trusted list_items snapshots');
select throws_ok($$update public.list_items set created_at = now()$$,'42501',null,'signed_in_shopper cannot rewrite trusted list_items snapshots');
reset role;
select tests.act_as('anonymous_shopper');
select throws_ok($$delete from public.plan_sessions$$,'42501',null,'anonymous_shopper cannot delete trusted plan_sessions snapshots');
select throws_ok($$update public.plan_sessions set created_at = now()$$,'42501',null,'anonymous_shopper cannot rewrite trusted plan_sessions snapshots');
select throws_ok($$delete from public.plan_candidates$$,'42501',null,'anonymous_shopper cannot delete trusted plan_candidates snapshots');
select throws_ok($$update public.plan_candidates set created_at = now()$$,'42501',null,'anonymous_shopper cannot rewrite trusted plan_candidates snapshots');
select throws_ok($$delete from public.plan_edits$$,'42501',null,'anonymous_shopper cannot delete trusted plan_edits snapshots');
select throws_ok($$update public.plan_edits set created_at = now()$$,'42501',null,'anonymous_shopper cannot rewrite trusted plan_edits snapshots');
select throws_ok($$delete from public.lists$$,'42501',null,'anonymous_shopper cannot delete trusted lists snapshots');
select throws_ok($$update public.lists set created_at = now()$$,'42501',null,'anonymous_shopper cannot rewrite trusted lists snapshots');
select throws_ok($$delete from public.list_items$$,'42501',null,'anonymous_shopper cannot delete trusted list_items snapshots');
select throws_ok($$update public.list_items set created_at = now()$$,'42501',null,'anonymous_shopper cannot rewrite trusted list_items snapshots');
reset role;
select tests.act_as('organisation_owner');
select throws_ok($$delete from public.plan_sessions$$,'42501',null,'organisation_owner cannot delete trusted plan_sessions snapshots');
select throws_ok($$update public.plan_sessions set created_at = now()$$,'42501',null,'organisation_owner cannot rewrite trusted plan_sessions snapshots');
select throws_ok($$delete from public.plan_candidates$$,'42501',null,'organisation_owner cannot delete trusted plan_candidates snapshots');
select throws_ok($$update public.plan_candidates set created_at = now()$$,'42501',null,'organisation_owner cannot rewrite trusted plan_candidates snapshots');
select throws_ok($$delete from public.plan_edits$$,'42501',null,'organisation_owner cannot delete trusted plan_edits snapshots');
select throws_ok($$update public.plan_edits set created_at = now()$$,'42501',null,'organisation_owner cannot rewrite trusted plan_edits snapshots');
select throws_ok($$delete from public.lists$$,'42501',null,'organisation_owner cannot delete trusted lists snapshots');
select throws_ok($$update public.lists set created_at = now()$$,'42501',null,'organisation_owner cannot rewrite trusted lists snapshots');
select throws_ok($$delete from public.list_items$$,'42501',null,'organisation_owner cannot delete trusted list_items snapshots');
select throws_ok($$update public.list_items set created_at = now()$$,'42501',null,'organisation_owner cannot rewrite trusted list_items snapshots');
reset role;
select tests.act_as_public();
select throws_ok($$select * from public.plan_sessions$$,'42501',null,'public cannot read plan_sessions');
select throws_ok($$select * from public.plan_candidates$$,'42501',null,'public cannot read plan_candidates');
select throws_ok($$select * from public.plan_edits$$,'42501',null,'public cannot read plan_edits');
select throws_ok($$select * from public.lists$$,'42501',null,'public cannot read lists');
select throws_ok($$select * from public.list_items$$,'42501',null,'public cannot read list_items');
select throws_ok($$select * from public.follows$$,'42501',null,'public cannot read follows');
select throws_ok($$select * from public.privacy_requests$$,'42501',null,'public cannot read privacy_requests');
reset role;
update public.profiles set status = 'suspended' where id = tests.get_supabase_uid('signed_in_shopper');
select tests.act_as('signed_in_shopper');
select is((select count(*) from public.plan_sessions),0::bigint,'suspended shopper cannot read plan_sessions');
select is((select count(*) from public.plan_candidates),0::bigint,'suspended shopper cannot read plan_candidates');
select is((select count(*) from public.plan_edits),0::bigint,'suspended shopper cannot read plan_edits');
select is((select count(*) from public.lists),0::bigint,'suspended shopper cannot read lists');
select is((select count(*) from public.list_items),0::bigint,'suspended shopper cannot read list_items');
select is((select count(*) from public.follows),0::bigint,'suspended shopper cannot read follows');
select is((select count(*) from public.privacy_requests),0::bigint,'suspended shopper cannot read privacy_requests');
select finish();
