-- Atomic token refill, fenced worker ownership and bounded retry transitions.
select no_plan();
select tests.create_operations_fixture();
select ok(private.consume_rate_limit('fixture',2,1),'first token consumed');
select ok(private.consume_rate_limit('fixture',2,1),'second token consumed');
select ok(not private.consume_rate_limit('fixture',2,1),'exhausted bucket refused');
update public.rate_limit_buckets set refilled_at = clock_timestamp() - interval '1 second' where key = 'fixture';
select ok(private.consume_rate_limit('fixture',2,1),'elapsed wall clock refills token');
update public.rate_limit_buckets set refilled_at = clock_timestamp() - interval '1 day' where key = 'fixture';
select ok(private.consume_rate_limit('fixture',2,1),'idle refill capped');
select ok((select tokens <= 1 from public.rate_limit_buckets where key = 'fixture'),'capacity prevents unlimited accumulation');
select throws_ok($$select private.consume_rate_limit('invalid',0,1)$$,'23514',null,'invalid capacity refused');
select throws_ok($$select private.consume_rate_limit('invalid',1,0)$$,'23514',null,'zero refill refused');
set local role service_role;
select is((public.claim_job(array['music_analyse'],'worker-a')).id,'b0000000-0000-0000-0000-000000000001'::uuid,'worker claims requested due kind');
select ok((public.claim_job(array['music_analyse'],'worker-b')).id is null,'active lease cannot be claimed again');
select throws_ok($$select public.complete_job('b0000000-0000-0000-0000-000000000001','worker-b',1::smallint)$$,'23514',null,'other worker cannot finish');
select throws_ok($$select public.complete_job('b0000000-0000-0000-0000-000000000001','worker-a',2::smallint)$$,'23514',null,'incorrect attempt fenced');
select ok(public.renew_job_lease('b0000000-0000-0000-0000-000000000001','worker-a',1::smallint) > clock_timestamp(),'lease renewal returns future wall-clock expiry');
select lives_ok($$select public.renew_job_lease('b0000000-0000-0000-0000-000000000001','worker-a',1::smallint)$$,'current worker renews lease');
select lives_ok($$select public.fail_job('b0000000-0000-0000-0000-000000000001','worker-a',1::smallint,'temporary')$$,'worker reports failure');
select is((select status from public.jobs where kind = 'music_analyse'),'failed','failure queued for retry');
select ok((select run_after >= now() + interval '30 seconds' from public.jobs where kind = 'music_analyse'),'first retry has backoff');
select ok((public.claim_job(array['music_analyse'],'worker-a')).id is null,'backoff prevents early claim');
update public.jobs set run_after = now() - interval '1 second' where kind = 'music_analyse';
select is((public.claim_job(array['music_analyse'],'worker-a')).attempts,2::smallint,'retry increments attempt');
select throws_ok($$select public.complete_job('b0000000-0000-0000-0000-000000000001','worker-a',1::smallint)$$,'23514',null,'same-name stale attempt cannot finish');
select lives_ok($$select public.fail_job('b0000000-0000-0000-0000-000000000001','worker-a',2::smallint,'again')$$,'second failure retried');
select ok((select run_after >= now() + interval '60 seconds' from public.jobs where kind = 'music_analyse'),'second retry doubles backoff');
update public.jobs set run_after = now() - interval '1 second' where kind = 'music_analyse';
select is((public.claim_job(array['music_analyse'],'worker-a')).attempts,3::smallint,'last allowed attempt claimed');
select lives_ok($$select public.fail_job('b0000000-0000-0000-0000-000000000001','worker-a',3::smallint,'terminal')$$,'last failure recorded');
select is((select status from public.jobs where kind = 'music_analyse'),'dead','attempt exhaustion terminal');
select ok((public.claim_job(array['music_analyse'],'worker-a')).id is null,'dead job never claimed');
select is((public.claim_job(array['video_analyse'],'worker-a')).attempts,1::smallint,'another kind remains claimable');
update public.jobs set lease_until = now() - interval '1 second' where kind = 'video_analyse';
select throws_ok($$select public.complete_job('b0000000-0000-0000-0000-000000000002','worker-a',1::smallint)$$,'23514',null,'expired worker cannot complete');
select is((public.claim_job(array['video_analyse'],'worker-b')).attempts,2::smallint,'expired lease reclaimed');
select lives_ok($$select public.complete_job('b0000000-0000-0000-0000-000000000002','worker-b',2::smallint,'{"ok":true}','{"usd":0}')$$,'current worker completes');
select is((select status from public.jobs where kind = 'video_analyse'),'done','success terminal');
select is((select result from public.jobs where kind = 'video_analyse'),'{"ok":true}'::jsonb,'result saved');
select throws_ok($$select public.claim_job(array['music_analyse'],'')$$,'23514',null,'blank worker refused');
insert into public.jobs(id,kind,payload,max_attempts) values ('b0000000-0000-0000-0000-000000000003','privacy_export','{}',1);
select is((public.claim_job(array['privacy_export'],'crashed')).attempts,1::smallint,'single-attempt job claimed');
update public.jobs set lease_until = now() - interval '1 second' where kind = 'privacy_export';
select ok((public.claim_job(array['privacy_export'],'replacement')).id is null,'exhausted crashed job not reclaimed');
select is((select status from public.jobs where kind = 'privacy_export'),'dead','expired final lease marked dead');
reset role;
select * from finish();
