-- Tenant integration visibility, setting rights and credential boundaries.
select no_plan();
select tests.create_platform_fixture();
reset role;
select tests.act_as('organisation_owner');
select is((select count(*) from public.integrations),1::bigint,'owner reads own integrations');
select is((select count(*) from public.integrations where organisation_id <> '10000000-0000-0000-0000-000000000001'),0::bigint,'foreign integrations hidden');
reset role;
select tests.act_as('organisation_manager');
select is((select count(*) from public.integrations),1::bigint,'manager reads own integrations');
reset role;
select tests.act_as('platform_staff');
select is((select count(*) from public.integrations),2::bigint,'staff reads integrations across tenants');
reset role;
select tests.act_as('signed_in_shopper');
select is((select count(*) from public.integrations),0::bigint,'signed_in_shopper cannot read integrations');
reset role;
select tests.act_as('anonymous_shopper');
select is((select count(*) from public.integrations),0::bigint,'anonymous_shopper cannot read integrations');
reset role;
select tests.act_as('supplier_member');
select is((select count(*) from public.integrations),0::bigint,'supplier_member cannot read integrations');
reset role;
select tests.act_as('other_organisation_member');
select is((select count(*) from public.integrations where organisation_id = '10000000-0000-0000-0000-000000000001'),0::bigint,'other member cannot read integrations');
reset role;
select tests.act_as('organisation_owner');
select is((select count(*) from public.sync_runs),1::bigint,'owner reads own sync_runs');
select is((select count(*) from public.sync_runs where organisation_id <> '10000000-0000-0000-0000-000000000001'),0::bigint,'foreign sync_runs hidden');
reset role;
select tests.act_as('organisation_manager');
select is((select count(*) from public.sync_runs),1::bigint,'manager reads own sync_runs');
reset role;
select tests.act_as('platform_staff');
select is((select count(*) from public.sync_runs),2::bigint,'staff reads sync_runs across tenants');
reset role;
select tests.act_as('signed_in_shopper');
select is((select count(*) from public.sync_runs),0::bigint,'signed_in_shopper cannot read sync_runs');
reset role;
select tests.act_as('anonymous_shopper');
select is((select count(*) from public.sync_runs),0::bigint,'anonymous_shopper cannot read sync_runs');
reset role;
select tests.act_as('supplier_member');
select is((select count(*) from public.sync_runs),0::bigint,'supplier_member cannot read sync_runs');
reset role;
select tests.act_as('other_organisation_member');
select is((select count(*) from public.sync_runs where organisation_id = '10000000-0000-0000-0000-000000000001'),0::bigint,'other member cannot read sync_runs');
reset role;
select tests.act_as('organisation_owner');
select is((select count(*) from public.webhook_endpoints),1::bigint,'owner reads own webhook_endpoints');
select is((select count(*) from public.webhook_endpoints where organisation_id <> '10000000-0000-0000-0000-000000000001'),0::bigint,'foreign webhook_endpoints hidden');
reset role;
select tests.act_as('organisation_manager');
select is((select count(*) from public.webhook_endpoints),1::bigint,'manager reads own webhook_endpoints');
reset role;
select tests.act_as('platform_staff');
select is((select count(*) from public.webhook_endpoints),2::bigint,'staff reads webhook_endpoints across tenants');
reset role;
select tests.act_as('signed_in_shopper');
select is((select count(*) from public.webhook_endpoints),0::bigint,'signed_in_shopper cannot read webhook_endpoints');
reset role;
select tests.act_as('anonymous_shopper');
select is((select count(*) from public.webhook_endpoints),0::bigint,'anonymous_shopper cannot read webhook_endpoints');
reset role;
select tests.act_as('supplier_member');
select is((select count(*) from public.webhook_endpoints),0::bigint,'supplier_member cannot read webhook_endpoints');
reset role;
select tests.act_as('other_organisation_member');
select is((select count(*) from public.webhook_endpoints where organisation_id = '10000000-0000-0000-0000-000000000001'),0::bigint,'other member cannot read webhook_endpoints');
reset role;
select tests.act_as('organisation_owner');
select is((select count(*) from public.api_keys),1::bigint,'owner reads own api_keys');
select is((select count(*) from public.api_keys where organisation_id <> '10000000-0000-0000-0000-000000000001'),0::bigint,'foreign api_keys hidden');
reset role;
select tests.act_as('organisation_manager');
select is((select count(*) from public.api_keys),1::bigint,'manager reads own api_keys');
reset role;
select tests.act_as('platform_staff');
select is((select count(*) from public.api_keys),2::bigint,'staff reads api_keys across tenants');
reset role;
select tests.act_as('signed_in_shopper');
select is((select count(*) from public.api_keys),0::bigint,'signed_in_shopper cannot read api_keys');
reset role;
select tests.act_as('anonymous_shopper');
select is((select count(*) from public.api_keys),0::bigint,'anonymous_shopper cannot read api_keys');
reset role;
select tests.act_as('supplier_member');
select is((select count(*) from public.api_keys),0::bigint,'supplier_member cannot read api_keys');
reset role;
select tests.act_as('other_organisation_member');
select is((select count(*) from public.api_keys where organisation_id = '10000000-0000-0000-0000-000000000001'),0::bigint,'other member cannot read api_keys');
reset role;
select tests.act_as('organisation_manager');
select throws_ok($$insert into public.integrations(organisation_id,provider,status) values('10000000-0000-0000-0000-000000000001','mailchimp','paused')$$,'42501',null,'manager cannot insert integrations');
with changed as (update public.integrations set status = 'paused' where organisation_id = '10000000-0000-0000-0000-000000000001' returning id) select is(count(*),0::bigint,'manager cannot update integrations') from changed;
reset role;
select tests.act_as('other_organisation_member');
select throws_ok($$insert into public.integrations(organisation_id,provider,status) values('10000000-0000-0000-0000-000000000001','mailchimp','paused')$$,'42501',null,'foreign owner cannot insert integrations');
with changed as (update public.integrations set status = 'paused' where organisation_id = '10000000-0000-0000-0000-000000000001' returning id) select is(count(*),0::bigint,'foreign owner cannot update integrations') from changed;
reset role;
select tests.act_as('organisation_owner');
select lives_ok($$insert into public.integrations(organisation_id,provider,status) values('10000000-0000-0000-0000-000000000001','mailchimp','paused')$$,'owner inserts integrations');
select lives_ok($$update public.integrations set status = 'paused' where organisation_id = '10000000-0000-0000-0000-000000000001'$$,'owner updates integrations');
reset role;
select tests.act_as('organisation_manager');
select throws_ok($$insert into public.webhook_endpoints(organisation_id,url,events) values('10000000-0000-0000-0000-000000000001','https://example.invalid/new',array['sync.done'])$$,'42501',null,'manager cannot insert webhook_endpoints');
with changed as (update public.webhook_endpoints set active = false where organisation_id = '10000000-0000-0000-0000-000000000001' returning id) select is(count(*),0::bigint,'manager cannot update webhook_endpoints') from changed;
reset role;
select tests.act_as('other_organisation_member');
select throws_ok($$insert into public.webhook_endpoints(organisation_id,url,events) values('10000000-0000-0000-0000-000000000001','https://example.invalid/new',array['sync.done'])$$,'42501',null,'foreign owner cannot insert webhook_endpoints');
with changed as (update public.webhook_endpoints set active = false where organisation_id = '10000000-0000-0000-0000-000000000001' returning id) select is(count(*),0::bigint,'foreign owner cannot update webhook_endpoints') from changed;
reset role;
select tests.act_as('organisation_owner');
select lives_ok($$insert into public.webhook_endpoints(organisation_id,url,events) values('10000000-0000-0000-0000-000000000001','https://example.invalid/new',array['sync.done'])$$,'owner inserts webhook_endpoints');
select lives_ok($$update public.webhook_endpoints set active = false where organisation_id = '10000000-0000-0000-0000-000000000001'$$,'owner updates webhook_endpoints');
reset role;
select tests.act_as('other_organisation_member');
with changed as (delete from public.webhook_endpoints where organisation_id = '10000000-0000-0000-0000-000000000001' returning id) select is(count(*),0::bigint,'foreign owner cannot delete endpoints') from changed;
reset role;
select tests.act_as('organisation_owner');
select lives_ok($$delete from public.webhook_endpoints where organisation_id = '10000000-0000-0000-0000-000000000001'$$,'owner deletes endpoints');
reset role;
select tests.act_as('organisation_owner');
select throws_ok($$select key_hash from public.api_keys$$,'42501',null,'key_hash excluded from client reads');
select throws_ok($$select secret_id from public.integrations$$,'42501',null,'secret_id excluded from client reads');
select throws_ok($$update public.api_keys set revoked_at = now()$$,'42501',null,'key writes backend only');
select throws_ok($$insert into public.sync_runs(organisation_id,integration_id) select organisation_id,id from public.integrations$$,'42501',null,'sync writes backend only');
reset role;
select throws_ok($$insert into public.sync_runs(organisation_id,integration_id) values('10000000-0000-0000-0000-000000000001','87000000-0000-0000-0000-000000000002')$$,'23503',null,'sync tenant must match integration');
select throws_ok($$insert into public.api_keys(organisation_id,prefix,key_hash,scopes) values('10000000-0000-0000-0000-000000000001','bad','plaintext',array['read'])$$,'23514',null,'plaintext key rejected');
select throws_ok($$insert into public.webhook_endpoints(organisation_id,url,events) values('10000000-0000-0000-0000-000000000001','http://example.invalid',array['read'])$$,'23514',null,'HTTPS endpoint required');
reset role;
update public.memberships set store_ids = '{}' where profile_id = tests.get_supabase_uid('organisation_owner');
select tests.act_as('organisation_owner');
select throws_ok($$insert into public.integrations(organisation_id,provider,status) values('10000000-0000-0000-0000-000000000001','restricted','paused')$$,'42501',null,'store-restricted owner cannot change organisation integrations');
with changed as (update public.integrations set status = 'error' returning id)
  select is(count(*),0::bigint,'store-restricted owner cannot update integrations') from changed;
reset role;
select tests.act_as_public();
select ok(not has_table_privilege(current_user,'public.integrations','SELECT'),'public has no integration access');
select ok(not has_table_privilege(current_user,'public.api_keys','SELECT'),'public has no key access');
select * from finish();
