-- Platform configuration policies, personal notices and deterministic tenant flags.
select no_plan();
select tests.create_platform_fixture();
reset role;
select tests.act_as('platform_staff');
select ok((select count(*) from public.feature_flags) > 0,'staff reads feature_flags');
select lives_ok($$insert into public.feature_flags(key,enabled) values('new',true)$$,'admin inserts feature_flags');
select lives_ok($$update public.feature_flags set enabled = false$$,'admin updates feature_flags');
select lives_ok($$delete from public.feature_flags where key = 'new'$$,'admin deletes feature_flags');
reset role;
select tests.act_as('organisation_owner');
select is((select count(*) from public.feature_flags),0::bigint,'retailer scoped feature_flags visibility');
select throws_ok($$insert into public.feature_flags(key,enabled) values('new',true)$$,'42501',null,'owner cannot insert feature_flags');
with changed as (update public.feature_flags set enabled = false returning 1) select is(count(*),0::bigint,'owner cannot update feature_flags') from changed;
with changed as (delete from public.feature_flags returning 1) select is(count(*),0::bigint,'owner cannot delete feature_flags') from changed;
reset role;
select tests.act_as('other_organisation_member');
select throws_ok($$insert into public.feature_flags(key,enabled) values('new',true)$$,'42501',null,'foreign owner cannot insert feature_flags');
with changed as (update public.feature_flags set enabled = false returning 1) select is(count(*),0::bigint,'foreign owner cannot update feature_flags') from changed;
with changed as (delete from public.feature_flags returning 1) select is(count(*),0::bigint,'foreign owner cannot delete feature_flags') from changed;
reset role;
select tests.act_as('platform_staff');
select ok((select count(*) from public.platform_settings) > 0,'staff reads platform_settings');
select lives_ok($$insert into public.platform_settings(key,value) values('new','{}')$$,'admin inserts platform_settings');
select lives_ok($$update public.platform_settings set value = '{"changed":true}'$$,'admin updates platform_settings');
select lives_ok($$delete from public.platform_settings where key = 'new'$$,'admin deletes platform_settings');
reset role;
select tests.act_as('organisation_owner');
select is((select count(*) from public.platform_settings),0::bigint,'retailer scoped platform_settings visibility');
select throws_ok($$insert into public.platform_settings(key,value) values('new','{}')$$,'42501',null,'owner cannot insert platform_settings');
with changed as (update public.platform_settings set value = '{"changed":true}' returning 1) select is(count(*),0::bigint,'owner cannot update platform_settings') from changed;
with changed as (delete from public.platform_settings returning 1) select is(count(*),0::bigint,'owner cannot delete platform_settings') from changed;
reset role;
select tests.act_as('other_organisation_member');
select throws_ok($$insert into public.platform_settings(key,value) values('new','{}')$$,'42501',null,'foreign owner cannot insert platform_settings');
with changed as (update public.platform_settings set value = '{"changed":true}' returning 1) select is(count(*),0::bigint,'foreign owner cannot update platform_settings') from changed;
with changed as (delete from public.platform_settings returning 1) select is(count(*),0::bigint,'foreign owner cannot delete platform_settings') from changed;
reset role;
select tests.act_as('platform_staff');
select ok((select count(*) from public.flag_overrides) > 0,'staff reads flag_overrides');
select lives_ok($$insert into public.flag_overrides(flag_key,organisation_id,enabled) values('disabled','10000000-0000-0000-0000-000000000001',true)$$,'admin inserts flag_overrides');
select lives_ok($$update public.flag_overrides set enabled = false$$,'admin updates flag_overrides');
select lives_ok($$delete from public.flag_overrides where flag_key = 'disabled'$$,'admin deletes flag_overrides');
reset role;
select tests.act_as('organisation_owner');
select is((select count(*) from public.flag_overrides),1::bigint,'retailer scoped flag_overrides visibility');
select throws_ok($$insert into public.flag_overrides(flag_key,organisation_id,enabled) values('disabled','10000000-0000-0000-0000-000000000001',true)$$,'42501',null,'owner cannot insert flag_overrides');
with changed as (update public.flag_overrides set enabled = false returning 1) select is(count(*),0::bigint,'owner cannot update flag_overrides') from changed;
with changed as (delete from public.flag_overrides returning 1) select is(count(*),0::bigint,'owner cannot delete flag_overrides') from changed;
reset role;
select tests.act_as('other_organisation_member');
select is((select count(*) from public.flag_overrides where organisation_id = '10000000-0000-0000-0000-000000000001'),0::bigint,'foreign override hidden');
select throws_ok($$insert into public.flag_overrides(flag_key,organisation_id,enabled) values('disabled','10000000-0000-0000-0000-000000000001',true)$$,'42501',null,'foreign owner cannot insert flag_overrides');
with changed as (update public.flag_overrides set enabled = false where organisation_id = '10000000-0000-0000-0000-000000000001' returning 1) select is(count(*),0::bigint,'foreign owner cannot update flag_overrides') from changed;
with changed as (delete from public.flag_overrides where organisation_id = '10000000-0000-0000-0000-000000000001' returning 1) select is(count(*),0::bigint,'foreign owner cannot delete flag_overrides') from changed;
reset role;
update public.feature_flags set enabled = true, rollout_pct = 100;
delete from public.flag_overrides;
reset role;
select tests.act_as('organisation_owner');
select ok(public.flag_on('fixture','10000000-0000-0000-0000-000000000001'),'full rollout on');
select ok(not public.flag_on('missing','10000000-0000-0000-0000-000000000001'),'unknown flag off');
select throws_ok($$select public.flag_on('fixture','10000000-0000-0000-0000-000000000002')$$,'42501',null,'foreign flag evaluation denied');
reset role;
update public.feature_flags set rollout_pct = 0;
reset role;
select tests.act_as('organisation_owner');
select ok(not public.flag_on('fixture','10000000-0000-0000-0000-000000000001'),'zero rollout off');
reset role;
update public.feature_flags set rollout_pct = 100, markets = array['AU'];
reset role;
select tests.act_as('organisation_owner');
select ok(not public.flag_on('fixture','10000000-0000-0000-0000-000000000001'),'home market mismatch off');
reset role;
select tests.act_as('other_organisation_member');
select ok(public.flag_on('fixture','10000000-0000-0000-0000-000000000002'),'matching home market on');
reset role;
insert into public.flag_overrides(flag_key,organisation_id,enabled) values ('fixture','10000000-0000-0000-0000-000000000001',true);
reset role;
select tests.act_as('organisation_owner');
select ok(public.flag_on('fixture','10000000-0000-0000-0000-000000000001'),'override wins over market gate');
reset role;
update public.flag_overrides set enabled = false;
reset role;
select tests.act_as('organisation_owner');
select ok(not public.flag_on('fixture','10000000-0000-0000-0000-000000000001'),'false override wins');
reset role;
delete from public.flag_overrides;
update public.feature_flags set markets = null, rollout_pct = 37;
reset role;
select tests.act_as('organisation_owner');
select is(public.flag_on('fixture','10000000-0000-0000-0000-000000000001'),abs(hashtext('10000000-0000-0000-0000-000000000001'::text || 'fixture')::bigint) % 100 < 37,'rollout matches specified hash algorithm');
reset role;
select throws_ok($$update public.feature_flags set rollout_pct = 101$$,'23514',null,'percentage bounds enforced');
reset role;
select tests.act_as('organisation_owner');
select is((select count(*) from public.notifications),1::bigint,'caller reads own notice');
select lives_ok($$update public.notifications set read_at = now()$$,'caller marks notice read');
with changed as (update public.notifications set read_at = now() where profile_id <> tests.get_supabase_uid('organisation_owner') returning id) select is(count(*),0::bigint,'foreign notice update hidden') from changed;
reset role;
select tests.act_as('organisation_manager');
select is((select count(*) from public.notifications),1::bigint,'caller reads own notice');
select lives_ok($$update public.notifications set read_at = now()$$,'caller marks notice read');
with changed as (update public.notifications set read_at = now() where profile_id <> tests.get_supabase_uid('organisation_manager') returning id) select is(count(*),0::bigint,'foreign notice update hidden') from changed;
reset role;
select tests.act_as('other_organisation_member');
select is((select count(*) from public.notifications),1::bigint,'caller reads own notice');
select lives_ok($$update public.notifications set read_at = now()$$,'caller marks notice read');
with changed as (update public.notifications set read_at = now() where profile_id <> tests.get_supabase_uid('other_organisation_member') returning id) select is(count(*),0::bigint,'foreign notice update hidden') from changed;
reset role;
select tests.act_as('signed_in_shopper');
select is((select count(*) from public.notifications),0::bigint,'unrelated notices hidden');
with changed as (update public.notifications set read_at = now() returning id) select is(count(*),0::bigint,'unrelated notice updates hidden') from changed;
reset role;
select tests.act_as('anonymous_shopper');
select is((select count(*) from public.notifications),0::bigint,'unrelated notices hidden');
with changed as (update public.notifications set read_at = now() returning id) select is(count(*),0::bigint,'unrelated notice updates hidden') from changed;
reset role;
select tests.act_as('supplier_member');
select is((select count(*) from public.notifications),0::bigint,'unrelated notices hidden');
with changed as (update public.notifications set read_at = now() returning id) select is(count(*),0::bigint,'unrelated notice updates hidden') from changed;
reset role;
select tests.act_as('platform_staff');
select is((select count(*) from public.notifications),0::bigint,'unrelated notices hidden');
with changed as (update public.notifications set read_at = now() returning id) select is(count(*),0::bigint,'unrelated notice updates hidden') from changed;
reset role;
select tests.act_as('organisation_owner');
select throws_ok($$update public.notifications set title = 'forged'$$,'42501',null,'notice content backend only');
reset role;
select tests.act_as('organisation_owner');
select is((select count(*) from public.notification_preferences),1::bigint,'own preferences readable');
select lives_ok($$insert into public.notification_preferences(profile_id,organisation_id,kind,channel,enabled) values(tests.get_supabase_uid('organisation_owner'),'10000000-0000-0000-0000-000000000001','new','email',true)$$,'owner inserts preference');
select lives_ok($$update public.notification_preferences set enabled = false$$,'owner updates preference');
reset role;
select tests.act_as('other_organisation_member');
select is((select count(*) from public.notification_preferences where organisation_id = '10000000-0000-0000-0000-000000000001'),0::bigint,'foreign preferences hidden');
select throws_ok($$insert into public.notification_preferences(profile_id,organisation_id,kind,channel,enabled) values(tests.get_supabase_uid('other_organisation_member'),'10000000-0000-0000-0000-000000000001','new','email',true)$$,'42501',null,'foreign tenant preference insert denied');
with changed as (update public.notification_preferences set enabled = true where organisation_id = '10000000-0000-0000-0000-000000000001' returning 1) select is(count(*),0::bigint,'foreign preference update denied') from changed;
with changed as (delete from public.notification_preferences where organisation_id = '10000000-0000-0000-0000-000000000001' returning 1) select is(count(*),0::bigint,'foreign preference delete denied') from changed;
reset role;
select tests.act_as('organisation_owner');
select lives_ok($$delete from public.notification_preferences where kind = 'new'$$,'own preference deleted');
reset role;
update public.feature_flags set enabled = false, rollout_pct = 100;
select tests.act_as('organisation_owner');
select ok(not public.flag_on('fixture','10000000-0000-0000-0000-000000000001'),'disabled flag stays off despite full rollout');
select throws_ok($$insert into public.notification_preferences(profile_id,organisation_id,kind,channel,enabled) values(tests.get_supabase_uid('organisation_manager'),'10000000-0000-0000-0000-000000000001','forged','email',true)$$,'42501',null,'cannot insert preferences for a colleague');
reset role;
insert into public.notifications(profile_id,kind,title) values
  (tests.get_supabase_uid('anonymous_shopper'),'fixture','Synthetic notice'),
  (tests.get_supabase_uid('signed_in_shopper'),'fixture','Synthetic notice');
select tests.act_as('anonymous_shopper');
select is((select count(*) from public.notifications),1::bigint,'anonymous account reads its own notice');
select lives_ok($$update public.notifications set read_at = now()$$,'anonymous account marks own notice read');
reset role;
select tests.act_as('signed_in_shopper');
select is((select count(*) from public.notifications),1::bigint,'signed-in shopper reads its own notice');
select lives_ok($$update public.notifications set read_at = now()$$,'signed-in shopper marks own notice read');
reset role;
update public.staff_roles set role = 'support';
select tests.act_as('platform_staff');
select is((select count(*) from public.platform_settings),1::bigint,'support may inspect settings');
select throws_ok($$insert into public.platform_settings(key,value) values('forged','{}')$$,'42501',null,'support cannot insert settings');
with changed as (update public.feature_flags set enabled = true returning key)
  select is(count(*),0::bigint,'support cannot update flags') from changed;
with changed as (delete from public.platform_settings returning key)
  select is(count(*),0::bigint,'support cannot delete settings') from changed;
reset role;
select tests.act_as_public();
select ok(not has_function_privilege(current_user,'private.flag_on(text,uuid)','EXECUTE'),'public flag helper unavailable by ACL');
select ok(not has_table_privilege(current_user,'public.platform_settings','SELECT'),'public cannot read settings');
select * from finish();
