-- Transactional audit attribution, redaction and independently approved support records.
select no_plan();
select tests.create_platform_fixture();
select tests.act_as('platform_staff');
select ok((select count(*) from public.audit_log) > 0,'staff reads audit history');
select is((select count(*) from public.support_sessions),1::bigint,'admin reads support records');
select lives_ok($$update public.platform_settings set value = '{"changed":true}', updated_by = tests.get_supabase_uid('organisation_owner') where key = 'fixture'$$,'admin edits settings');
select is((select updated_by from public.platform_settings where key = 'fixture'),tests.get_supabase_uid('platform_staff'),'editor derived from actual request');
select ok(exists(select from public.audit_log where table_name = 'platform_settings' and action = 'update' and actor_id = tests.get_supabase_uid('platform_staff')),'setting audit records actual actor');
select lives_ok($$select public.start_support_session(tests.get_supabase_uid('platform_staff'),'10000000-0000-0000-0000-000000000001',tests.get_supabase_uid('organisation_owner'),'view','Investigate fixture',null,now()+interval '1 hour')$$,'staff opens view session');
select throws_ok($$select public.start_support_session(tests.get_supabase_uid('platform_staff'),'10000000-0000-0000-0000-000000000001',null,'edit','Self approval',null,now()+interval '1 hour')$$,'42501',null,'admin cannot approve own edit session');
select throws_ok($$select public.start_support_session(tests.get_supabase_uid('platform_staff'),'10000000-0000-0000-0000-000000000001',tests.get_supabase_uid('other_organisation_member'),'view','Foreign target',null,now()+interval '1 hour')$$,'23514',null,'support target must belong to tenant');
select throws_ok($$select public.start_support_session(tests.get_supabase_uid('platform_staff'),'10000000-0000-0000-0000-000000000001',null,'view','Expired',null,now()-interval '1 second')$$,'23514',null,'session expiry must follow start');
reset role;
insert into public.staff_roles(profile_id,role) values(tests.get_supabase_uid('supplier_member'),'support');
select tests.act_as('platform_staff');
select lives_ok($$select public.start_support_session(tests.get_supabase_uid('supplier_member'),'10000000-0000-0000-0000-000000000001',null,'edit','Approved correction','SYNTHETIC',now()+interval '1 hour')$$,'admin approves another support user');
select is((select approved_by from public.support_sessions where mode = 'edit'),tests.get_supabase_uid('platform_staff'),'approval recorded from caller');
reset role;
select tests.act_as('supplier_member');
select is((select count(*) from public.support_sessions),1::bigint,'support reads only own session');
select throws_ok($$select public.start_support_session(tests.get_supabase_uid('supplier_member'),'10000000-0000-0000-0000-000000000001',null,'edit','Forged approval',null,now()+interval '1 hour')$$,'42501',null,'support cannot approve edits');
select lives_ok($$select public.end_support_session((select id from public.support_sessions where mode = 'edit'))$$,'support ends own session');
select lives_ok($$select public.end_support_session((select id from public.support_sessions where mode = 'edit'))$$,'session end is idempotent');
select ok((select ended_at is not null from public.support_sessions where mode = 'edit'),'session end recorded');
select throws_ok($$update public.support_sessions set approved_by = tests.get_supabase_uid('supplier_member')$$,'42501',null,'clients cannot rewrite approval');
select throws_ok($$insert into public.audit_log(action) values('forged')$$,'42501',null,'clients cannot insert audit rows');
select throws_ok($$update public.audit_log set action = 'forged'$$,'42501',null,'clients cannot update audit rows');
select throws_ok($$delete from public.audit_log$$,'42501',null,'clients cannot delete audit rows');
select ok(not has_function_privilege(current_user,'private.audit_record()','EXECUTE'),'audit trigger execute not exposed');
reset role;
select tests.act_as('organisation_owner');
select ok((select count(*) from public.audit_log) > 0,'owner reads own audit rows');
select is((select count(*) from public.audit_log where organisation_id = '10000000-0000-0000-0000-000000000002'),0::bigint,'foreign audit rows hidden');
select is((select count(*) from public.support_sessions),0::bigint,'retailer cannot read support sessions');
select throws_ok($$select public.start_support_session(tests.get_supabase_uid('organisation_owner'),'10000000-0000-0000-0000-000000000001',null,'view','Retailer',null,now()+interval '1 hour')$$,'42501',null,'retailer cannot open support session');
select lives_ok($$update public.integrations set config = '{"store":"synthetic"}' where provider = 'square'$$,'owner updates non-secret config');
select ok(exists(select from public.audit_log where table_name = 'integrations' and action = 'update' and diff->'changed_fields' ? 'config'),'redacted config change remains audited');
select ok(not exists(select from public.audit_log where diff->'after' ? 'config' or diff->'after' ? 'secret_id' or diff->'after' ? 'key_hash'),'audit omits credentials and configuration payload');
reset role;
select tests.act_as('other_organisation_member');
select is((select count(*) from public.audit_log where organisation_id = '10000000-0000-0000-0000-000000000001'),0::bigint,'other tenant cannot read owner audit');
reset role;
select tests.act_as('organisation_manager');
select is((select count(*) from public.audit_log),0::bigint,'manager cannot read audit');
select is((select count(*) from public.support_sessions),0::bigint,'manager cannot read support records');
reset role;
select tests.act_as('anonymous_shopper');
select is((select count(*) from public.audit_log),0::bigint,'anonymous shopper cannot read audit');
reset role;
select tests.act_as('signed_in_shopper');
select is((select count(*) from public.audit_log),0::bigint,'shopper cannot read audit');
reset role;
set local role service_role;
select ok(not has_table_privilege(current_user,'public.audit_log','UPDATE'),'backend cannot update audit history');
select ok(not has_table_privilege(current_user,'public.audit_log','DELETE'),'backend cannot delete audit history');
reset role;
-- A caught subtransaction rolls back both the change and its audit record.
do $$
#variable_conflict error
begin
  update public.platform_settings set value = '{"rollback":true}';
  raise exception 'rollback fixture';
exception when raise_exception then null;
end;
$$;
select ok(not exists(select from public.audit_log where diff->'after'->'value' = '{"rollback":true}'::jsonb),'audit rollback follows source rollback');
select ok(not exists(select from public.audit_log where acting_as_support_session is not null),'untrusted session claims are never attributed');
select * from finish();
