-- Configuration audit coverage uses the actual catalogue and retailer write paths.
select no_plan();
select tests.create_operations_fixture();
select ok(exists(select from public.audit_log where table_name = 'memberships' and action = 'insert'),'membership creation audited');
select ok(exists(select from public.audit_log where table_name = 'plans' and action = 'insert'),'plan creation audited');
select ok(exists(select from public.audit_log where table_name = 'effect_versions' and action = 'insert'),'effect draft creation audited');
select ok(exists(select from public.audit_log where table_name = 'product_versions' and action = 'insert'),'product draft creation audited');
select ok(exists(select from public.audit_log where table_name = 'show_versions' and action = 'insert' and organisation_id = '10000000-0000-0000-0000-000000000001'),'show version tenant retained');
select ok(exists(select from public.audit_log where table_name = 'qr_codes' and action = 'insert'),'QR target creation audited');
select tests.act_as('organisation_owner');
select lives_ok($$update public.range_items set price_minor = 2600 where id = '91000000-0000-0000-0000-000000000001'$$,'owner changes range price');
select ok(exists(select from public.audit_log where table_name = 'range_items' and action = 'update' and actor_id = tests.get_supabase_uid('organisation_owner') and diff->'after'->>'price_minor' = '2600' and diff->'before'->>'price_minor' = '2500'),'range price audit records before and after');
select lives_ok($$update public.store_items set price_override_minor = 2700 where store_id = '90000000-0000-0000-0000-000000000001'$$,'owner changes store price');
select ok(exists(select from public.audit_log where table_name = 'store_items' and action = 'update' and row_id = '90000000-0000-0000-0000-000000000001/91000000-0000-0000-0000-000000000001'),'store price has compound audit identity');
select lives_ok($$update public.qr_codes set label_text = 'Fixture label' where slug = 'fixture-1'$$,'owner changes QR configuration');
select ok(exists(select from public.audit_log where table_name = 'qr_codes' and action = 'update' and actor_id = tests.get_supabase_uid('organisation_owner')),'QR update audited');
select throws_ok($$update public.range_items set price_minor = -1 where id = '91000000-0000-0000-0000-000000000001'$$,'23514',null,'invalid price fails');
select ok(not exists(select from public.audit_log where table_name = 'range_items' and diff->'after'->>'price_minor' = '-1'),'failed price change has no audit record');
select lives_ok($$update public.range_items set price_minor = 2600 where id = '91000000-0000-0000-0000-000000000001'$$,'no-op price write permitted');
select is((select count(*) from public.audit_log where table_name = 'range_items' and action = 'update'),1::bigint,'no-op write adds no audit event');
reset role;
select tests.act_as('platform_staff');
select lives_ok($$delete from public.memberships where profile_id = tests.get_supabase_uid('organisation_manager')$$,'admin removes membership');
select ok(exists(select from public.audit_log where table_name = 'memberships' and action = 'delete' and diff->'after' = 'null'::jsonb and diff->'before'->>'profile_id' = tests.get_supabase_uid('organisation_manager')::text),'deletion retains previous membership');
reset role;
select throws_ok($$update public.effect_versions set design = '{}' where status = 'published'$$,'23514',null,'history validation still rejects invalid published update');
reset role;
select ok(not exists(select from public.audit_log where diff->'after' ? 'design' or diff->'after' ? 'composition' or diff->'after' ? 'cues'),'large authored payloads omitted from audit');
select is((select count(*) from public.audit_log where table_name = 'events'),0::bigint,'raw analytics events are not audited');
select * from finish();
