begin;
create extension if not exists pgtap with schema extensions;
set local search_path = public, extensions;
select plan(18);
insert into auth.users(id,email) values ('94000000-0000-4000-8000-000000000001','design-admin@example.test'), ('94000000-0000-4000-8000-000000000002','design-member@example.test');
insert into public.user_roles(user_id,role_id) select '94000000-0000-4000-8000-000000000001',id from public.roles where key='admin' on conflict(user_id) do update set role_id=excluded.role_id;
create temporary table design_fixture(doc jsonb);
insert into design_fixture values ('{"kind":"shell","launch":{"height_m":56,"time_s":1.7389652095427326,"tilt_deg":0,"tail":"gold","sparks":180,"spread":1.4,"smoke":1},"breaks":[{"at_s":0,"core":{"enabled":true,"colour":"#ff3b2f","count":110,"radius":0.5,"flash":1,"flash_on":true,"ring":false},"fade":{"white_hot":0.03,"ember_at":0.8,"fade_at":0.72,"prime_s":0.25},"layers":[{"id":"l1","name":"Red and green petals","pattern":"sphere","count":90,"radius_m":26,"tilt":0.4,"speed_var":0.22,"drag_per_s":2.6,"gravity_m_s2":9,"life_s":2.2,"life_var":0.2,"delay_s":0,"offset_m":[0,0,0],"flash":true,"hidden":false,"colour":{"mode":"alternate","stops":[[0,["#ff3048","#2fe06a"]],[1,["#ff3048","#2fe06a"]]]},"brightness":[[0,1.5],[1,1.5]],"head":{"size":1.1,"visible":true},"trail":{"sparks":10,"length_s":0.25,"spread_m_s":0.4,"gravity_m_s2":3,"drag_per_s":2.6,"size":1,"flicker":0.3,"colour":"star","glitter":0,"glitter_delay_s":0.35,"fork":0},"modifiers":[]}]}],"ground":null,"sound":{"lift":0.7,"break":0.85,"crackle":0.6,"whistle":0},"seed":11}'::jsonb);
select ok(not has_function_privilege('anon','public.create_firework_from_template(text,text,jsonb,jsonb,jsonb,numeric)','execute'), 'Anonymous callers cannot create templates');
select set_config('request.jwt.claim.sub','94000000-0000-4000-8000-000000000002',true);
select throws_ok($$select public.create_firework_from_template('test-editor-template','Test', (select doc from design_fixture),'{}','{}',5)$$, '42501', 'Not permitted.', 'Members cannot create templates');
select set_config('request.jwt.claim.sub','94000000-0000-4000-8000-000000000001',true);
create temporary table created_firework as select public.create_firework_from_template('test-editor-template','Test template',doc,'{}','{"geometry":"sphere","stars":{"outer":{"head":{}}},"launch":{"shell":{}}}',5) as id from design_fixture;
select is((select count(*)::integer from public.firework_effects where template_key='test-editor-template'),1,'Creates one reusable effect');
select is((select f.design from public.fireworks f join created_firework c using(id)),(select doc from design_fixture),'Firework receives a full design copy');
select ok((select is_listed and finale_product_id is null from public.catalogue_items where firework_id=(select id from created_firework)), 'Catalogue item is listed without a Finale product');
select is((select render_snapshot_json from public.fireworks where id=(select id from created_firework)), '{"geometry":"sphere","stars":{"outer":{"head":{}}},"launch":{"shell":{}}}'::jsonb, 'Existing render-snapshot trigger captures the complete legacy appearance');
select public.create_firework_from_template('test-editor-template','Second copy',doc,'{}','{"geometry":"sphere","stars":{"outer":{"head":{}}},"launch":{"shell":{}}}',5) from design_fixture;
select is((select count(*)::integer from public.firework_effects where template_key='test-editor-template'),1,'Reuses the template effect');
create temporary table saved_design as select public.save_firework_editor('firework', f.id,f.updated_at,jsonb_build_object('design',jsonb_set(f.design,'{seed}','123')), '94000000-0000-4000-8000-000000000011') response from public.fireworks f join created_firework c using(id);
select ok((select (response->>'ok')::boolean from saved_design),'Design-only save succeeds');
select is((select snapshot_json->'design' from public.firework_editor_versions where id='94000000-0000-4000-8000-000000000011'), jsonb_set((select doc from design_fixture),'{seed}','123'),'Saved version contains design');
select is((select previous_snapshot_json->'design' from public.firework_editor_versions where id='94000000-0000-4000-8000-000000000011'),(select doc from design_fixture),'Previous version contains the exact baseline');
select is((select render_snapshot_json from public.fireworks where id=(select id from created_firework)), '{"geometry":"sphere","stars":{"outer":{"head":{}}},"launch":{"shell":{}}}'::jsonb,'Design save retains legacy render snapshot');
select public.save_firework_editor('firework',f.id,f.updated_at,jsonb_build_object('design',(select snapshot_json->'design' from public.firework_editor_versions where id='94000000-0000-4000-8000-000000000011')),'94000000-0000-4000-8000-000000000012','restore','94000000-0000-4000-8000-000000000011') from public.fireworks f join created_firework c using(id);
select is((select design from public.fireworks where id=(select id from created_firework)), jsonb_set((select doc from design_fixture),'{seed}','123'),'Restore can reinstate a design');
select throws_ok($$select public.save_firework_editor('firework',id,updated_at,'{"design":{}}',gen_random_uuid()) from public.fireworks where id=(select id from created_firework)$$,'23514',null,'Invalid design fails database validation');
select is((select count(*)::integer from public.firework_editor_versions where firework_id=(select id from created_firework)),2,'Failed design save leaves no history');
create temporary table effect_save as select public.save_firework_editor('effect',id,updated_at,jsonb_build_object('design',jsonb_set(design,'{seed}','456')),'94000000-0000-4000-8000-000000000013') response from public.firework_effects where template_key='test-editor-template';
select ok((select (response->>'ok')::boolean from effect_save),'Effect design saves atomically');
select is((select snapshot_json->'design'->>'seed' from public.firework_editor_versions where id='94000000-0000-4000-8000-000000000013'),'456','Effect history includes its design');
select is((select design->>'seed' from public.fireworks where id=(select id from created_firework)),'123','Effect changes do not propagate to a firework copy');
select throws_ok($$select public.create_firework_from_template('invalid-editor-template','Invalid', '{}','{}','{"geometry":"sphere","stars":{"outer":{"head":{}}},"launch":{"shell":{}}}',5)$$,'23514',null,'Invalid template creation rolls back all writes');
select * from finish();
rollback;
