/** Controlled product tiles with caller-owned 3D poster URLs and loading/error states. */
'use client';
import { Check } from 'lucide-react';
import { Skeleton } from './feedback';

/** Studio-ready product metadata; posters are rendered once outside the picker. */
export interface ProductChoice {
  id: string;
  name: string;
  metadata: string;
  price: string;
  poster?: string;
  posterError?: string;
  disabled?: boolean;
}
/** Selects products by stable id without owning catalogue data, currency or WebGL contexts. */
export function ProductPicker({
  label,
  items,
  selected,
  onChange,
}: {
  label: string;
  items: readonly ProductChoice[];
  selected: readonly string[];
  onChange: (ids: string[]) => void;
}) {
  return (
    <div
      role="group"
      aria-label={label}
      className="grid grid-cols-[repeat(auto-fill,minmax(min(var(--product-tile-min-width),100%),1fr))] gap-(--card-gap)"
    >
      {items.map((item) => (
        <button
          key={item.id}
          type="button"
          disabled={item.disabled}
          aria-pressed={selected.includes(item.id)}
          className="border-border bg-card aria-pressed:border-highlight aria-pressed:ring-highlight relative min-w-0 overflow-hidden rounded-lg border text-left disabled:opacity-50 aria-pressed:ring-1"
          onClick={() => {
            onChange(
              selected.includes(item.id)
                ? selected.filter((id) => id !== item.id)
                : [...selected, item.id],
            );
          }}
        >
          <PosterImage url={item.poster} error={item.posterError} />
          <span className="border-stage-foreground/70 bg-stage/60 text-stage-foreground absolute top-2 right-2 rounded border p-0.5">
            {selected.includes(item.id) ? (
              <Check className="size-3" />
            ) : (
              <span className="block size-3" />
            )}
          </span>
          <span className="grid gap-0.5 px-2.5 pt-2 pb-2.5">
            <b className="truncate text-sm font-semibold">{item.name}</b>
            <span className="text-muted-foreground flex flex-wrap justify-between gap-1 text-xs">
              <span>{item.metadata}</span>
              <span className="tabular-nums">{item.price}</span>
            </span>
          </span>
        </button>
      ))}
    </div>
  );
}
/** Displays a browser-generated poster with explicit preparation and failure states. */
export function PosterImage({ url, error }: { url?: string; error?: string }) {
  if (error !== undefined) {
    return (
      <span
        className="bg-stage text-stage-foreground flex aspect-[4/3] items-center justify-center p-3 text-xs"
        role="status"
      >
        {error}
      </span>
    );
  }
  if (url === undefined) {
    return (
      <span className="bg-stage block aspect-[4/3] p-3">
        <Skeleton className="bg-stage-foreground/10 h-full" />
        <span className="sr-only">Preparing 3D poster</span>
      </span>
    );
  }
  // Blob URLs are generated by the shared browser poster API and cannot use image optimisation.
  // eslint-disable-next-line @next/next/no-img-element -- Browser-generated blobs need a native image element.
  return <img src={url} alt="" className="bg-stage aspect-[4/3] w-full object-cover" />;
}
