/** Shared browser setup for synthetic identities in the local Supabase seeds. */
import { expect, type Page } from '@playwright/test';

// This password belongs only to the synthetic accounts generated by the local seed script.
const SEED_PASSWORD = 'LocalShowcrafter123!';

/** Signs in through the password form and waits for the verified workspace to hydrate. */
export async function signInAs(page: Page, persona: string): Promise<void> {
  await page.goto('/auth/sign-in');
  await page.getByLabel('Email', { exact: true }).fill(`${persona}@showcrafter.test`);
  await page.getByLabel('Password', { exact: true }).fill(SEED_PASSWORD);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page).not.toHaveURL(/auth\/sign-in/);
  await expect(page.locator('.sc-shell')).toHaveAttribute('data-hydrated', 'true');
}
