/** Shared browser setup for synthetic identities in the local Supabase seeds. */
import { readFileSync } from 'node:fs';
import { expect, type Page } from '@playwright/test';

// This password belongs only to the synthetic accounts generated by the local seed script.
const SEED_PASSWORD = 'LocalShowcrafter123!';

/** Signs in through the password form and waits for the verified workspace to hydrate. */
export async function signInAs(page: Page, persona: string): Promise<void> {
  await page.goto('/auth/sign-in');
  await page.getByLabel('Email', { exact: true }).fill(`${persona}@showcrafter.test`);
  await page.getByLabel('Password', { exact: true }).fill(SEED_PASSWORD);
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await expect(page).not.toHaveURL(/auth\/sign-in/);
  await expect(page.locator('.sc-shell')).toHaveAttribute('data-hydrated', 'true');
}

// Only the seeded local Auth and mail-catcher services are used by these helpers.
const API = 'http://127.0.0.1:55421';
const MAIL = 'http://127.0.0.1:55424';
function apiKey(): string {
  const env = readFileSync('apps/web/.env.local', 'utf8');
  const url = env.match(/^NEXT_PUBLIC_SUPABASE_URL=(.*)$/m)?.[1]?.replaceAll('"', '');
  if (url !== API) throw new Error('Auth journeys require the local Supabase environment');
  const key = env
    .match(/^NEXT_PUBLIC_SUPABASE_(?:ANON_KEY|PUBLISHABLE_KEY|PUBLISHABLE_DEFAULT_KEY)=(.*)$/m)?.[1]
    ?.replaceAll('"', '');
  if (!key) throw new Error('Local publishable key is missing');
  return key;
}
async function accessToken(page: Page): Promise<string> {
  const cookies = await page.context().cookies();
  const pieces = cookies
    .filter((cookie) => /sb-.*-auth-token(?:\.\d+)?$/.test(cookie.name))
    .sort((left, right) => left.name.localeCompare(right.name));
  const encoded = pieces.map((cookie) => cookie.value).join('');
  if (!encoded.startsWith('base64-')) throw new Error('Expected Supabase SSR session cookies');
  const session: unknown = JSON.parse(
    Buffer.from(encoded.slice('base64-'.length), 'base64url').toString(),
  );
  if (
    typeof session !== 'object' ||
    session === null ||
    !('access_token' in session) ||
    typeof session.access_token !== 'string'
  )
    throw new Error('Invalid Auth session');
  return session.access_token;
}
/** Returns the verified local Auth UUID from the current SSR session. */
export async function userId(page: Page): Promise<string> {
  const response = await page.request.get(`${API}/auth/v1/user`, {
    headers: { apikey: apiKey(), Authorization: `Bearer ${await accessToken(page)}` },
  });
  expect(response.ok()).toBe(true);
  const user: unknown = await response.json();
  if (typeof user !== 'object' || user === null || !('id' in user) || typeof user.id !== 'string')
    throw new Error('Invalid Auth user');
  return user.id;
}
/** Reads one string field from untrusted mail-catcher JSON. */
function stringField(value: unknown, key: string): string {
  if (typeof value !== 'object' || value === null || !(key in value)) return '';
  const field: unknown = (value as Record<string, unknown>)[key];
  return typeof field === 'string' ? field : '';
}
/** Waits for Mailpit's newest email to an address sent after the given time; returns its Auth link. */
export async function magicLink(page: Page, address: string, sentAfter: Date): Promise<string> {
  let link = '';
  await expect
    .poll(async () => {
      const query = encodeURIComponent(`to:"${address}"`);
      const response = await page.request.get(`${MAIL}/api/v1/search?query=${query}`);
      if (!response.ok()) return false;
      const result: unknown = await response.json();
      const messages: unknown =
        typeof result === 'object' && result !== null && 'messages' in result
          ? result.messages
          : [];
      if (!Array.isArray(messages)) return false;
      // Mailpit lists newest first; earlier runs may have left used links for the same address.
      const latest: unknown = messages.find(
        (message: unknown) => new Date(stringField(message, 'Created')) >= sentAfter,
      );
      const id = stringField(latest, 'ID');
      if (id === '') return false;
      const detail = await page.request.get(`${MAIL}/api/v1/message/${id}`);
      const body = stringField(await detail.json(), 'HTML');
      const match = body.match(/https?:[^\s"<>]+\/auth\/v1\/verify\?[^\s"<>]+/);
      link = match?.[0]?.replaceAll('&amp;', '&') ?? '';
      return link.length > 0;
    })
    .toBe(true);
  const url = new URL(link);
  if (!['localhost', '127.0.0.1'].includes(url.hostname))
    throw new Error('Refusing a non-local Auth link');
  return link;
}
