// Generated by Supabase MCP `generate_typescript_types`.
// To regenerate: `mcp call project-0-platform-supabase.generate_typescript_types`
// Do not edit by hand.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: "14.4"
  }
  public: {
    Tables: {
      "Finale3D CSV Import Sample": {
        Row: {
          available: string | null
          category: string | null
          ceNumber: string | null
          color: string | null
          customPartField: string | null
          description: string | null
          dmxFixtureDefinition: string | null
          dmxPatch: string | null
          duration: number | null
          ematches: string | null
          exNumber: string | null
          fuseDelay: string | null
          height: number | null
          internalDelay: number | null
          lockoutDefault: string | null
          manufacturer: string | null
          manufacturerPartNumber: string | null
          neq: string | null
          numDevices: number | null
          numTubes: string | null
          partNotes: string | null
          partNumber: string
          partType: string | null
          physicalSpecifications: string | null
          qoh: string | null
          rackType: string | null
          safetyDistance: string | null
          size: string | null
          stdCost: string | null
          stdLocation: string | null
          stdPrice: string | null
          subtype: string | null
          unNumber: string | null
          vdl: string | null
          weight: string | null
        }
        Insert: {
          available?: string | null
          category?: string | null
          ceNumber?: string | null
          color?: string | null
          customPartField?: string | null
          description?: string | null
          dmxFixtureDefinition?: string | null
          dmxPatch?: string | null
          duration?: number | null
          ematches?: string | null
          exNumber?: string | null
          fuseDelay?: string | null
          height?: number | null
          internalDelay?: number | null
          lockoutDefault?: string | null
          manufacturer?: string | null
          manufacturerPartNumber?: string | null
          neq?: string | null
          numDevices?: number | null
          numTubes?: string | null
          partNotes?: string | null
          partNumber: string
          partType?: string | null
          physicalSpecifications?: string | null
          qoh?: string | null
          rackType?: string | null
          safetyDistance?: string | null
          size?: string | null
          stdCost?: string | null
          stdLocation?: string | null
          stdPrice?: string | null
          subtype?: string | null
          unNumber?: string | null
          vdl?: string | null
          weight?: string | null
        }
        Update: {
          available?: string | null
          category?: string | null
          ceNumber?: string | null
          color?: string | null
          customPartField?: string | null
          description?: string | null
          dmxFixtureDefinition?: string | null
          dmxPatch?: string | null
          duration?: number | null
          ematches?: string | null
          exNumber?: string | null
          fuseDelay?: string | null
          height?: number | null
          internalDelay?: number | null
          lockoutDefault?: string | null
          manufacturer?: string | null
          manufacturerPartNumber?: string | null
          neq?: string | null
          numDevices?: number | null
          numTubes?: string | null
          partNotes?: string | null
          partNumber?: string
          partType?: string | null
          physicalSpecifications?: string | null
          qoh?: string | null
          rackType?: string | null
          safetyDistance?: string | null
          size?: string | null
          stdCost?: string | null
          stdLocation?: string | null
          stdPrice?: string | null
          subtype?: string | null
          unNumber?: string | null
          vdl?: string | null
          weight?: string | null
        }
        Relationships: []
      }
      firework_specifications: {
        Row: {
          created_at: string
          description: string | null
          id: string
          name: string
          slug: string
          sort_order: number
          spec: Json
          updated_at: string
        }
        Insert: {
          created_at?: string
          description?: string | null
          id?: string
          name: string
          slug: string
          sort_order?: number
          spec: Json
          updated_at?: string
        }
        Update: {
          created_at?: string
          description?: string | null
          id?: string
          name?: string
          slug?: string
          sort_order?: number
          spec?: Json
          updated_at?: string
        }
        Relationships: []
      }
      profiles: {
        Row: {
          created_at: string
          email: string | null
          full_name: string | null
          id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          email?: string | null
          full_name?: string | null
          id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          email?: string | null
          full_name?: string | null
          id?: string
          updated_at?: string
        }
        Relationships: []
      }
      shopping_list_items: {
        Row: {
          created_at: string
          firework_part_number: string | null
          id: string
          name: string
          position: number
          price_cents: number
          qty: number
          show_id: string
          updated_at: string
        }
        Insert: {
          created_at?: string
          firework_part_number?: string | null
          id?: string
          name: string
          position?: number
          price_cents?: number
          qty?: number
          show_id: string
          updated_at?: string
        }
        Update: {
          created_at?: string
          firework_part_number?: string | null
          id?: string
          name?: string
          position?: number
          price_cents?: number
          qty?: number
          show_id?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "shopping_list_items_show_id_fkey"
            columns: ["show_id"]
            isOneToOne: false
            referencedRelation: "shows"
            referencedColumns: ["id"]
          },
        ]
      }
      show_cues: {
        Row: {
          created_at: string
          description: string
          firework_specification_id: string | null
          id: string
          position: number
          render_params: Json | null
          show_id: string
          time_seconds: number | null
          updated_at: string
        }
        Insert: {
          created_at?: string
          description: string
          firework_specification_id?: string | null
          id?: string
          position?: number
          render_params?: Json | null
          show_id: string
          time_seconds?: number | null
          updated_at?: string
        }
        Update: {
          created_at?: string
          description?: string
          firework_specification_id?: string | null
          id?: string
          position?: number
          render_params?: Json | null
          show_id?: string
          time_seconds?: number | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "show_cues_firework_specification_id_fkey"
            columns: ["firework_specification_id"]
            isOneToOne: false
            referencedRelation: "firework_specifications"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "show_cues_show_id_fkey"
            columns: ["show_id"]
            isOneToOne: false
            referencedRelation: "shows"
            referencedColumns: ["id"]
          },
        ]
      }
      shows: {
        Row: {
          artist: string | null
          audio_path: string | null
          budget_cents: number | null
          created_at: string
          description: string | null
          duration_seconds: number | null
          effects_count: number
          id: string
          location: string | null
          mood_tags: string[]
          safety_meters: number | null
          slug: string
          song: string | null
          status: string
          sync_percent: number | null
          time_of_day: string | null
          title: string
          total_cents: number
          updated_at: string
          user_id: string
        }
        Insert: {
          artist?: string | null
          audio_path?: string | null
          budget_cents?: number | null
          created_at?: string
          description?: string | null
          duration_seconds?: number | null
          effects_count?: number
          id?: string
          location?: string | null
          mood_tags?: string[]
          safety_meters?: number | null
          slug: string
          song?: string | null
          status?: string
          sync_percent?: number | null
          time_of_day?: string | null
          title: string
          total_cents?: number
          updated_at?: string
          user_id: string
        }
        Update: {
          artist?: string | null
          audio_path?: string | null
          budget_cents?: number | null
          created_at?: string
          description?: string | null
          duration_seconds?: number | null
          effects_count?: number
          id?: string
          location?: string | null
          mood_tags?: string[]
          safety_meters?: number | null
          slug?: string
          song?: string | null
          status?: string
          sync_percent?: number | null
          time_of_day?: string | null
          title?: string
          total_cents?: number
          updated_at?: string
          user_id?: string
        }
        Relationships: []
      }
      "Wikifireworks sample database": {
        Row: {
          "BARCODE 1 (optional)": string | null
          "BARCODE 2 (optional)": string | null
          DESCRIPTION: string | null
          DURATION: number | null
          "FIREWORK TYPE": string | null
          "IMAGE URL": string | null
          NAME: string | null
          "PART NUMBER": string
          "PRO USE": boolean | null
          "QR CODE (optional)": string | null
          "WEBSITE URL": string | null
          "YOUTUBE URL": string | null
        }
        Insert: {
          "BARCODE 1 (optional)"?: string | null
          "BARCODE 2 (optional)"?: string | null
          DESCRIPTION?: string | null
          DURATION?: number | null
          "FIREWORK TYPE"?: string | null
          "IMAGE URL"?: string | null
          NAME?: string | null
          "PART NUMBER": string
          "PRO USE"?: boolean | null
          "QR CODE (optional)"?: string | null
          "WEBSITE URL"?: string | null
          "YOUTUBE URL"?: string | null
        }
        Update: {
          "BARCODE 1 (optional)"?: string | null
          "BARCODE 2 (optional)"?: string | null
          DESCRIPTION?: string | null
          DURATION?: number | null
          "FIREWORK TYPE"?: string | null
          "IMAGE URL"?: string | null
          NAME?: string | null
          "PART NUMBER"?: string
          "PRO USE"?: boolean | null
          "QR CODE (optional)"?: string | null
          "WEBSITE URL"?: string | null
          "YOUTUBE URL"?: string | null
        }
        Relationships: []
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      [_ in never]: never
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
