/** Ready-made briefs the dice button picks from to randomise the whole brief. */
export const RANDOM_BRIEFS = [
  'Gold and silver, slow elegant start, everything ends in one huge crackling finale.',
  'Warm reds and oranges building to a dense, beat-synced crescendo with a crackling send-off.',
  'Cool blues and whites, minimalist and precise, with one big surprise before the finale.',
  'A playful, colourful backyard show - quick bursts, a quiet moment, then a crackling finish.',
  'Cinematic and grand: a slow build, a quiet midpoint, and a finale that fills the sky.',
  'Emerald and white with clean comet lines, exact on the beat, then an all-out finale.',
  'Silver rings and blue strobes, futuristic and precise, with a false ending before the final hit.',
  'Romantic gold willows and soft rose palms, restrained verses, then one huge finale.',
  'Bright rainbow colour changes, playful syncopated accents, and a fast crackling finish.',
  'Deep red and silver, bold bar-downbeat hits, a moment of silence, then relentless energy.',
  'Icy white and cyan, sparse and elegant, with a held-back brocade surprise near the end.',
  'Classic gold brocade and palms, cinematic builds, broad choruses, and a massive finale.',
  'Green crossettes and sharp white strobes, high energy and non-stop through every drop.',
  'Minimal white rings on the strongest beats, lots of dark sky, and a gentle ending.',
  'Warm amber glitter with a quiet middle, rising beat by beat into a full-sky finale.',
  'Patriotic red, white, and blue with precise downbeat pairs and a gold crackling finish.',
  'Purple and silver, mysterious and restrained, then an unexpected three-position climax.',
  'Teal comets and gold palms, playful verses, dense choruses, and one clean final burst.',
] as const;
