import type { BurstTrailPreset, FireworkDesign } from './schema.ts';
import {
  BURST_TRAIL_MAX_STOPS,
  BURST_TRAIL_PRESETS,
  round2,
  TRAIL_CLOSING_DEFAULTS,
  TRAIL_OPENING_DEFAULTS,
} from './schema.ts';

export function isBurstTrailPreset(value: unknown): value is BurstTrailPreset {
  return typeof value === 'string' && (BURST_TRAIL_PRESETS as readonly string[]).includes(value);
}

export type BurstTrail = FireworkDesign['burstTrail'];

export type BurstTrailStop = BurstTrail['stops'][number];

export function cloneJson<T>(value: T): T {
  return JSON.parse(JSON.stringify(value)) as T;
}

export function burstTrailStop(
  position: number,
  density: number,
  size: number,
  sizeVariation: number,
  shapeWeights: BurstTrailStop['shapeWeights'],
): BurstTrailStop {
  return { position, density, size, sizeVariation, shapeWeights };
}

export const BURST_TRAIL_PRESET_DEFAULTS: Record<BurstTrailPreset, BurstTrail> = {
  none: {
    enabled: false,
    preset: 'none',
    colourMode: 'gold',
    particlesPerStar: 0,
    frontClump: 0,
    width: { front: 0, tail: 0, curve: 1 },
    particleSize: { base: 0.6, headScale: 1, tailScale: 0.6, variationPercent: 0 },
    opening: TRAIL_OPENING_DEFAULTS,
    closing: TRAIL_CLOSING_DEFAULTS,
    placement: { headGapPercent: 0 },
    spacing: { curve: 1, jitterPercent: 0 },
    lifetime: {
      mode: 'dynamic',
      percent: 0.1,
      baseSeconds: 0.4,
      variationPercent: 20,
      afterglowSeconds: 0,
    },
    intensity: { brightness: 0, fadeSoftness: 1 },
    flicker: { chance: 0, strength: 0, lifetimeMultiplier: 0.45 },
    motion: {
      gravity: -0.014,
      drag: 1.6,
      inheritedVelocity: 0,
      turbulence: 0,
      driftX: 0,
      driftY: -0.012,
      driftZ: 0,
      spin: 0,
    },
    stops: [
      burstTrailStop(0, 0, 0.6, 0, { circle: 0, square: 100, triangle: 0 }),
      burstTrailStop(100, 0, 0.4, 0, { circle: 0, square: 100, triangle: 0 }),
    ],
  },
  sparkDust: {
    enabled: true,
    preset: 'sparkDust',
    colourMode: 'star',
    particlesPerStar: 40,
    frontClump: 0.35,
    width: { front: 1.4, tail: 2.5, curve: 1.15 },
    particleSize: { base: 0.7, headScale: 1, tailScale: 0.45, variationPercent: 55 },
    opening: TRAIL_OPENING_DEFAULTS,
    closing: TRAIL_CLOSING_DEFAULTS,
    placement: { headGapPercent: 35 },
    spacing: { curve: 1, jitterPercent: 55 },
    lifetime: {
      mode: 'dynamic',
      percent: 0.16,
      baseSeconds: 1.1,
      variationPercent: 55,
      afterglowSeconds: 0.18,
    },
    intensity: { brightness: 0.92, fadeSoftness: 1.3 },
    flicker: { chance: 0.22, strength: 0.75, lifetimeMultiplier: 0.45 },
    motion: {
      gravity: -0.035,
      drag: 2.2,
      inheritedVelocity: 0.02,
      turbulence: 0.2,
      driftX: 0,
      driftY: -0.018,
      driftZ: 0,
      spin: 0,
    },
    stops: [
      burstTrailStop(0, 1.1, 0.78, 55, { circle: 76, square: 16, triangle: 8 }),
      burstTrailStop(55, 0.6, 0.58, 60, { circle: 82, square: 12, triangle: 6 }),
      burstTrailStop(100, 0.18, 0.34, 70, { circle: 90, square: 8, triangle: 2 }),
    ],
  },
  solidStreaks: {
    enabled: true,
    preset: 'solidStreaks',
    colourMode: 'gold',
    particlesPerStar: 104,
    frontClump: 0.55,
    width: { front: 2.4, tail: 2.4, curve: 1 },
    particleSize: { base: 1.0, headScale: 1, tailScale: 0.55, variationPercent: 28 },
    opening: TRAIL_OPENING_DEFAULTS,
    closing: TRAIL_CLOSING_DEFAULTS,
    placement: { headGapPercent: 45 },
    spacing: { curve: 1, jitterPercent: 22 },
    lifetime: {
      mode: 'dynamic',
      percent: 0.22,
      baseSeconds: 1.5,
      variationPercent: 28,
      afterglowSeconds: 0.3,
    },
    intensity: { brightness: 1.1, fadeSoftness: 1 },
    flicker: { chance: 0.08, strength: 0.9, lifetimeMultiplier: 0.45 },
    motion: {
      gravity: -0.018,
      drag: 1.4,
      inheritedVelocity: 0.02,
      turbulence: 0.045,
      driftX: 0,
      driftY: -0.012,
      driftZ: 0,
      spin: 0,
    },
    stops: [
      burstTrailStop(0, 1.5, 1.05, 28, { circle: 4, square: 88, triangle: 8 }),
      burstTrailStop(32, 1.15, 0.9, 30, { circle: 5, square: 86, triangle: 9 }),
      burstTrailStop(100, 0.34, 0.5, 34, { circle: 8, square: 84, triangle: 8 }),
    ],
  },
  willowHang: {
    enabled: true,
    preset: 'willowHang',
    colourMode: 'gold',
    particlesPerStar: 92,
    frontClump: 0.46,
    width: { front: 1.4, tail: 2.8, curve: 1.6 },
    particleSize: { base: 0.86, headScale: 1, tailScale: 0.45, variationPercent: 34 },
    opening: TRAIL_OPENING_DEFAULTS,
    closing: TRAIL_CLOSING_DEFAULTS,
    placement: { headGapPercent: 55 },
    spacing: { curve: 1.35, jitterPercent: 24 },
    lifetime: {
      mode: 'dynamic',
      percent: 0.34,
      baseSeconds: 2.6,
      variationPercent: 34,
      afterglowSeconds: 0.4,
    },
    intensity: { brightness: 0.95, fadeSoftness: 1.6 },
    flicker: { chance: 0.06, strength: 0.55, lifetimeMultiplier: 0.5 },
    motion: {
      gravity: -0.12,
      drag: 0.8,
      inheritedVelocity: 0.015,
      turbulence: 0.06,
      driftX: 0,
      driftY: -0.08,
      driftZ: 0,
      spin: 0,
    },
    stops: [
      burstTrailStop(0, 1.25, 0.9, 30, { circle: 8, square: 84, triangle: 8 }),
      burstTrailStop(48, 0.92, 0.75, 36, { circle: 12, square: 78, triangle: 10 }),
      burstTrailStop(100, 0.3, 0.4, 42, { circle: 22, square: 68, triangle: 10 }),
    ],
  },
  cometTail: {
    enabled: true,
    preset: 'cometTail',
    colourMode: 'starFade',
    particlesPerStar: 112,
    frontClump: 0.68,
    width: { front: 3.0, tail: 0.9, curve: 0.72 },
    particleSize: { base: 1.1, headScale: 1.15, tailScale: 0.35, variationPercent: 20 },
    opening: TRAIL_OPENING_DEFAULTS,
    closing: TRAIL_CLOSING_DEFAULTS,
    placement: { headGapPercent: 70 },
    spacing: { curve: 1.25, jitterPercent: 18 },
    lifetime: {
      mode: 'dynamic',
      percent: 0.24,
      baseSeconds: 1.5,
      variationPercent: 24,
      afterglowSeconds: 0.25,
    },
    intensity: { brightness: 1.2, fadeSoftness: 0.9 },
    flicker: { chance: 0.04, strength: 0.65, lifetimeMultiplier: 0.45 },
    motion: {
      gravity: -0.028,
      drag: 1.3,
      inheritedVelocity: 0.04,
      turbulence: 0.05,
      driftX: 0,
      driftY: -0.018,
      driftZ: 0,
      spin: 0,
    },
    stops: [
      burstTrailStop(0, 1.7, 1.35, 20, { circle: 6, square: 84, triangle: 10 }),
      burstTrailStop(42, 0.95, 0.9, 24, { circle: 8, square: 80, triangle: 12 }),
      burstTrailStop(100, 0.24, 0.44, 32, { circle: 18, square: 72, triangle: 10 }),
    ],
  },
  denseBrocade: {
    enabled: true,
    preset: 'denseBrocade',
    colourMode: 'gold',
    particlesPerStar: 120,
    frontClump: 0.72,
    width: { front: 3.2, tail: 2.7, curve: 0.86 },
    particleSize: { base: 1, headScale: 1.12, tailScale: 0.45, variationPercent: 18 },
    opening: TRAIL_OPENING_DEFAULTS,
    closing: TRAIL_CLOSING_DEFAULTS,
    placement: { headGapPercent: 70 },
    spacing: { curve: 1.4, jitterPercent: 15 },
    lifetime: {
      mode: 'dynamic',
      percent: 0.24,
      baseSeconds: 1.45,
      variationPercent: 22,
      afterglowSeconds: 0.16,
    },
    intensity: { brightness: 1.15, fadeSoftness: 1.1 },
    flicker: { chance: 0.1, strength: 0.95, lifetimeMultiplier: 0.45 },
    motion: {
      gravity: -0.014,
      drag: 1.6,
      inheritedVelocity: 0.018,
      turbulence: 0.05,
      driftX: 0,
      driftY: -0.012,
      driftZ: 0,
      spin: 0,
    },
    stops: [
      burstTrailStop(0, 1.85, 1.15, 22, { circle: 4, square: 88, triangle: 8 }),
      burstTrailStop(25, 1.25, 0.92, 24, { circle: 5, square: 86, triangle: 9 }),
      burstTrailStop(70, 0.62, 0.64, 30, { circle: 8, square: 82, triangle: 10 }),
      burstTrailStop(100, 0.24, 0.42, 36, { circle: 14, square: 76, triangle: 10 }),
    ],
  },
  silverRain: {
    enabled: true,
    preset: 'silverRain',
    colourMode: 'silver',
    particlesPerStar: 112,
    frontClump: 0.42,
    width: { front: 1.2, tail: 4.2, curve: 1.45 },
    particleSize: { base: 0.78, headScale: 1, tailScale: 0.38, variationPercent: 32 },
    opening: TRAIL_OPENING_DEFAULTS,
    closing: TRAIL_CLOSING_DEFAULTS,
    placement: { headGapPercent: 50 },
    spacing: { curve: 1.25, jitterPercent: 30 },
    lifetime: {
      mode: 'dynamic',
      percent: 0.42,
      baseSeconds: 2.8,
      variationPercent: 36,
      afterglowSeconds: 0.45,
    },
    intensity: { brightness: 1.12, fadeSoftness: 1.7 },
    flicker: { chance: 0.14, strength: 0.8, lifetimeMultiplier: 0.5 },
    motion: {
      gravity: -0.16,
      drag: 0.72,
      inheritedVelocity: 0.012,
      turbulence: 0.08,
      driftX: 0,
      driftY: -0.09,
      driftZ: 0,
      spin: 0,
    },
    stops: [
      burstTrailStop(0, 1.3, 0.94, 28, { circle: 12, square: 80, triangle: 8 }),
      burstTrailStop(55, 0.84, 0.68, 34, { circle: 18, square: 72, triangle: 10 }),
      burstTrailStop(100, 0.22, 0.3, 45, { circle: 34, square: 58, triangle: 8 }),
    ],
  },
  ghostFade: {
    enabled: true,
    preset: 'ghostFade',
    colourMode: 'starFade',
    particlesPerStar: 76,
    frontClump: 0.58,
    width: { front: 1.6, tail: 2.8, curve: 1.2 },
    particleSize: { base: 0.72, headScale: 1.08, tailScale: 0.2, variationPercent: 24 },
    opening: {
      size: { startPercent: 35 },
      visibility: { brightnessPercent: 165, particlesPercent: 72, revealPercent: 18 },
    },
    closing: {
      colour: { enabled: true, color: { r: 0.55, g: 0.72, b: 1 }, fadePercent: 46 },
      size: { enabled: true, endPercent: 0, shrinkPercent: 42 },
      spreadFade: { enabled: true, startAngle: 36, endOpacityPercent: 4 },
    },
    placement: { headGapPercent: 46 },
    spacing: { curve: 1.4, jitterPercent: 16 },
    lifetime: {
      mode: 'fixed',
      percent: 0.28,
      baseSeconds: 1.65,
      variationPercent: 22,
      afterglowSeconds: 0.55,
    },
    intensity: { brightness: 1.22, fadeSoftness: 2.25 },
    flicker: { chance: 0.03, strength: 0.45, lifetimeMultiplier: 0.5 },
    motion: {
      gravity: -0.045,
      drag: 1.05,
      inheritedVelocity: 0.025,
      turbulence: 0.035,
      driftX: 0,
      driftY: -0.018,
      driftZ: 0,
      spin: 0,
    },
    stops: [
      burstTrailStop(0, 1.1, 0.84, 22, { circle: 76, square: 20, triangle: 4 }),
      burstTrailStop(60, 0.68, 0.5, 28, { circle: 86, square: 12, triangle: 2 }),
      burstTrailStop(100, 0.12, 0.18, 36, { circle: 94, square: 6, triangle: 0 }),
    ],
  },
  dragonEgg: {
    enabled: true,
    preset: 'dragonEgg',
    colourMode: 'ember',
    particlesPerStar: 148,
    frontClump: 0.64,
    width: { front: 4.8, tail: 7.5, curve: 0.82 },
    particleSize: { base: 1.18, headScale: 1.3, tailScale: 0.3, variationPercent: 72 },
    opening: TRAIL_OPENING_DEFAULTS,
    closing: {
      ...TRAIL_CLOSING_DEFAULTS,
      size: { enabled: true, endPercent: 0, shrinkPercent: 34 },
    },
    placement: { headGapPercent: 38 },
    spacing: { curve: 0.72, jitterPercent: 78 },
    lifetime: {
      mode: 'fixed',
      percent: 0.2,
      baseSeconds: 0.58,
      variationPercent: 68,
      afterglowSeconds: 0.24,
    },
    intensity: { brightness: 1.5, fadeSoftness: 0.72 },
    flicker: { chance: 0.62, strength: 1.7, lifetimeMultiplier: 0.28 },
    motion: {
      gravity: -0.22,
      drag: 2.8,
      inheritedVelocity: 0.008,
      turbulence: 0.88,
      driftX: 0,
      driftY: -0.08,
      driftZ: 0,
      spin: 1.6,
    },
    stops: [
      burstTrailStop(0, 2.2, 1.4, 65, { circle: 48, square: 32, triangle: 20 }),
      burstTrailStop(45, 1.45, 0.92, 76, { circle: 58, square: 26, triangle: 16 }),
      burstTrailStop(100, 0.38, 0.3, 88, { circle: 76, square: 18, triangle: 6 }),
    ],
  },
  titaniumFlash: {
    enabled: true,
    preset: 'titaniumFlash',
    colourMode: 'silver',
    particlesPerStar: 180,
    frontClump: 0.78,
    width: { front: 6.5, tail: 5.5, curve: 0.65 },
    particleSize: { base: 1.45, headScale: 1.5, tailScale: 0.16, variationPercent: 62 },
    opening: {
      size: { startPercent: 55 },
      visibility: { brightnessPercent: 240, particlesPercent: 100, revealPercent: 8 },
    },
    closing: {
      ...TRAIL_CLOSING_DEFAULTS,
      size: { enabled: true, endPercent: 0, shrinkPercent: 24 },
    },
    placement: { headGapPercent: 24 },
    spacing: { curve: 0.58, jitterPercent: 66 },
    lifetime: {
      mode: 'fixed',
      percent: 0.12,
      baseSeconds: 0.22,
      variationPercent: 58,
      afterglowSeconds: 0.16,
    },
    intensity: { brightness: 2.25, fadeSoftness: 0.55 },
    flicker: { chance: 0.48, strength: 2.2, lifetimeMultiplier: 0.2 },
    motion: {
      gravity: -0.3,
      drag: 3.2,
      inheritedVelocity: 0.006,
      turbulence: 1.25,
      driftX: 0,
      driftY: -0.12,
      driftZ: 0,
      spin: 2.8,
    },
    stops: [
      burstTrailStop(0, 2.8, 1.8, 58, { circle: 42, square: 38, triangle: 20 }),
      burstTrailStop(35, 1.4, 0.92, 72, { circle: 58, square: 28, triangle: 14 }),
      burstTrailStop(100, 0.18, 0.2, 90, { circle: 82, square: 12, triangle: 6 }),
    ],
  },
  custom: {
    enabled: true,
    preset: 'custom',
    colourMode: 'starFade',
    particlesPerStar: 178,
    frontClump: 0.55,
    width: { front: 10, tail: 0, curve: 1 },
    particleSize: { base: 1.2, headScale: 1, tailScale: 0.35, variationPercent: 8 },
    opening: TRAIL_OPENING_DEFAULTS,
    closing: TRAIL_CLOSING_DEFAULTS,
    placement: { headGapPercent: 60 },
    spacing: { curve: 1, jitterPercent: 18 },
    lifetime: {
      mode: 'dynamic',
      percent: 0.18,
      baseSeconds: 8,
      variationPercent: 30,
      afterglowSeconds: 0.15,
    },
    intensity: { brightness: 1, fadeSoftness: 1 },
    flicker: { chance: 0.08, strength: 0.8, lifetimeMultiplier: 0.45 },
    motion: {
      gravity: -0.014,
      drag: 1.6,
      inheritedVelocity: 0.02,
      turbulence: 0.045,
      driftX: 0,
      driftY: -0.012,
      driftZ: 0,
      spin: 0,
    },
    stops: [
      burstTrailStop(0, 1, 2.68, 0, { circle: 0, square: 100, triangle: 0 }),
      burstTrailStop(100, 1, 0.08, 0, { circle: 0, square: 100, triangle: 0 }),
    ],
  },
};

export function makeBurstTrailPreset(preset: BurstTrailPreset): BurstTrail {
  return cloneJson(BURST_TRAIL_PRESET_DEFAULTS[preset]);
}

export function normaliseBurstTrailStops(stops: readonly BurstTrailStop[]): BurstTrailStop[] {
  const source = stops.length > 0 ? stops : BURST_TRAIL_PRESET_DEFAULTS.sparkDust.stops;
  return source
    .slice(0, BURST_TRAIL_MAX_STOPS)
    .map((stop) => {
      const weights = stop.shapeWeights;
      const total = weights.circle + weights.square + weights.triangle;
      const shapeWeights =
        total > 0
          ? {
              circle: round2((weights.circle / total) * 100),
              square: round2((weights.square / total) * 100),
              triangle: round2((weights.triangle / total) * 100),
            }
          : { circle: 0, square: 100, triangle: 0 };
      return {
        position: round2(Math.min(100, Math.max(0, stop.position))),
        density: round2(Math.min(4, Math.max(0, stop.density))),
        size: round2(Math.min(24, Math.max(0.08, stop.size))),
        sizeVariation: round2(Math.min(100, Math.max(0, stop.sizeVariation))),
        shapeWeights,
      };
    })
    .sort((a, b) => a.position - b.position);
}
