/** Marketing "Press" page. */

import type { Metadata } from 'next';
import { Download } from 'lucide-react';
import { Container } from '@/app/components/ui/Container';
import { Card } from '@/app/components/ui/Card';
import { Button } from '@/app/components/ui/Button';
import { Badge, Eyebrow } from '@/app/components/ui/Badge';
import { PageHeader } from '@/app/components/marketing/PageHeader';

export const metadata: Metadata = {
  title: 'Press · ShowCrafter',
  description:
    'Press releases, brand assets and media coverage for ShowCrafter — AI choreography for real consumer fireworks.',
};

const COVERAGE = [
  {
    outlet: 'ABC News',
    date: '18 Apr 2026',
    title: 'Brisbane students teach AI to choreograph backyard fireworks',
  },
  {
    outlet: 'Hackaday',
    date: '02 Apr 2026',
    title: 'ShowCrafter pairs librosa with an LLM to score the night sky',
  },
  {
    outlet: 'Australian Pyrotechnics Quarterly',
    date: '21 Mar 2026',
    title: 'ICON Pyrotechnics partners with UQ team on consumer choreography tool',
  },
  {
    outlet: 'Courier Mail',
    date: '07 Mar 2026',
    title: 'AI puts a fireworks-show designer in every backyard',
  },
];

const RELEASES = [
  {
    date: '21 Mar 2026',
    title: 'ShowCrafter announces partnership with ICON Pyrotechnics International',
    excerpt:
      "The platform will use ICON's full retail catalogue as the source-of-truth for every cue generated by its choreography agent.",
  },
  {
    date: '12 Feb 2026',
    title: 'ShowCrafter enters closed beta with 250 test designers',
    excerpt:
      'Backyard pyrotechnics enthusiasts in QLD, NSW and VIC are using ShowCrafter to design Anzac Day and New Year shows.',
  },
];

export default function PressPage() {
  return (
    <>
      <PageHeader
        eyebrow="Press"
        title="Press &amp; media."
        subtitle="Logos, story angles, founder bios and a contact for journalists. Everything you need to write about ShowCrafter."
      />

      <section className="py-24">
        <Container>
          <div className="mx-auto grid max-w-5xl gap-6 md:grid-cols-3">
            <Card radius="lg" className="p-6 md:col-span-1">
              <Eyebrow>Brand kit</Eyebrow>
              <h3 className="text-on-surface mt-3 text-lg font-bold">Logos &amp; wordmark</h3>
              <p className="text-on-surface-variant mt-2 text-sm leading-relaxed">
                SVG and PNG variants on light, dark and night-sky backgrounds.
              </p>
              <div className="mt-5">
                <Button
                  href="mailto:press@showcrafter.app?subject=ShowCrafter%20brand%20kit"
                  variant="secondary"
                  size="sm"
                >
                  Download <Download size={14} strokeWidth={1.75} />
                </Button>
              </div>
            </Card>
            <Card radius="lg" className="p-6 md:col-span-1">
              <Eyebrow>Screenshots</Eyebrow>
              <h3 className="text-on-surface mt-3 text-lg font-bold">Product imagery</h3>
              <p className="text-on-surface-variant mt-2 text-sm leading-relaxed">
                High-resolution captures of the editor, preview and dashboard.
              </p>
              <div className="mt-5">
                <Button
                  href="mailto:press@showcrafter.app?subject=ShowCrafter%20screenshots"
                  variant="secondary"
                  size="sm"
                >
                  Download <Download size={14} strokeWidth={1.75} />
                </Button>
              </div>
            </Card>
            <Card radius="lg" className="p-6 md:col-span-1">
              <Eyebrow>Press contact</Eyebrow>
              <h3 className="text-on-surface mt-3 text-lg font-bold">Talk to us</h3>
              <p className="text-on-surface-variant mt-2 text-sm leading-relaxed">
                Founders are available for interviews on 24-hour notice.
              </p>
              <div className="mt-5">
                <Button href="mailto:press@showcrafter.app" size="sm">
                  press@showcrafter.app
                </Button>
              </div>
            </Card>
          </div>
        </Container>
      </section>

      <section className="border-outline-variant/15 bg-surface-container-lowest border-t py-24">
        <Container>
          <div className="mx-auto max-w-4xl">
            <Eyebrow>Recent coverage</Eyebrow>
            <h2 className="text-on-surface mt-3 text-3xl font-bold tracking-tight md:text-5xl">
              In the news.
            </h2>
            <ul className="divide-outline-variant/15 border-outline-variant/15 mt-12 divide-y border-y">
              {COVERAGE.map((c) => (
                <li key={c.title}>
                  <div className="flex flex-col gap-2 py-6 md:flex-row md:items-center md:gap-6">
                    <div className="md:w-56">
                      <Badge tone="neutral">{c.outlet}</Badge>
                      <div className="text-on-surface-variant mt-2 text-xs tracking-widest uppercase">
                        {c.date}
                      </div>
                    </div>
                    <h3 className="text-on-surface flex-grow text-base font-bold md:text-lg">
                      {c.title}
                    </h3>
                  </div>
                </li>
              ))}
            </ul>
          </div>
        </Container>
      </section>

      <section className="py-24">
        <Container>
          <div className="mx-auto max-w-4xl">
            <Eyebrow>Press releases</Eyebrow>
            <h2 className="text-on-surface mt-3 text-3xl font-bold tracking-tight md:text-5xl">
              Official announcements.
            </h2>
            <div className="mt-12 space-y-4">
              {RELEASES.map((r) => (
                <Card key={r.title} radius="lg" className="p-7">
                  <div className="text-on-surface-variant text-xs tracking-widest uppercase">
                    {r.date}
                  </div>
                  <h3 className="text-on-surface mt-2 text-xl font-bold tracking-tight">
                    {r.title}
                  </h3>
                  <p className="text-on-surface-variant mt-3 text-sm leading-relaxed">
                    {r.excerpt}
                  </p>
                </Card>
              ))}
            </div>
          </div>
        </Container>
      </section>
    </>
  );
}
