'use client';

/** Generated by shadcn — do not edit manually. */

import { useEffect, useRef } from 'react';
import { useTheme } from 'next-themes';
import {
  Toaster as Sonner,
  toast as sonnerToast,
  useSonner,
  type ToastT,
  type ToasterProps,
} from 'sonner';
import { CheckIcon, InfoIcon, TriangleAlertIcon, XIcon, Loader2Icon } from 'lucide-react';

const TOAST_DURATION_MS = 3000;

const Toaster = ({ ...props }: ToasterProps) => {
  const { theme = 'system' } = useTheme();
  const defaultDuration = props.toastOptions?.duration ?? props.duration ?? TOAST_DURATION_MS;

  return (
    <>
      <Sonner
        theme={theme as ToasterProps['theme']}
        duration={TOAST_DURATION_MS}
        className="toaster group"
        icons={{
          success: (
            <span className="cn-toast-icon cn-toast-icon-success">
              <CheckIcon className="size-3.5" strokeWidth={2.5} />
            </span>
          ),
          info: (
            <span className="cn-toast-icon cn-toast-icon-info">
              <InfoIcon className="size-3.5" strokeWidth={2.5} />
            </span>
          ),
          warning: (
            <span className="cn-toast-icon cn-toast-icon-warning">
              <TriangleAlertIcon className="size-3.5" strokeWidth={2.5} />
            </span>
          ),
          error: (
            <span className="cn-toast-icon cn-toast-icon-error">
              <XIcon className="size-3.5" strokeWidth={2.5} />
            </span>
          ),
          loading: (
            <span className="cn-toast-icon cn-toast-icon-info">
              <Loader2Icon className="size-3.5 animate-spin" />
            </span>
          ),
        }}
        style={
          {
            '--normal-bg': 'var(--color-bg-elevated, var(--popover))',
            '--normal-text': 'var(--color-content-emphasis, var(--popover-foreground))',
            '--normal-border': 'var(--color-border-default, var(--border))',
            '--border-radius': '12px',
          } as React.CSSProperties
        }
        toastOptions={{
          classNames: {
            toast: 'cn-toast',
            title: 'cn-toast-title',
            description: 'cn-toast-description',
            closeButton: 'cn-toast-close',
          },
        }}
        {...props}
      />
      <ToastVisibilityExpiry defaultDuration={defaultDuration} />
    </>
  );
};

type ToastExpiry = {
  duration: number;
  signature: string;
  startedAt: number;
};

function ToastVisibilityExpiry({ defaultDuration }: { defaultDuration: number }) {
  const { toasts } = useSonner();
  const toastExpiries = useRef(new Map<number | string, ToastExpiry>());
  const hiddenExpiryTimer = useRef<number | null>(null);

  useEffect(() => {
    const now = Date.now();
    const activeToastIds = new Set<number | string>();

    toasts.forEach((toast) => {
      activeToastIds.add(toast.id);

      const duration = getToastDuration(toast, defaultDuration);
      if (duration === null || toast.type === 'loading') {
        toastExpiries.current.delete(toast.id);
        return;
      }

      const signature = getToastSignature(toast);
      const existingExpiry = toastExpiries.current.get(toast.id);

      if (!existingExpiry || existingExpiry.signature !== signature) {
        toastExpiries.current.set(toast.id, { duration, signature, startedAt: now });
      } else if (existingExpiry.duration !== duration) {
        toastExpiries.current.set(toast.id, { ...existingExpiry, duration });
      }
    });

    toastExpiries.current.forEach((_, toastId) => {
      if (!activeToastIds.has(toastId)) toastExpiries.current.delete(toastId);
    });
  }, [defaultDuration, toasts]);

  useEffect(() => {
    const clearHiddenExpiryTimer = () => {
      if (hiddenExpiryTimer.current === null) return;
      window.clearTimeout(hiddenExpiryTimer.current);
      hiddenExpiryTimer.current = null;
    };

    const dismissExpiredToasts = ({ allowWhenHidden = false } = {}) => {
      if (document.hidden && !allowWhenHidden) return;

      const now = Date.now();
      toastExpiries.current.forEach((expiry, toastId) => {
        if (now - expiry.startedAt >= expiry.duration) sonnerToast.dismiss(toastId);
      });
    };

    const scheduleHiddenExpiry = () => {
      clearHiddenExpiryTimer();
      if (!document.hidden) return;

      const now = Date.now();
      let nextDelay: number | null = null;

      toastExpiries.current.forEach((expiry) => {
        const delay = Math.max(0, expiry.duration - (now - expiry.startedAt));
        nextDelay = nextDelay === null ? delay : Math.min(nextDelay, delay);
      });

      if (nextDelay === null) return;

      hiddenExpiryTimer.current = window.setTimeout(() => {
        dismissExpiredToasts({ allowWhenHidden: true });
        scheduleHiddenExpiry();
      }, nextDelay);
    };

    const handleVisibilityChange = () => {
      if (document.hidden) {
        scheduleHiddenExpiry();
      } else {
        clearHiddenExpiryTimer();
        dismissExpiredToasts();
      }
    };
    const handleFocus = () => dismissExpiredToasts();

    document.addEventListener('visibilitychange', handleVisibilityChange);
    window.addEventListener('focus', handleFocus);

    return () => {
      clearHiddenExpiryTimer();
      document.removeEventListener('visibilitychange', handleVisibilityChange);
      window.removeEventListener('focus', handleFocus);
    };
  }, []);

  return null;
}

function getToastDuration(toast: ToastT, defaultDuration: number) {
  const duration = toast.duration ?? defaultDuration;
  return Number.isFinite(duration) ? duration : null;
}

function getToastSignature(toast: ToastT) {
  return [
    toast.type ?? 'default',
    getPrimitiveToastPart(toast.title),
    getPrimitiveToastPart(toast.description),
    Boolean(toast.action),
    Boolean(toast.cancel),
  ].join('|');
}

function getPrimitiveToastPart(value: ToastT['title']) {
  return typeof value === 'string' || typeof value === 'number' || typeof value === 'boolean'
    ? String(value)
    : '';
}

export { Toaster };
