import { RENDERER_BEHAVIOURS } from '@showcrafter/fireworks/behaviours';
import type { FireworkDesign, GeometryTuningGroupKey } from '@showcrafter/fireworks/design';
import { FIREWORK_GEOMETRIES } from '@showcrafter/fireworks/design';

/** Which geometry-tuning group drives each burst geometry. Geometries without
 *  bespoke shape behaviour (sphere, split_cross) have no entry and show no
 *  Geometry panel. */
export const GEOMETRY_TUNING_GROUPS: Partial<
  Record<FireworkDesign['geometry'], GeometryTuningGroupKey>
> = Object.fromEntries(
  Object.entries(RENDERER_BEHAVIOURS)
    .filter(([, entry]) => entry.tuning)
    .map(([geometry, entry]) => [geometry, entry.tuning]),
);

export type GeometryTuningSlider = {
  key: string;
  label: string;
  min: number;
  max: number;
  step: number;
  hint: string;
  unit?: string;
  inputKind?: 'slider' | 'number';
};

export const PERCENT_HINTS = {
  life: 'Star burn time relative to the burst life setting. 100% is unchanged.',
  gravity: 'How strongly gravity pulls these stars, relative to the burst gravity.',
  drag: 'Air resistance relative to a standard star. Lower drifts further.',
  headSize: 'Star head size relative to the layer size budget.',
  trailLife: 'Trail persistence relative to the standard trail life.',
};

export const GEOMETRY_TUNING_SLIDERS: Record<GeometryTuningGroupKey, GeometryTuningSlider[]> = {
  ring: [
    {
      key: 'wobble',
      label: 'Wobble',
      min: 0,
      max: 1,
      step: 0.01,
      hint: 'Out-of-plane jitter so the hoop reads as 3D rather than a razor line.',
    },
    {
      key: 'verticalSquash',
      label: 'Vertical squash',
      min: 0.2,
      max: 1.5,
      step: 0.01,
      hint: '1 is a perfect circle; lower flattens the hoop.',
    },
    {
      key: 'tiltVariation',
      label: 'Tilt variation',
      min: 0,
      max: 3,
      step: 0.05,
      hint: 'How far the hoop plane can randomly tilt, in radians.',
    },
    {
      key: 'lifePercent',
      label: 'Star life',
      min: 10,
      max: 300,
      step: 1,
      hint: PERCENT_HINTS.life,
    },
  ],
  crown: [
    {
      key: 'lift',
      label: 'Upward throw',
      min: 0,
      max: 2,
      step: 0.01,
      hint: 'How hard each frond is thrown upward before drooping.',
    },
    {
      key: 'liftVariation',
      label: 'Throw variation',
      min: 0,
      max: 2,
      step: 0.01,
      hint: 'Random extra upward throw per star.',
    },
    {
      key: 'spread',
      label: 'Spread',
      min: 0,
      max: 2,
      step: 0.01,
      hint: 'Sideways reach of the fronds.',
    },
    {
      key: 'spreadVariation',
      label: 'Spread variation',
      min: 0,
      max: 2,
      step: 0.01,
      hint: 'Random extra sideways reach per star.',
    },
  ],
  weeping: [
    {
      key: 'lift',
      label: 'Upward throw',
      min: 0,
      max: 2,
      step: 0.01,
      hint: 'How hard each strand is thrown upward before hanging.',
    },
    {
      key: 'liftVariation',
      label: 'Throw variation',
      min: 0,
      max: 2,
      step: 0.01,
      hint: 'Random extra upward throw per star.',
    },
    {
      key: 'spread',
      label: 'Spread',
      min: 0,
      max: 2,
      step: 0.01,
      hint: 'Sideways reach of the strands.',
    },
    {
      key: 'spreadVariation',
      label: 'Spread variation',
      min: 0,
      max: 2,
      step: 0.01,
      hint: 'Random extra sideways reach per star.',
    },
    {
      key: 'lifePercent',
      label: 'Star life',
      min: 10,
      max: 300,
      step: 1,
      hint: PERCENT_HINTS.life,
    },
    {
      key: 'gravityPercent',
      label: 'Gravity',
      min: 5,
      max: 300,
      step: 1,
      hint: PERCENT_HINTS.gravity,
    },
    { key: 'dragPercent', label: 'Drag', min: 10, max: 300, step: 1, hint: PERCENT_HINTS.drag },
  ],
  radialArms: [
    {
      key: 'arms',
      label: 'Arms',
      min: 2,
      max: 24,
      step: 1,
      hint: 'Number of straight spokes the stars group into.',
    },
    {
      key: 'angleJitter',
      label: 'Arm scatter',
      min: 0,
      max: 1,
      step: 0.01,
      hint: 'Random angular scatter of each star off its spoke.',
    },
    {
      key: 'armLength',
      label: 'Arm length',
      min: 0.1,
      max: 2,
      step: 0.01,
      hint: 'Base spoke length relative to burst speed.',
    },
    {
      key: 'lift',
      label: 'Upward throw',
      min: -1,
      max: 2,
      step: 0.01,
      hint: 'Vertical push applied to the whole spider.',
    },
    {
      key: 'liftVariation',
      label: 'Throw variation',
      min: 0,
      max: 2,
      step: 0.01,
      hint: 'Random extra vertical push per star.',
    },
    { key: 'dragPercent', label: 'Drag', min: 10, max: 300, step: 1, hint: PERCENT_HINTS.drag },
  ],
  fallingTail: [
    {
      key: 'spread',
      label: 'Spread',
      min: 0,
      max: 2,
      step: 0.01,
      hint: 'Sideways push before the stars start sinking.',
    },
    {
      key: 'spreadVariation',
      label: 'Spread variation',
      min: 0,
      max: 2,
      step: 0.01,
      hint: 'Random extra sideways push per star.',
    },
    {
      key: 'sink',
      label: 'Sink speed',
      min: 0,
      max: 2,
      step: 0.01,
      hint: 'Initial downward speed of the tails.',
    },
    {
      key: 'sinkVariation',
      label: 'Sink variation',
      min: 0,
      max: 2,
      step: 0.01,
      hint: 'Random extra downward speed per star.',
    },
    {
      key: 'lifePercent',
      label: 'Star life',
      min: 10,
      max: 300,
      step: 1,
      hint: PERCENT_HINTS.life,
    },
    {
      key: 'gravityPercent',
      label: 'Gravity',
      min: 5,
      max: 300,
      step: 1,
      hint: PERCENT_HINTS.gravity,
    },
    { key: 'dragPercent', label: 'Drag', min: 10, max: 300, step: 1, hint: PERCENT_HINTS.drag },
  ],
  pearls: [
    {
      key: 'spread',
      label: 'Spread',
      min: 0,
      max: 2,
      step: 0.01,
      hint: 'Sideways reach of the pearl ring.',
    },
    {
      key: 'spreadVariation',
      label: 'Spread variation',
      min: 0,
      max: 2,
      step: 0.01,
      hint: 'Random extra reach per pearl.',
    },
    {
      key: 'lift',
      label: 'Upward throw',
      min: -1,
      max: 2,
      step: 0.01,
      hint: 'Vertical push of the pearl ring.',
    },
    {
      key: 'liftVariation',
      label: 'Throw variation',
      min: 0,
      max: 2,
      step: 0.01,
      hint: 'Random extra vertical push per pearl.',
    },
    {
      key: 'lifePercent',
      label: 'Star life',
      min: 10,
      max: 300,
      step: 1,
      hint: PERCENT_HINTS.life,
    },
    {
      key: 'gravityPercent',
      label: 'Gravity',
      min: 5,
      max: 300,
      step: 1,
      hint: PERCENT_HINTS.gravity,
    },
    { key: 'dragPercent', label: 'Drag', min: 10, max: 300, step: 1, hint: PERCENT_HINTS.drag },
  ],
  fragmentCloud: [
    {
      key: 'speedBase',
      label: 'Base speed',
      min: 0.1,
      max: 2,
      step: 0.01,
      hint: 'Minimum speed factor for each fragment.',
    },
    {
      key: 'speedVariation',
      label: 'Speed variation',
      min: 0,
      max: 2,
      step: 0.01,
      hint: 'Random extra speed so the cloud looks uneven.',
    },
  ],
  heart: [
    {
      key: 'scaleX',
      label: 'Width',
      min: 0.2,
      max: 2.5,
      step: 0.01,
      hint: 'Horizontal scale of the heart outline.',
    },
    {
      key: 'scaleY',
      label: 'Height',
      min: 0.2,
      max: 2.5,
      step: 0.01,
      hint: 'Vertical scale of the heart outline.',
    },
    {
      key: 'depthScale',
      label: 'Depth',
      min: 0,
      max: 1,
      step: 0.01,
      hint: 'Front-to-back thickness. 0 keeps the heart perfectly planar.',
    },
    {
      key: 'outlineJitter',
      label: 'Outline variation',
      min: 0,
      max: 0.4,
      step: 0.005,
      hint: 'Seeded scatter around the mathematical heart outline.',
    },
    {
      key: 'tiltVariation',
      label: 'Tilt variation',
      min: 0,
      max: 3,
      step: 0.05,
      hint: 'Random tilt of the heart plane, in radians.',
    },
    {
      key: 'rotationDegrees',
      label: 'Rotation',
      min: -180,
      max: 180,
      step: 1,
      hint: 'Rotation of the heart inside its plane, in degrees.',
    },
  ],
  fivePointStar: [
    {
      key: 'points',
      label: 'Points',
      min: 3,
      max: 12,
      step: 1,
      hint: 'Number of points in the outlined star polygon.',
    },
    {
      key: 'innerRadius',
      label: 'Inner radius',
      min: 0.08,
      max: 0.95,
      step: 0.01,
      hint: 'Depth of the valleys between points. Lower values make sharper points.',
    },
    {
      key: 'scaleX',
      label: 'Width',
      min: 0.2,
      max: 2.5,
      step: 0.01,
      hint: 'Horizontal scale of the star outline.',
    },
    {
      key: 'scaleY',
      label: 'Height',
      min: 0.2,
      max: 2.5,
      step: 0.01,
      hint: 'Vertical scale of the star outline.',
    },
    {
      key: 'depthScale',
      label: 'Depth',
      min: 0,
      max: 1,
      step: 0.01,
      hint: 'Front-to-back thickness. 0 keeps the star perfectly planar.',
    },
    {
      key: 'outlineJitter',
      label: 'Outline variation',
      min: 0,
      max: 0.4,
      step: 0.005,
      hint: 'Seeded scatter around the polygon outline.',
    },
    {
      key: 'tiltVariation',
      label: 'Tilt variation',
      min: 0,
      max: 3,
      step: 0.05,
      hint: 'Random tilt of the star plane, in radians.',
    },
    {
      key: 'rotationDegrees',
      label: 'Rotation',
      min: -180,
      max: 180,
      step: 1,
      hint: 'Rotation of the star inside its plane, in degrees.',
    },
  ],
  bowtie: [
    {
      key: 'fanAngleDegrees',
      label: 'Fan angle',
      min: 10,
      max: 180,
      step: 1,
      hint: 'Total opening angle of each lobe fan, in degrees.',
    },
    {
      key: 'verticalScale',
      label: 'Fan height',
      min: 0,
      max: 1.5,
      step: 0.01,
      hint: 'Vertical thickness of the fans.',
    },
    {
      key: 'depthScale',
      label: 'Fan depth',
      min: 0,
      max: 1.5,
      step: 0.01,
      hint: 'Front-to-back thickness of the fans.',
    },
    {
      key: 'lengthBase',
      label: 'Lobe length',
      min: 0.1,
      max: 2,
      step: 0.01,
      hint: 'Base lobe length relative to burst speed.',
    },
    {
      key: 'lengthVariation',
      label: 'Length variation',
      min: 0,
      max: 2,
      step: 0.01,
      hint: 'Random extra lobe length per star.',
    },
  ],
  fish: [
    {
      key: 'verticalScale',
      label: 'Flatten',
      min: 0,
      max: 1.5,
      step: 0.01,
      hint: '1 is a full sphere; lower keeps the swarm flat.',
    },
    {
      key: 'lifeBaseSeconds',
      label: 'Life base',
      min: 0.1,
      max: 8,
      step: 0.1,
      hint: 'Minimum swim time in seconds.',
    },
    {
      key: 'lifeVariationSeconds',
      label: 'Life spread',
      min: 0,
      max: 8,
      step: 0.1,
      hint: 'Random extra swim time in seconds.',
    },
    {
      key: 'wiggleStrength',
      label: 'Wiggle strength',
      min: 0,
      max: 8,
      step: 0.1,
      hint: 'How hard each fish darts side to side.',
    },
    {
      key: 'wiggleRate',
      label: 'Wiggle rate',
      min: 0,
      max: 40,
      step: 0.5,
      hint: 'Wiggle oscillations per second on the primary axis.',
    },
    {
      key: 'wiggleRateCross',
      label: 'Cross wiggle rate',
      min: 0,
      max: 40,
      step: 0.5,
      hint: 'Wiggle oscillations per second on the crossing axis.',
    },
    {
      key: 'gravityPercent',
      label: 'Gravity',
      min: 5,
      max: 300,
      step: 1,
      hint: PERCENT_HINTS.gravity,
    },
    { key: 'dragPercent', label: 'Drag', min: 10, max: 300, step: 1, hint: PERCENT_HINTS.drag },
    {
      key: 'headSizePercent',
      label: 'Head size',
      min: 5,
      max: 200,
      step: 1,
      hint: PERCENT_HINTS.headSize,
    },
    {
      key: 'trailLifePercent',
      label: 'Trail life',
      min: 5,
      max: 300,
      step: 1,
      hint: PERCENT_HINTS.trailLife,
    },
  ],
  waterfall: [
    {
      key: 'width',
      label: 'Curtain width',
      min: 0,
      max: 1200,
      step: 0.1,
      unit: 'scene units',
      hint: 'Distance between the leftmost and rightmost stars, before scatter. Changing the star count only changes density.',
    },
    {
      key: 'scatterX',
      label: 'Width scatter',
      min: 0,
      max: 120,
      step: 1,
      hint: 'Random horizontal scatter of each spawn point.',
    },
    {
      key: 'scatterZ',
      label: 'Depth scatter',
      min: 0,
      max: 120,
      step: 1,
      hint: 'Random depth scatter of each spawn point.',
    },
    {
      key: 'dropStart',
      label: 'Drop start',
      min: 0,
      max: 240,
      step: 1,
      hint: 'How far below the burst point stars may start.',
    },
    {
      key: 'fallSpeed',
      label: 'Fall speed',
      min: 0,
      max: 6,
      step: 0.05,
      hint: 'Base downward speed of the curtain.',
    },
    {
      key: 'fallSpeedVariation',
      label: 'Fall variation',
      min: 0,
      max: 6,
      step: 0.05,
      hint: 'Random extra downward speed per star.',
    },
    {
      key: 'sideDrift',
      label: 'Side drift',
      min: 0,
      max: 2,
      step: 0.01,
      hint: 'Sideways drift while falling.',
    },
    {
      key: 'depthDrift',
      label: 'Depth drift',
      min: 0,
      max: 2,
      step: 0.01,
      hint: 'Front-to-back drift while falling.',
    },
    {
      key: 'lifePercent',
      label: 'Star life',
      min: 10,
      max: 300,
      step: 1,
      hint: PERCENT_HINTS.life,
    },
    {
      key: 'gravityBase',
      label: 'Gravity pull',
      min: -2,
      max: 0,
      step: 0.01,
      hint: 'Base gravity while falling; more negative falls faster.',
    },
    {
      key: 'gravityVariation',
      label: 'Gravity variation',
      min: 0,
      max: 2,
      step: 0.01,
      hint: 'Random extra gravity per star.',
    },
    { key: 'dragPercent', label: 'Drag', min: 10, max: 300, step: 1, hint: PERCENT_HINTS.drag },
    {
      key: 'headSizePercent',
      label: 'Head size',
      min: 5,
      max: 200,
      step: 1,
      hint: PERCENT_HINTS.headSize,
    },
  ],
  whirl: [
    {
      key: 'verticalBias',
      label: 'Vertical bias',
      min: -1,
      max: 1,
      step: 0.01,
      hint: 'Negative sends more stars downward; positive lifts the whirl.',
    },
    {
      key: 'spinStrength',
      label: 'Spin strength',
      min: 0,
      max: 10,
      step: 0.1,
      hint: 'How hard the spiral force pulls the corkscrew arms.',
    },
    {
      key: 'spinRate',
      label: 'Spin rate',
      min: 0,
      max: 40,
      step: 0.5,
      hint: 'Spiral oscillations per second.',
    },
    {
      key: 'lifeBaseSeconds',
      label: 'Life base',
      min: 0.1,
      max: 8,
      step: 0.1,
      hint: 'Minimum star burn time in seconds.',
    },
    {
      key: 'lifeVariationSeconds',
      label: 'Life spread',
      min: 0,
      max: 8,
      step: 0.1,
      hint: 'Random extra burn time in seconds.',
    },
    {
      key: 'gravityPercent',
      label: 'Gravity',
      min: 5,
      max: 300,
      step: 1,
      hint: PERCENT_HINTS.gravity,
    },
    { key: 'dragPercent', label: 'Drag', min: 10, max: 300, step: 1, hint: PERCENT_HINTS.drag },
    {
      key: 'headSizePercent',
      label: 'Head size',
      min: 5,
      max: 200,
      step: 1,
      hint: PERCENT_HINTS.headSize,
    },
    {
      key: 'trailLifePercent',
      label: 'Trail life',
      min: 5,
      max: 300,
      step: 1,
      hint: PERCENT_HINTS.trailLife,
    },
  ],
  singleTail: [
    {
      key: 'inheritPercent',
      label: 'Carried speed',
      min: 0,
      max: 100,
      step: 1,
      hint: 'How much of the shell velocity the comet keeps.',
    },
    {
      key: 'driftPercent',
      label: 'Drift',
      min: 0,
      max: 100,
      step: 1,
      hint: 'Random sideways drift as a percentage of burst speed.',
    },
    {
      key: 'riseFactor',
      label: 'Rise',
      min: 0,
      max: 2,
      step: 0.01,
      hint: 'Minimum upward speed as a fraction of burst speed.',
    },
    {
      key: 'pushFactor',
      label: 'Push',
      min: 0,
      max: 2,
      step: 0.01,
      hint: 'Extra upward push added to the inherited rise.',
    },
    {
      key: 'lifePercent',
      label: 'Star life',
      min: 10,
      max: 300,
      step: 1,
      hint: PERCENT_HINTS.life,
    },
    {
      key: 'headSizePercent',
      label: 'Head size',
      min: 5,
      max: 200,
      step: 1,
      hint: PERCENT_HINTS.headSize,
    },
    {
      key: 'trailLifePercent',
      label: 'Trail life',
      min: 5,
      max: 300,
      step: 1,
      hint: PERCENT_HINTS.trailLife,
    },
  ],
  upwardFan: [
    {
      key: 'spreadAngleDegrees',
      label: 'Fan angle',
      min: 10,
      max: 300,
      step: 1,
      hint: 'Total sideways opening angle of the fan, in degrees.',
    },
    {
      key: 'fanBase',
      label: 'Fan reach',
      min: 0,
      max: 2,
      step: 0.01,
      hint: 'Minimum sideways throw of each star.',
    },
    {
      key: 'fanVariation',
      label: 'Reach variation',
      min: 0,
      max: 2,
      step: 0.01,
      hint: 'Random extra sideways throw per star.',
    },
    {
      key: 'spawnScatter',
      label: 'Tube scatter',
      min: 0,
      max: 120,
      step: 1,
      hint: 'Random horizontal scatter of each spawn point.',
    },
    {
      key: 'riseBase',
      label: 'Muzzle height',
      min: 0,
      max: 120,
      step: 1,
      hint: 'Base spawn height above the tube.',
    },
    {
      key: 'riseVariation',
      label: 'Height variation',
      min: 0,
      max: 120,
      step: 1,
      hint: 'Random extra spawn height per star.',
    },
    {
      key: 'riseSpeed',
      label: 'Rise speed',
      min: 0,
      max: 4,
      step: 0.01,
      hint: 'Base upward speed as a fraction of burst speed.',
    },
    {
      key: 'riseSpeedVariation',
      label: 'Rise variation',
      min: 0,
      max: 4,
      step: 0.01,
      hint: 'Random extra upward speed per star.',
    },
    {
      key: 'depthScale',
      label: 'Fan depth',
      min: 0,
      max: 1.5,
      step: 0.01,
      hint: 'Front-to-back thickness of the fan.',
    },
    {
      key: 'lifePercent',
      label: 'Star life',
      min: 10,
      max: 300,
      step: 1,
      hint: PERCENT_HINTS.life,
    },
    { key: 'dragPercent', label: 'Drag', min: 10, max: 300, step: 1, hint: PERCENT_HINTS.drag },
    {
      key: 'headSizePercent',
      label: 'Head size',
      min: 5,
      max: 200,
      step: 1,
      hint: PERCENT_HINTS.headSize,
    },
    {
      key: 'trailLifePercent',
      label: 'Trail life',
      min: 5,
      max: 300,
      step: 1,
      hint: PERCENT_HINTS.trailLife,
    },
  ],
  romanCandle: [
    {
      key: 'durationSeconds',
      label: 'Sequence duration',
      min: 0.1,
      max: 30,
      step: 0.1,
      inputKind: 'number',
      hint: 'How long this ground effect emits, in seconds.',
    },
    {
      key: 'spread',
      label: 'Aim wobble',
      min: 0,
      max: 2,
      step: 0.01,
      hint: 'Sideways aim wobble per shot, in radians.',
    },
    {
      key: 'azimuth',
      label: 'Depth wobble',
      min: 0,
      max: 2,
      step: 0.01,
      hint: 'Front-to-back aim wobble per shot, in radians.',
    },
    {
      key: 'speedBase',
      label: 'Shot speed',
      min: 0.1,
      max: 3,
      step: 0.01,
      hint: 'Minimum shot speed as a fraction of burst speed.',
    },
    {
      key: 'speedVariation',
      label: 'Speed variation',
      min: 0,
      max: 3,
      step: 0.01,
      hint: 'Random extra speed per shot.',
    },
    {
      key: 'muzzleScatter',
      label: 'Muzzle scatter',
      min: 0,
      max: 60,
      step: 1,
      hint: 'Random muzzle offset of each shot.',
    },
    {
      key: 'lateralScale',
      label: 'Sideways throw',
      min: 0,
      max: 1.5,
      step: 0.01,
      hint: 'Sideways speed factor of each shot.',
    },
    {
      key: 'depthScale',
      label: 'Depth throw',
      min: 0,
      max: 1.5,
      step: 0.01,
      hint: 'Front-to-back speed factor of each shot.',
    },
    {
      key: 'riseBase',
      label: 'Rise speed',
      min: 0,
      max: 4,
      step: 0.01,
      hint: 'Base upward speed of each shot.',
    },
    {
      key: 'riseVariation',
      label: 'Rise variation',
      min: 0,
      max: 4,
      step: 0.01,
      hint: 'Random extra upward speed per shot.',
    },
    {
      key: 'lifePercent',
      label: 'Star life',
      min: 10,
      max: 300,
      step: 1,
      hint: PERCENT_HINTS.life,
    },
    { key: 'dragPercent', label: 'Drag', min: 10, max: 300, step: 1, hint: PERCENT_HINTS.drag },
    {
      key: 'headSizePercent',
      label: 'Head size',
      min: 5,
      max: 200,
      step: 1,
      hint: PERCENT_HINTS.headSize,
    },
    {
      key: 'trailLifePercent',
      label: 'Trail life',
      min: 5,
      max: 300,
      step: 1,
      hint: PERCENT_HINTS.trailLife,
    },
  ],
  fountain: [
    {
      key: 'durationSeconds',
      label: 'Emission duration',
      min: 0.1,
      max: 30,
      step: 0.1,
      inputKind: 'number',
      hint: 'How long this ground effect emits, in seconds.',
    },
    {
      key: 'coneAngleDegrees',
      label: 'Cone angle',
      min: 2,
      max: 180,
      step: 1,
      hint: 'Total opening angle of the spray cone, in degrees.',
    },
    {
      key: 'speedBase',
      label: 'Spark speed',
      min: 0.05,
      max: 3,
      step: 0.01,
      hint: 'Minimum spark speed as a fraction of burst speed.',
    },
    {
      key: 'speedVariation',
      label: 'Speed variation',
      min: 0,
      max: 3,
      step: 0.01,
      hint: 'Random extra speed per spark.',
    },
    {
      key: 'spawnScatter',
      label: 'Nozzle scatter',
      min: 0,
      max: 60,
      step: 1,
      hint: "Random offset of each spark's spawn point.",
    },
    {
      key: 'lateralScale',
      label: 'Sideways spray',
      min: 0,
      max: 1.5,
      step: 0.01,
      hint: 'Sideways speed factor of the spray.',
    },
    {
      key: 'lifePercent',
      label: 'Spark life',
      min: 5,
      max: 300,
      step: 1,
      hint: PERCENT_HINTS.life,
    },
    { key: 'dragPercent', label: 'Drag', min: 10, max: 300, step: 1, hint: PERCENT_HINTS.drag },
    {
      key: 'headSizePercent',
      label: 'Spark size',
      min: 5,
      max: 200,
      step: 1,
      hint: PERCENT_HINTS.headSize,
    },
    {
      key: 'trailLifePercent',
      label: 'Trail life',
      min: 5,
      max: 300,
      step: 1,
      hint: PERCENT_HINTS.trailLife,
    },
  ],
};

export const GEOMETRY_OPTIONS = FIREWORK_GEOMETRIES.map((geometry) => ({
  value: geometry,
  label:
    {
      sphere: 'Sphere',
      crown: 'Crown',
      weeping: 'Weeping willow',
      radial_arms: 'Radial arms',
      ring: 'Ring',
      split_cross: 'Split cross',
      falling_tail: 'Falling tail',
      single_tail: 'Single comet',
      upward_fan: 'Upward fan',
      fragment_cloud: 'Fragment cloud',
      heart: 'Heart',
      five_point_star: 'Outlined star',
      pearls: 'Pearls',
      fish: 'Flying fish',
      waterfall: 'Waterfall',
      whirl: 'Tourbillion',
      bowtie: 'Bow tie',
      roman_candle: 'Roman candle',
      fountain: 'Fountain',
    }[geometry] ?? geometry,
}));
