-- Explicit catalogue capabilities; all other table and function privileges remain revoked.
grant execute on function private.create_effect_draft(uuid, text, text, text, jsonb, text, uuid), public.create_effect_draft(uuid, text, text, text, jsonb, text, uuid) to authenticated, service_role;
grant execute on function private.save_effect_draft(uuid, jsonb, text, text, jsonb, uuid), public.save_effect_draft(uuid, jsonb, text, text, jsonb, uuid) to authenticated, service_role;
grant execute on function private.create_product_draft(uuid, text, text, text, jsonb, jsonb, text), public.create_product_draft(uuid, text, text, text, jsonb, jsonb, text) to authenticated, service_role;
grant execute on function private.save_product_draft(uuid, jsonb, jsonb, text), public.save_product_draft(uuid, jsonb, jsonb, text) to authenticated, service_role;
grant execute on function private.publish_effect_version(uuid), public.publish_effect_version(uuid) to authenticated, service_role;
grant execute on function private.publish_product_version(uuid), public.publish_product_version(uuid) to authenticated, service_role;
grant execute on function private.archive_effect(uuid), public.archive_effect(uuid) to authenticated, service_role;
grant execute on function private.archive_product(uuid), public.archive_product(uuid) to authenticated, service_role;
grant execute on function private.confirm_product_safety(uuid, smallint, smallint, jsonb, uuid, uuid, smallint, numeric), public.confirm_product_safety(uuid, smallint, smallint, jsonb, uuid, uuid, smallint, numeric) to authenticated, service_role;
grant execute on function private.create_pack(text, text), public.create_pack(text, text) to authenticated, service_role;
grant execute on function private.save_pack_items(uuid, jsonb), public.save_pack_items(uuid, jsonb) to authenticated, service_role;
grant execute on function private.publish_pack(uuid), public.publish_pack(uuid) to authenticated, service_role;
grant execute on function private.supplier_ids() to authenticated, service_role;
grant execute on function private.design_schema(), private.composition_schema() to service_role;
revoke all on public.effects from public, anon, authenticated, service_role;
grant all on public.effects to service_role;
grant select on public.effects to authenticated;
grant select on public.effects to anon;
revoke all on public.effect_versions from public, anon, authenticated, service_role;
grant all on public.effect_versions to service_role;
grant select on public.effect_versions to authenticated;
grant select on public.effect_versions to anon;
revoke all on public.poster_renders from public, anon, authenticated, service_role;
grant all on public.poster_renders to service_role;
grant select on public.poster_renders to authenticated;
grant select on public.poster_renders to anon;
grant insert, update on public.poster_renders to authenticated;
revoke all on public.media from public, anon, authenticated, service_role;
grant all on public.media to service_role;
grant select on public.media to authenticated;
grant insert on public.media to authenticated;
revoke all on public.products from public, anon, authenticated, service_role;
grant all on public.products to service_role;
grant select on public.products to authenticated;
grant select on public.products to anon;
revoke all on public.product_versions from public, anon, authenticated, service_role;
grant all on public.product_versions to service_role;
grant select on public.product_versions to authenticated;
grant select on public.product_versions to anon;
revoke all on public.product_version_effects from public, anon, authenticated, service_role;
grant all on public.product_version_effects to service_role;
grant select on public.product_version_effects to authenticated;
grant select on public.product_version_effects to anon;
revoke all on public.pack_items from public, anon, authenticated, service_role;
grant all on public.pack_items to service_role;
grant select on public.pack_items to authenticated;
grant select on public.pack_items to anon;
revoke all on public.product_markets from public, anon, authenticated, service_role;
grant all on public.product_markets to service_role;
grant select on public.product_markets to authenticated;
grant select on public.product_markets to anon;
revoke all on public.product_media from public, anon, authenticated, service_role;
grant all on public.product_media to service_role;
grant select on public.product_media to authenticated;
grant select on public.product_media to anon;
grant insert, update, delete on public.product_media to authenticated;
revoke all on public.suppliers from public, anon, authenticated, service_role;
grant all on public.suppliers to service_role;
grant select on public.suppliers to authenticated;
grant insert, update, delete on public.suppliers to authenticated;
revoke all on public.supplier_members from public, anon, authenticated, service_role;
grant all on public.supplier_members to service_role;
grant select on public.supplier_members to authenticated;
grant insert, update, delete on public.supplier_members to authenticated;
revoke all on public.supplier_products from public, anon, authenticated, service_role;
grant all on public.supplier_products to service_role;
grant select on public.supplier_products to authenticated;
grant insert, update, delete on public.supplier_products to authenticated;
grant execute on function private.save_product_details(uuid, text, text, text), public.save_product_details(uuid, text, text, text) to authenticated, service_role;
grant execute on function private.save_effect_details(uuid, text, text, boolean), public.save_effect_details(uuid, text, text, boolean) to authenticated, service_role;
