-- Explicit platform capabilities; hashes, sync results, audit writes and support lifecycle are backend-owned.
revoke all on public.integrations from public, anon, authenticated, service_role;
grant all on public.integrations to service_role;
grant select (id,organisation_id,provider,status,config,last_sync_at,created_at,updated_at) on public.integrations to authenticated;
grant insert (id,organisation_id,provider,status,config), update (status,config) on public.integrations to authenticated;
revoke all on public.sync_runs from public, anon, authenticated, service_role;
grant all on public.sync_runs to service_role;
grant select on public.sync_runs to authenticated;
revoke all on public.webhook_endpoints from public, anon, authenticated, service_role;
grant all on public.webhook_endpoints to service_role;
grant select (id,organisation_id,url,events,active,created_at,updated_at) on public.webhook_endpoints to authenticated;
grant insert (id,organisation_id,url,events,active), update (url,events,active), delete on public.webhook_endpoints to authenticated;
revoke all on public.api_keys from public, anon, authenticated, service_role;
grant all on public.api_keys to service_role;
grant select (id,organisation_id,prefix,scopes,last_used_at,revoked_at,created_at,updated_at) on public.api_keys to authenticated;
revoke all on public.feature_flags from public, anon, authenticated, service_role;
grant all on public.feature_flags to service_role;
grant select on public.feature_flags to authenticated;
grant insert, update, delete on public.feature_flags to authenticated;
revoke all on public.flag_overrides from public, anon, authenticated, service_role;
grant all on public.flag_overrides to service_role;
grant select on public.flag_overrides to authenticated;
grant insert, update, delete on public.flag_overrides to authenticated;
revoke all on public.platform_settings from public, anon, authenticated, service_role;
grant all on public.platform_settings to service_role;
grant select on public.platform_settings to authenticated;
grant insert, update, delete on public.platform_settings to authenticated;
revoke all on public.notifications from public, anon, authenticated, service_role;
grant all on public.notifications to service_role;
grant select on public.notifications to authenticated;
grant update (read_at) on public.notifications to authenticated;
revoke all on public.notification_preferences from public, anon, authenticated, service_role;
grant all on public.notification_preferences to service_role;
grant select on public.notification_preferences to authenticated;
grant insert, update, delete on public.notification_preferences to authenticated;
revoke all on public.audit_log from public, anon, authenticated, service_role;
grant select, insert on public.audit_log to service_role;
grant select on public.audit_log to authenticated;
revoke all on public.support_sessions from public, anon, authenticated, service_role;
grant all on public.support_sessions to service_role;
grant select on public.support_sessions to authenticated;
revoke all on function public.flag_on(text,uuid) from public, anon, authenticated, service_role;
grant execute on function public.flag_on(text,uuid) to authenticated, service_role;
revoke all on function private.flag_on(text,uuid) from public, anon, authenticated, service_role;
grant execute on function private.flag_on(text,uuid) to authenticated, service_role;
revoke all on function public.start_support_session(uuid,uuid,uuid,text,text,text,timestamptz) from public, anon, authenticated, service_role;
grant execute on function public.start_support_session(uuid,uuid,uuid,text,text,text,timestamptz) to authenticated, service_role;
revoke all on function private.start_support_session(uuid,uuid,uuid,text,text,text,timestamptz) from public, anon, authenticated, service_role;
grant execute on function private.start_support_session(uuid,uuid,uuid,text,text,text,timestamptz) to authenticated, service_role;
revoke all on function public.end_support_session(uuid) from public, anon, authenticated, service_role;
grant execute on function public.end_support_session(uuid) to authenticated, service_role;
revoke all on function private.end_support_session(uuid) from public, anon, authenticated, service_role;
grant execute on function private.end_support_session(uuid) to authenticated, service_role;
grant usage, select on sequence public.notifications_id_seq, public.audit_log_id_seq to service_role;
