-- Explicit jobs capabilities; clients receive only the authorised operations.
revoke all on public.prompt_versions from public, anon, authenticated, service_role;
grant all on public.prompt_versions to service_role;
grant select on public.prompt_versions to authenticated;
revoke all on public.llm_calls from public, anon, authenticated, service_role;
grant all on public.llm_calls to service_role;
grant select on public.llm_calls to authenticated;
revoke all on public.jobs from public, anon, authenticated, service_role;
grant all on public.jobs to service_role;
grant select on public.jobs to authenticated;
revoke all on public.rate_limit_buckets from public, anon, authenticated, service_role;
grant all on public.rate_limit_buckets to service_role;
revoke all on function public.claim_job(text[],text) from public, anon, authenticated, service_role;
grant execute on function public.claim_job(text[],text) to service_role;
revoke all on function public.complete_job(uuid,text,smallint,jsonb,jsonb) from public, anon, authenticated, service_role;
grant execute on function public.complete_job(uuid,text,smallint,jsonb,jsonb) to service_role;
revoke all on function public.fail_job(uuid,text,smallint,text,jsonb) from public, anon, authenticated, service_role;
grant execute on function public.fail_job(uuid,text,smallint,text,jsonb) to service_role;
revoke all on function public.renew_job_lease(uuid,text,smallint) from public, anon, authenticated, service_role;
grant execute on function public.renew_job_lease(uuid,text,smallint) to service_role;
revoke all on function private.claim_job(text[],text) from public, anon, authenticated, service_role;
grant execute on function private.claim_job(text[],text) to service_role;
revoke all on function private.finish_job(uuid,text,smallint,jsonb,text,jsonb) from public, anon, authenticated, service_role;
grant execute on function private.finish_job(uuid,text,smallint,jsonb,text,jsonb) to service_role;
revoke all on function private.renew_job_lease(uuid,text,smallint) from public, anon, authenticated, service_role;
grant execute on function private.renew_job_lease(uuid,text,smallint) to service_role;
revoke all on function private.consume_rate_limit(text,numeric,numeric,numeric) from public, anon, authenticated, service_role;
grant execute on function private.consume_rate_limit(text,numeric,numeric,numeric) to service_role;
grant usage, select on sequence public.llm_calls_id_seq to service_role;
