-- Remove the old templates that reference non-existent firework slugs
DELETE FROM show_templates;

-- Insert 3 new templates using real effect_specs slugs and real HAC product pricing
INSERT INTO show_templates (
  slug, title, theme, description,
  duration_seconds, budget_cents, total_cents, effects_count,
  time_of_day, mood_tags, preview_cues,
  is_featured, sort_order
) VALUES

-- Show 1: Outback Gold — big night show built from premium HAC cakes
(
  'outback-gold',
  'Outback Gold',
  'Warm gold crescendo with a blazing finale',
  'A premium three-minute night show built around ICON''s gold-heavy HAC cakes. Opens with cascading gold palms, builds through silver bursts and mega blooms, and closes with a white-strobe barrage.',
  180,
  25000,
  20925,
  30,
  'Night',
  ARRAY['Grand finale focused', 'Warm tones', 'Premium'],
  '[
    {"timeSeconds": 3,   "fireworkSlug": "fib-gold",     "description": "Gold sphere"},
    {"timeSeconds": 8,   "fireworkSlug": "fib-mini",     "description": "Mini burst"},
    {"timeSeconds": 13,  "fireworkSlug": "fib-gold",     "description": "Gold sphere"},
    {"timeSeconds": 19,  "fireworkSlug": "strobe-white", "description": "White strobe"},
    {"timeSeconds": 25,  "fireworkSlug": "fib-mega",     "description": "Mega bloom"},
    {"timeSeconds": 31,  "fireworkSlug": "fib-gold",     "description": "Gold sphere"},
    {"timeSeconds": 37,  "fireworkSlug": "fib-mini",     "description": "Mini burst"},
    {"timeSeconds": 42,  "fireworkSlug": "wave-rainbow", "description": "Rainbow wave"},
    {"timeSeconds": 48,  "fireworkSlug": "fib-gold",     "description": "Gold sphere"},
    {"timeSeconds": 54,  "fireworkSlug": "strobe-mixed", "description": "Mixed strobe"},
    {"timeSeconds": 60,  "fireworkSlug": "fib-red",      "description": "Red sphere"},
    {"timeSeconds": 66,  "fireworkSlug": "fib-gold",     "description": "Gold sphere"},
    {"timeSeconds": 72,  "fireworkSlug": "fib-mega",     "description": "Mega bloom"},
    {"timeSeconds": 78,  "fireworkSlug": "strobe-white", "description": "White strobe"},
    {"timeSeconds": 84,  "fireworkSlug": "fib-gold",     "description": "Gold sphere"},
    {"timeSeconds": 90,  "fireworkSlug": "wave-rainbow", "description": "Rainbow wave"},
    {"timeSeconds": 96,  "fireworkSlug": "fib-mini",     "description": "Mini burst"},
    {"timeSeconds": 102, "fireworkSlug": "fib-gold",     "description": "Gold sphere"},
    {"timeSeconds": 108, "fireworkSlug": "fib-mega",     "description": "Mega bloom"},
    {"timeSeconds": 114, "fireworkSlug": "strobe-mixed", "description": "Mixed strobe"},
    {"timeSeconds": 120, "fireworkSlug": "fib-gold",     "description": "Gold sphere"},
    {"timeSeconds": 126, "fireworkSlug": "strobe-white", "description": "White strobe"},
    {"timeSeconds": 132, "fireworkSlug": "fib-mega",     "description": "Mega bloom"},
    {"timeSeconds": 138, "fireworkSlug": "wave-rainbow", "description": "Rainbow wave"},
    {"timeSeconds": 144, "fireworkSlug": "fib-gold",     "description": "Gold sphere"},
    {"timeSeconds": 150, "fireworkSlug": "fib-mini",     "description": "Mini burst"},
    {"timeSeconds": 156, "fireworkSlug": "strobe-mixed", "description": "Mixed strobe"},
    {"timeSeconds": 162, "fireworkSlug": "fib-mega",     "description": "Mega bloom"},
    {"timeSeconds": 168, "fireworkSlug": "strobe-white", "description": "White strobe"},
    {"timeSeconds": 175, "fireworkSlug": "strobe-mixed", "description": "Finale barrage"}
  ]'::jsonb,
  true,
  10
),

-- Show 2: Colour Burst — vibrant dusk show cycling through the HAC Hi-Vis colour range
(
  'colour-burst',
  'Colour Burst',
  'Red, blue, green and gold — every colour in two minutes',
  'A punchy dusk show that works through the entire HAC Hi-Vis colour range. Red spheres open, a rainbow wave bridge connects the halves, and green and mixed strobes close it out.',
  150,
  12000,
  10375,
  25,
  'Dusk',
  ARRAY['High energy', 'Colourful', 'Family friendly'],
  '[
    {"timeSeconds": 3,   "fireworkSlug": "fib-red",      "description": "Red sphere"},
    {"timeSeconds": 9,   "fireworkSlug": "fib-blue",     "description": "Blue sphere"},
    {"timeSeconds": 15,  "fireworkSlug": "fib-green",    "description": "Green sphere"},
    {"timeSeconds": 21,  "fireworkSlug": "fib-red",      "description": "Red sphere"},
    {"timeSeconds": 27,  "fireworkSlug": "wave-cyan",    "description": "Cyan wave"},
    {"timeSeconds": 33,  "fireworkSlug": "fib-blue",     "description": "Blue sphere"},
    {"timeSeconds": 39,  "fireworkSlug": "fib-red",      "description": "Red sphere"},
    {"timeSeconds": 45,  "fireworkSlug": "fib-green",    "description": "Green sphere"},
    {"timeSeconds": 51,  "fireworkSlug": "wave-rainbow", "description": "Rainbow wave"},
    {"timeSeconds": 57,  "fireworkSlug": "fib-blue",     "description": "Blue sphere"},
    {"timeSeconds": 63,  "fireworkSlug": "strobe-red",   "description": "Red strobe"},
    {"timeSeconds": 69,  "fireworkSlug": "fib-green",    "description": "Green sphere"},
    {"timeSeconds": 75,  "fireworkSlug": "fib-red",      "description": "Red sphere"},
    {"timeSeconds": 81,  "fireworkSlug": "wave-cyan",    "description": "Cyan wave"},
    {"timeSeconds": 87,  "fireworkSlug": "fib-blue",     "description": "Blue sphere"},
    {"timeSeconds": 93,  "fireworkSlug": "fib-green",    "description": "Green sphere"},
    {"timeSeconds": 99,  "fireworkSlug": "strobe-mixed", "description": "Mixed strobe"},
    {"timeSeconds": 105, "fireworkSlug": "fib-red",      "description": "Red sphere"},
    {"timeSeconds": 111, "fireworkSlug": "wave-rainbow", "description": "Rainbow wave"},
    {"timeSeconds": 117, "fireworkSlug": "fib-blue",     "description": "Blue sphere"},
    {"timeSeconds": 123, "fireworkSlug": "fib-green",    "description": "Green sphere"},
    {"timeSeconds": 129, "fireworkSlug": "strobe-red",   "description": "Red strobe"},
    {"timeSeconds": 135, "fireworkSlug": "wave-cyan",    "description": "Cyan wave"},
    {"timeSeconds": 141, "fireworkSlug": "strobe-mixed", "description": "Mixed strobe"},
    {"timeSeconds": 147, "fireworkSlug": "strobe-mixed", "description": "Finale burst"}
  ]'::jsonb,
  true,
  20
),

-- Show 3: Midnight Pulse — minimal atmospheric night show
(
  'midnight-pulse',
  'Midnight Pulse',
  'Sparse, cinematic moments for a dramatic night sky',
  'A two-minute show that prizes space over density. Purple waves anchor the mood, blue spheres and mini bursts punctuate the silence, and a mega bloom closes the sky.',
  120,
  18000,
  16075,
  20,
  'Night',
  ARRAY['Minimalist', 'Romantic', 'Atmospheric'],
  '[
    {"timeSeconds": 3,   "fireworkSlug": "wave-purple",  "description": "Purple wave"},
    {"timeSeconds": 9,   "fireworkSlug": "fib-mini",     "description": "Mini burst"},
    {"timeSeconds": 15,  "fireworkSlug": "wave-purple",  "description": "Purple wave"},
    {"timeSeconds": 21,  "fireworkSlug": "fib-blue",     "description": "Blue sphere"},
    {"timeSeconds": 27,  "fireworkSlug": "fib-mini",     "description": "Mini burst"},
    {"timeSeconds": 33,  "fireworkSlug": "wave-purple",  "description": "Purple wave"},
    {"timeSeconds": 39,  "fireworkSlug": "fib-mega",     "description": "Mega bloom"},
    {"timeSeconds": 45,  "fireworkSlug": "fib-mini",     "description": "Mini burst"},
    {"timeSeconds": 51,  "fireworkSlug": "wave-purple",  "description": "Purple wave"},
    {"timeSeconds": 57,  "fireworkSlug": "fib-blue",     "description": "Blue sphere"},
    {"timeSeconds": 63,  "fireworkSlug": "strobe-white", "description": "White strobe"},
    {"timeSeconds": 69,  "fireworkSlug": "fib-mini",     "description": "Mini burst"},
    {"timeSeconds": 75,  "fireworkSlug": "wave-purple",  "description": "Purple wave"},
    {"timeSeconds": 81,  "fireworkSlug": "fib-mega",     "description": "Mega bloom"},
    {"timeSeconds": 87,  "fireworkSlug": "strobe-white", "description": "White strobe"},
    {"timeSeconds": 93,  "fireworkSlug": "fib-blue",     "description": "Blue sphere"},
    {"timeSeconds": 99,  "fireworkSlug": "wave-purple",  "description": "Purple wave"},
    {"timeSeconds": 105, "fireworkSlug": "fib-mega",     "description": "Mega bloom"},
    {"timeSeconds": 111, "fireworkSlug": "strobe-white", "description": "White strobe"},
    {"timeSeconds": 116, "fireworkSlug": "strobe-mixed", "description": "Finale burst"}
  ]'::jsonb,
  true,
  30
);
