with hydrated_trail_defaults(slug, defaults_json) as (
  values
    (
      'spark-dust-trail',
      '{"burstTrail":{"version":2,"enabled":true,"preset":"sparkDust","colourMode":"star","particlesPerStar":24,"frontClump":0.35,"width":{"front":1.1,"tail":2.1,"curve":1.15},"particleSize":{"base":0.65,"headScale":1,"tailScale":0.45,"variationPercent":55},"opening":{"size":{"startPercent":100},"visibility":{"brightnessPercent":100,"particlesPercent":100,"revealPercent":24}},"closing":{"colour":{"enabled":false,"color":{"r":1,"g":0.34,"b":0.08},"fadePercent":22},"size":{"enabled":false,"endPercent":0,"shrinkPercent":22},"spreadFade":{"enabled":true,"startAngle":60,"endOpacityPercent":12}},"placement":{"headGapPercent":35},"spacing":{"curve":1,"jitterPercent":55},"lifetime":{"mode":"dynamic","percent":0.14,"baseSeconds":0.82,"variationPercent":55,"afterglowSeconds":0.1},"intensity":{"brightness":0.72,"fadeSoftness":1.3},"flicker":{"chance":0.22,"strength":0.75,"lifetimeMultiplier":0.45},"motion":{"gravity":-0.035,"drag":2.4,"inheritedVelocity":0.02,"turbulence":0.2,"driftX":0,"driftY":-0.018,"driftZ":0,"spin":0},"stops":[{"position":0,"density":1.05,"size":0.74,"sizeVariation":55,"shapeWeights":{"circle":76,"square":16,"triangle":8}},{"position":55,"density":0.55,"size":0.55,"sizeVariation":60,"shapeWeights":{"circle":82,"square":12,"triangle":6}},{"position":100,"density":0.16,"size":0.32,"sizeVariation":70,"shapeWeights":{"circle":90,"square":8,"triangle":2}}]}}'::jsonb
    ),
    (
      'solid-streaks-trail',
      '{"burstTrail":{"version":2,"enabled":true,"preset":"solidStreaks","colourMode":"gold","particlesPerStar":84,"frontClump":0.55,"width":{"front":1.35,"tail":1.35,"curve":1},"particleSize":{"base":0.95,"headScale":1,"tailScale":0.55,"variationPercent":28},"opening":{"size":{"startPercent":100},"visibility":{"brightnessPercent":100,"particlesPercent":100,"revealPercent":24}},"closing":{"colour":{"enabled":false,"color":{"r":1,"g":0.34,"b":0.08},"fadePercent":22},"size":{"enabled":false,"endPercent":0,"shrinkPercent":22},"spreadFade":{"enabled":true,"startAngle":60,"endOpacityPercent":12}},"placement":{"headGapPercent":45},"spacing":{"curve":1,"jitterPercent":22},"lifetime":{"mode":"dynamic","percent":0.18,"baseSeconds":1,"variationPercent":28,"afterglowSeconds":0.12},"intensity":{"brightness":1,"fadeSoftness":1},"flicker":{"chance":0.08,"strength":0.9,"lifetimeMultiplier":0.45},"motion":{"gravity":-0.014,"drag":1.6,"inheritedVelocity":0.02,"turbulence":0.045,"driftX":0,"driftY":-0.012,"driftZ":0,"spin":0},"stops":[{"position":0,"density":1.45,"size":1,"sizeVariation":28,"shapeWeights":{"circle":4,"square":88,"triangle":8}},{"position":32,"density":1.1,"size":0.86,"sizeVariation":30,"shapeWeights":{"circle":5,"square":86,"triangle":9}},{"position":100,"density":0.32,"size":0.48,"sizeVariation":34,"shapeWeights":{"circle":8,"square":84,"triangle":8}}]}}'::jsonb
    ),
    (
      'willow-hang-trail',
      '{"burstTrail":{"version":2,"enabled":true,"preset":"willowHang","colourMode":"gold","particlesPerStar":72,"frontClump":0.46,"width":{"front":1.15,"tail":2.2,"curve":1.6},"particleSize":{"base":0.82,"headScale":1,"tailScale":0.45,"variationPercent":34},"opening":{"size":{"startPercent":100},"visibility":{"brightnessPercent":100,"particlesPercent":100,"revealPercent":24}},"closing":{"colour":{"enabled":false,"color":{"r":1,"g":0.34,"b":0.08},"fadePercent":22},"size":{"enabled":false,"endPercent":0,"shrinkPercent":22},"spreadFade":{"enabled":true,"startAngle":60,"endOpacityPercent":12}},"placement":{"headGapPercent":55},"spacing":{"curve":1.35,"jitterPercent":24},"lifetime":{"mode":"dynamic","percent":0.32,"baseSeconds":2.25,"variationPercent":34,"afterglowSeconds":0.2},"intensity":{"brightness":0.9,"fadeSoftness":1.8},"flicker":{"chance":0.06,"strength":0.55,"lifetimeMultiplier":0.5},"motion":{"gravity":-0.12,"drag":0.85,"inheritedVelocity":0.015,"turbulence":0.06,"driftX":0,"driftY":-0.08,"driftZ":0,"spin":0},"stops":[{"position":0,"density":1.2,"size":0.86,"sizeVariation":30,"shapeWeights":{"circle":8,"square":84,"triangle":8}},{"position":48,"density":0.88,"size":0.72,"sizeVariation":36,"shapeWeights":{"circle":12,"square":78,"triangle":10}},{"position":100,"density":0.28,"size":0.38,"sizeVariation":42,"shapeWeights":{"circle":22,"square":68,"triangle":10}}]}}'::jsonb
    ),
    (
      'comet-tail-trail',
      '{"burstTrail":{"version":2,"enabled":true,"preset":"cometTail","colourMode":"starFade","particlesPerStar":96,"frontClump":0.68,"width":{"front":2.6,"tail":0.8,"curve":0.72},"particleSize":{"base":1.05,"headScale":1.15,"tailScale":0.35,"variationPercent":20},"opening":{"size":{"startPercent":100},"visibility":{"brightnessPercent":100,"particlesPercent":100,"revealPercent":24}},"closing":{"colour":{"enabled":false,"color":{"r":1,"g":0.34,"b":0.08},"fadePercent":22},"size":{"enabled":false,"endPercent":0,"shrinkPercent":22},"spreadFade":{"enabled":true,"startAngle":60,"endOpacityPercent":12}},"placement":{"headGapPercent":70},"spacing":{"curve":1.25,"jitterPercent":18},"lifetime":{"mode":"dynamic","percent":0.22,"baseSeconds":1.25,"variationPercent":24,"afterglowSeconds":0.14},"intensity":{"brightness":1.15,"fadeSoftness":0.9},"flicker":{"chance":0.04,"strength":0.65,"lifetimeMultiplier":0.45},"motion":{"gravity":-0.028,"drag":1.3,"inheritedVelocity":0.04,"turbulence":0.05,"driftX":0,"driftY":-0.018,"driftZ":0,"spin":0},"stops":[{"position":0,"density":1.65,"size":1.28,"sizeVariation":20,"shapeWeights":{"circle":6,"square":84,"triangle":10}},{"position":42,"density":0.92,"size":0.86,"sizeVariation":24,"shapeWeights":{"circle":8,"square":80,"triangle":12}},{"position":100,"density":0.22,"size":0.42,"sizeVariation":32,"shapeWeights":{"circle":18,"square":72,"triangle":10}}]}}'::jsonb
    ),
    (
      'dense-brocade-trail',
      '{"burstTrail":{"version":2,"enabled":true,"preset":"denseBrocade","colourMode":"gold","particlesPerStar":120,"frontClump":0.72,"width":{"front":3.2,"tail":2.7,"curve":0.86},"particleSize":{"base":1,"headScale":1.12,"tailScale":0.45,"variationPercent":18},"opening":{"size":{"startPercent":100},"visibility":{"brightnessPercent":100,"particlesPercent":100,"revealPercent":24}},"closing":{"colour":{"enabled":false,"color":{"r":1,"g":0.34,"b":0.08},"fadePercent":22},"size":{"enabled":false,"endPercent":0,"shrinkPercent":22},"spreadFade":{"enabled":true,"startAngle":60,"endOpacityPercent":12}},"placement":{"headGapPercent":70},"spacing":{"curve":1.4,"jitterPercent":15},"lifetime":{"mode":"dynamic","percent":0.24,"baseSeconds":1.45,"variationPercent":22,"afterglowSeconds":0.16},"intensity":{"brightness":1.15,"fadeSoftness":1.1},"flicker":{"chance":0.1,"strength":0.95,"lifetimeMultiplier":0.45},"motion":{"gravity":-0.014,"drag":1.6,"inheritedVelocity":0.018,"turbulence":0.05,"driftX":0,"driftY":-0.012,"driftZ":0,"spin":0},"stops":[{"position":0,"density":1.85,"size":1.15,"sizeVariation":22,"shapeWeights":{"circle":4,"square":88,"triangle":8}},{"position":25,"density":1.25,"size":0.92,"sizeVariation":24,"shapeWeights":{"circle":5,"square":86,"triangle":9}},{"position":70,"density":0.62,"size":0.64,"sizeVariation":30,"shapeWeights":{"circle":8,"square":82,"triangle":10}},{"position":100,"density":0.24,"size":0.42,"sizeVariation":36,"shapeWeights":{"circle":14,"square":76,"triangle":10}}]}}'::jsonb
    )
)
update public.firework_style_defaults defaults
set
  defaults_json = hydrated_trail_defaults.defaults_json,
  updated_at = now()
from hydrated_trail_defaults
where defaults.slug = hydrated_trail_defaults.slug
  and defaults.kind = 'trail'
  and (
    defaults.defaults_json #> '{burstTrail,enabled}' is null
    or defaults.defaults_json #> '{burstTrail,particlesPerStar}' is null
    or defaults.defaults_json #> '{burstTrail,stops}' is null
  );
