-- Explicit retailer operations and public readers; internal trigger functions remain revoked.
revoke all on public.range_items from public, anon, authenticated, service_role;
grant all on public.range_items to service_role;
grant select on public.range_items to authenticated;
grant insert, update on public.range_items to authenticated;
revoke all on public.store_items from public, anon, authenticated, service_role;
grant all on public.store_items to service_role;
grant select on public.store_items to authenticated;
grant insert, update on public.store_items to authenticated;
revoke all on public.stock_movements from public, anon, authenticated, service_role;
grant all on public.stock_movements to service_role;
grant select on public.stock_movements to authenticated;
revoke all on public.collections from public, anon, authenticated, service_role;
grant all on public.collections to service_role;
grant select on public.collections to authenticated;
grant insert, update on public.collections to authenticated;
revoke all on public.collection_items from public, anon, authenticated, service_role;
grant all on public.collection_items to service_role;
grant select on public.collection_items to authenticated;
grant insert, update on public.collection_items to authenticated;
grant delete on public.collection_items to authenticated;
revoke all on public.shows from public, anon, authenticated, service_role;
grant all on public.shows to service_role;
grant select on public.shows to authenticated;
grant insert (id,organisation_id,owner_id,name,origin,soundtrack_track_id,tags,share_token),
  update (name,status,soundtrack_track_id,tags,share_token,archived_at) on public.shows to authenticated;
revoke all on public.show_versions from public, anon, authenticated, service_role;
grant all on public.show_versions to service_role;
grant select on public.show_versions to authenticated;
revoke all on public.show_version_products from public, anon, authenticated, service_role;
grant all on public.show_version_products to service_role;
grant select on public.show_version_products to authenticated;
revoke all on public.campaigns from public, anon, authenticated, service_role;
grant all on public.campaigns to service_role;
grant select on public.campaigns to authenticated;
grant insert, update on public.campaigns to authenticated;
revoke all on public.qr_codes from public, anon, authenticated, service_role;
grant all on public.qr_codes to service_role;
grant select on public.qr_codes to authenticated;
grant insert on public.qr_codes to authenticated;
grant update (store_id,target_type,target_id,campaign_id,placement,label_text,status,archived_at)
  on public.qr_codes to authenticated;
revoke all on public.label_batches from public, anon, authenticated, service_role;
grant all on public.label_batches to service_role;
grant select on public.label_batches to authenticated;
grant insert on public.label_batches to authenticated;
revoke all on public.store_prices, public.show_store_status from public, anon, authenticated, service_role;
grant select on public.store_prices, public.show_store_status to authenticated, service_role;
grant usage, select on sequence public.stock_movements_id_seq to service_role;
grant execute on function private.show_access(uuid,uuid,boolean) to authenticated, service_role;
grant execute on function private.record_stock(uuid,uuid,int,text,text) to authenticated, service_role;
grant execute on function private.save_show(uuid,jsonb,int,uuid,int,uuid,text) to authenticated, service_role;
revoke all on function public.record_stock(uuid,uuid,int,text,text) from public, anon, authenticated, service_role;
grant execute on function public.record_stock(uuid,uuid,int,text,text) to authenticated, service_role;
revoke all on function public.save_show(uuid,jsonb,int,uuid,int,uuid,text) from public, anon, authenticated, service_role;
grant execute on function public.save_show(uuid,jsonb,int,uuid,int,uuid,text) to authenticated, service_role;
revoke all on function public.resolve_qr(text) from public, anon, authenticated, service_role;
grant execute on function public.resolve_qr(text), private.resolve_qr(text) to anon, authenticated, service_role;
revoke all on function public.store_page(uuid) from public, anon, authenticated, service_role;
grant execute on function public.store_page(uuid), private.store_page(uuid) to anon, authenticated, service_role;
revoke all on function public.show_for_store(uuid,uuid) from public, anon, authenticated, service_role;
grant execute on function public.show_for_store(uuid,uuid), private.show_for_store(uuid,uuid) to anon, authenticated, service_role;
grant execute on function private.cues_schema() to service_role;
grant execute on function private.label_access(uuid,uuid[],boolean) to authenticated, service_role;
