-- Explicit billing capabilities; clients receive only the authorised operations.
revoke all on public.plans from public, anon, authenticated, service_role;
grant all on public.plans to service_role;
grant select on public.plans to authenticated;
revoke all on public.billing_accounts from public, anon, authenticated, service_role;
grant all on public.billing_accounts to service_role;
grant select on public.billing_accounts to authenticated;
revoke all on public.credit_packs from public, anon, authenticated, service_role;
grant all on public.credit_packs to service_role;
grant select on public.credit_packs to authenticated;
revoke all on public.credit_prices from public, anon, authenticated, service_role;
grant all on public.credit_prices to service_role;
grant select on public.credit_prices to authenticated;
revoke all on public.credit_ledger from public, anon, authenticated, service_role;
grant all on public.credit_ledger to service_role;
grant select on public.credit_ledger to authenticated;
revoke all on public.credit_reservations from public, anon, authenticated, service_role;
grant all on public.credit_reservations to service_role;
grant select on public.credit_reservations to authenticated;
revoke all on function public.credit_balance(uuid) from public, anon, authenticated, service_role;
grant execute on function public.credit_balance(uuid) to authenticated, service_role;
revoke all on function public.grant_credits(uuid,integer,text) from public, anon, authenticated, service_role;
grant execute on function public.grant_credits(uuid,integer,text) to authenticated, service_role;
revoke all on function private.read_credit_balance(uuid) from public, anon, authenticated, service_role;
grant execute on function private.read_credit_balance(uuid) to authenticated, service_role;
revoke all on function private.grant_credits(uuid,integer,text) from public, anon, authenticated, service_role;
grant execute on function private.grant_credits(uuid,integer,text) to authenticated, service_role;
revoke all on function private.release_expired_credit_reservations() from public, anon, authenticated, service_role;
grant execute on function private.release_expired_credit_reservations() to service_role;
grant usage, select on sequence public.credit_ledger_id_seq to service_role;
