-- Explicit shopper operations; solver results, redemption and analyses are backend-owned.
revoke all on public.plan_sessions from public, anon, authenticated, service_role;
grant all on public.plan_sessions to service_role;
grant select on public.plan_sessions to authenticated;
revoke all on public.plan_candidates from public, anon, authenticated, service_role;
grant all on public.plan_candidates to service_role;
grant select on public.plan_candidates to authenticated;
revoke all on public.plan_edits from public, anon, authenticated, service_role;
grant all on public.plan_edits to service_role;
grant select on public.plan_edits to authenticated;
revoke all on public.lists from public, anon, authenticated, service_role;
grant all on public.lists to service_role;
grant select on public.lists to authenticated;
revoke all on public.list_items from public, anon, authenticated, service_role;
grant all on public.list_items to service_role;
grant select on public.list_items to authenticated;
revoke all on public.follows from public, anon, authenticated, service_role;
grant all on public.follows to service_role;
grant select on public.follows to authenticated;
revoke all on public.privacy_requests from public, anon, authenticated, service_role;
grant all on public.privacy_requests to service_role;
grant select on public.privacy_requests to authenticated;
revoke all on public.music_tracks from public, anon, authenticated, service_role;
grant all on public.music_tracks to service_role;
grant select on public.music_tracks to authenticated;
revoke all on public.music_analyses from public, anon, authenticated, service_role;
grant all on public.music_analyses to service_role;
grant select on public.music_analyses to authenticated;
grant insert (shopper_id,organisation_id,visible_to_shop,marketing_opt_in,consent_text_version), delete on public.follows to authenticated;
grant update (visible_to_shop,marketing_opt_in,consent_text_version) on public.follows to authenticated;
grant insert (id,shopper_id,kind) on public.privacy_requests to authenticated;
grant select on public.music_tracks, public.music_analyses to anon;
grant insert, update on public.music_tracks to authenticated;
grant execute on function private.owns_shopper(uuid) to authenticated, service_role;
grant execute on function private.owns_plan(uuid) to authenticated, service_role;
grant execute on function private.can_read_list(uuid) to authenticated, service_role;
grant execute on function private.can_read_music_analysis(uuid,boolean,uuid) to anon, authenticated, service_role;
revoke all on function public.start_plan_session(uuid,jsonb,text,text,uuid,timestamptz) from public, anon, authenticated, service_role;
grant execute on function public.start_plan_session(uuid,jsonb,text,text,uuid,timestamptz), private.start_plan_session(uuid,jsonb,text,text,uuid,timestamptz) to authenticated, service_role;
revoke all on function public.create_list(uuid,jsonb,text,date,uuid) from public, anon, authenticated, service_role;
grant execute on function public.create_list(uuid,jsonb,text,date,uuid), private.create_list(uuid,jsonb,text,date,uuid) to authenticated, service_role;
revoke all on function public.shop_customers(uuid) from public, anon, authenticated, service_role;
grant execute on function public.shop_customers(uuid), private.shop_customers(uuid) to authenticated, service_role;
revoke all on function public.save_music_analysis(uuid,text,jsonb,text) from public, anon, authenticated, service_role;
grant execute on function public.save_music_analysis(uuid,text,jsonb,text), private.save_music_analysis(uuid,text,jsonb,text) to service_role;
