-- Clean-slate reseed of the firework effect catalogue.
-- Generated from platform/lib/fireworks/effect-catalogue.ts by
-- scripts/seed/generate-firework-catalogue-migration.mjs. Re-run the
-- generator after editing the catalogue to refresh this file.
--
-- Upserts the calibrated set (24 effects,
-- 72 coloured firework variants) tuned to the Brocade
-- reference bar, re-maps dependent catalogue_items and multishot_fireworks that
-- still point at catalogue or legacy-migrated fireworks to the nearest
-- catalogue effect's default firework so existing show timelines keep
-- rendering. Manual, video-inferred, and LLM-generated fireworks are preserved.
-- Legacy catalogue effects and fireworks not in the catalogue are pruned after
-- those legacy dependents are re-linked.
-- retained style-default links and editor versions stay attached to their
-- upserted ids.

-- Map old effect slugs to target catalogue effect slugs. Catalogue slugs
-- map to themselves; known legacy slugs remap to the nearest catalogue
-- effect; anything unmapped falls back to 'peony'.
create temp table if not exists _effect_remap (old_slug text, target_slug text);
insert into _effect_remap (old_slug, target_slug)
  select * from (values
    ('peony', 'peony'),
    ('chrysanthemum', 'chrysanthemum'),
    ('brocade', 'brocade'),
    ('kamuro', 'kamuro'),
    ('willow', 'willow'),
    ('palm', 'palm'),
    ('ring', 'ring'),
    ('saturn', 'saturn'),
    ('crossette', 'crossette'),
    ('double_break', 'double_break'),
    ('bowtie', 'bowtie'),
    ('horsetail', 'horsetail'),
    ('comet', 'comet'),
    ('mine', 'mine'),
    ('pearls', 'pearls'),
    ('pistil', 'pistil'),
    ('nishiki', 'nishiki'),
    ('strobe', 'strobe'),
    ('crackle', 'crackle'),
    ('silverFish', 'silverFish'),
    ('waterfall', 'waterfall'),
    ('whirl', 'whirl'),
    ('roman_candle', 'roman_candle'),
    ('fountain', 'fountain')
  ) as v(old_slug, target_slug);
insert into _effect_remap (old_slug, target_slug) values
  ('silver-fish', 'silverFish'),
  ('tail', 'comet'),
  ('custom-star-mqjgvfgo', 'peony'),
  ('legacy-effect-spec', 'peony');

-- Capture dependent -> target catalogue effect slug before reseed.
create temp table if not exists _dep_effect_targets (src text, dep_id uuid, target_effect_slug text);
insert into _dep_effect_targets (src, dep_id, target_effect_slug)
  select 'catalogue_item'::text, ci.id, coalesce(r.target_slug, 'peony')
  from public.catalogue_items ci
  join public.fireworks fw on ci.firework_id = fw.id
  join public.firework_effects fe on fe.id = fw.firework_effect_id
  left join _effect_remap r on r.old_slug = fe.slug
  where ci.firework_id is not null
    and fw.source in ('catalogue', 'legacy_migrated');
insert into _dep_effect_targets (src, dep_id, target_effect_slug)
  select 'multishot_firework'::text, mf.id, coalesce(r.target_slug, 'peony')
  from public.multishot_fireworks mf
  join public.fireworks fw on mf.firework_id = fw.id
  join public.firework_effects fe on fe.id = fw.firework_effect_id
  left join _effect_remap r on r.old_slug = fe.slug
  where mf.firework_id is not null
    and fw.source in ('catalogue', 'legacy_migrated');

-- Reseed base effects (upsert by slug). multishot_fireworks.firework_id is not
-- null with on-delete restrict, so effects/fireworks are upserted in place and
-- legacy rows are pruned only after dependents are re-linked below.
insert into public.firework_effects
  (slug, name, description, family, pattern_key, model_json, sort_order, source)
values
  ('peony', 'Peony', 'Round radial burst of glowing stars without persistent trails.', 'aerial_burst', 'peony', '{"version":3,"geometry":"sphere","trailProfile":"none","renderDefaults":{"pattern":"fibonacci","geometry":"sphere","trailProfile":"none","size":115,"liftVelocity":17,"shellLife":4.2,"burst":{"speed":[2.4,4],"gravity":[-0.5,0],"life":[2.6,3.8],"flairColorMode":"bombColor"},"flair":{"enabled":false},"crackle":{"enabled":false,"probability":0,"sound":"crackle"},"strobe":{"enabled":false,"frequencyHz":12,"dutyCycle":0.45},"split":{"enabled":false,"fragments":4,"speed":1.55,"delayRatio":0.42},"sound":{"launch":true,"boom":"auto"},"mortar":{"sound":true,"smokeParticles":100},"stars":{"outer":{"enabled":true,"count":80,"burst":{"speed":[2.4,4],"gravity":[-0.5,0],"life":[2.6,3.8],"flairColorMode":"bombColor"},"head":{"visible":true,"size":170,"glowStrength":1,"glowPadding":150,"whiteCoreSizePercent":10,"whiteCoreBlurPercent":15,"coreSoftness":70,"coreBrightness":30,"coreOpacityFalloff":60,"glowSize":90,"glowSoftness":100,"glowOpacityFalloff":100,"glowBlur":45,"backgroundGlowOpacityFalloff":75,"backgroundGlowSoftness":50,"brightnessHoldPercent":40,"brightnessHoldExponent":0.8,"opening":{"colour":{"enabled":true,"color":{"r":1,"g":0.42,"b":0.08},"fadePercent":16},"size":{"enabled":false,"startPercent":35,"growPercent":18}},"closing":{"colour":{"enabled":true,"color":{"r":1,"g":0.84,"b":0.4},"fadePercent":32},"size":{"enabled":true,"endPercent":0,"shrinkPercent":55}}},"colourPattern":{"mode":"solid","axis":"vertical","count":1,"colours":[]},"burstTrail":{"preset":"none","enabled":false,"particlesPerStar":0}},"core":{"enabled":false}}}}'::jsonb, 10, 'reference'),
  ('chrysanthemum', 'Chrysanthemum', 'Round flower burst whose stars carry long visible spark trails to the tips.', 'aerial_burst', 'chrysanthemum', '{"version":3,"geometry":"sphere","trailProfile":"spark","renderDefaults":{"pattern":"fibonacci","geometry":"sphere","trailProfile":"spark","size":75,"liftVelocity":22,"shellLife":5,"burst":{"speed":[1.6,3],"gravity":[-0.7,-0.2],"life":[2,3.5],"flairColorMode":"bombColor"},"flair":{"enabled":true},"crackle":{"enabled":false,"probability":0,"sound":"crackle"},"strobe":{"enabled":false,"frequencyHz":12,"dutyCycle":0.45},"split":{"enabled":false,"fragments":4,"speed":1.55,"delayRatio":0.42},"sound":{"launch":true,"boom":"auto"},"mortar":{"sound":true,"smokeParticles":110},"stars":{"outer":{"enabled":true,"count":75,"burst":{"speed":[1.6,3],"gravity":[-0.7,-0.2],"life":[2,3.5],"flairColorMode":"bombColor"},"head":{"visible":true,"size":260,"glowStrength":1.8,"glowPadding":150,"whiteCoreSizePercent":20,"whiteCoreBlurPercent":15,"coreSoftness":55,"coreBrightness":50,"coreOpacityFalloff":60,"glowSize":90,"glowSoftness":100,"glowOpacityFalloff":100,"glowBlur":45,"backgroundGlowOpacityFalloff":75,"backgroundGlowSoftness":50,"brightnessHoldPercent":82,"brightnessHoldExponent":0.8},"colourPattern":{"mode":"solid","axis":"vertical","count":1,"colours":[]},"burstTrail":{"preset":"solidStreaks","enabled":true,"particlesPerStar":96,"width":{"front":2.4,"tail":2.4,"curve":1},"lifetime":{"percent":0.22,"baseSeconds":1.7,"afterglowSeconds":0.32},"intensity":{"brightness":1.15,"fadeSoftness":1},"motion":{"gravity":-0.02,"drag":1.4},"colourMode":"starFade"}},"core":{"enabled":false}}}}'::jsonb, 20, 'reference'),
  ('brocade', 'Brocade', 'White-gold crown with a hot lift streak, amber burst haze, and long falling brocade trails. The reference quality bar.', 'aerial_burst', 'brocade', '{"version":3,"geometry":"crown","trailProfile":"glitter","renderDefaults":{"pattern":"wave","geometry":"crown","trailProfile":"glitter","size":270,"color":{"r":1,"g":0.82,"b":0.36},"secondaryColor":{"r":1,"g":0.98,"b":0.88},"liftVelocity":12.6,"burst":{"speed":[1.45,2.85],"gravity":[-0.82,-0.34],"life":[1.15,4.95],"flairColorMode":"bombColor"},"trail":{"density":2.85,"length":2.35,"sparkle":0.62,"thickness":0.86},"flair":{"enabled":true},"crackle":{"enabled":false,"probability":0,"sound":"crackle"},"strobe":{"enabled":false,"frequencyHz":12,"dutyCycle":0.45},"split":{"enabled":false,"fragments":4,"speed":1.55,"delayRatio":0.42},"sound":{"launch":true,"boom":"light"},"mortar":{"sound":true,"smokeParticles":70},"brocade":{"streakCount":48,"trailStep":3,"tubeRadius":3.2,"headsEnabled":true,"headSize":900,"glowStrength":1.2,"greenRatio":0.5,"headColors":{"green":{"r":0.4,"g":1,"b":0.5},"red":{"r":1,"g":0.28,"b":0.32}},"palette":{"hot":{"r":1,"g":0.93,"b":0.72},"ember":{"r":1,"g":0.42,"b":0.14}}}}}'::jsonb, 30, 'reference'),
  ('kamuro', 'Kamuro', 'Dense gold-to-silver brocade crown that cascades downward in a long glittering umbrella, very long hang.', 'aerial_burst', 'kamuro', '{"version":3,"geometry":"crown","trailProfile":"glitter","renderDefaults":{"pattern":"fibonacci","geometry":"crown","trailProfile":"glitter","size":90,"liftVelocity":24,"shellLife":6,"burst":{"speed":[1.2,2.4],"gravity":[-1.1,-0.5],"life":[4.5,6.5],"flairColorMode":"bombColor"},"trail":{"density":2.6,"length":2.6,"sparkle":0.6,"thickness":0.9},"flair":{"enabled":true},"crackle":{"enabled":true,"probability":0.04,"sound":"crackle"},"strobe":{"enabled":false,"frequencyHz":12,"dutyCycle":0.45},"split":{"enabled":false,"fragments":4,"speed":1.55,"delayRatio":0.42},"sound":{"launch":true,"boom":"heavy"},"mortar":{"sound":true,"smokeParticles":90},"brocade":{"streakCount":56,"trailStep":3,"tubeRadius":3.2,"headsEnabled":true,"headSize":700,"glowStrength":2.2,"greenRatio":0.5,"headColors":{"green":{"r":1,"g":0.84,"b":0.42},"red":{"r":0.96,"g":0.97,"b":1}},"palette":{"hot":{"r":1,"g":0.93,"b":0.72},"ember":{"r":1,"g":0.42,"b":0.14}}}}}'::jsonb, 35, 'reference'),
  ('willow', 'Willow', 'Long-burning gold stars that droop and hang like weeping willow branches.', 'aerial_burst', 'willow', '{"version":3,"geometry":"weeping","trailProfile":"long_hang","renderDefaults":{"pattern":"fibonacci","geometry":"weeping","trailProfile":"long_hang","size":80,"liftVelocity":22,"shellLife":6,"burst":{"speed":[0.8,1.8],"gravity":[-1.3,-0.7],"life":[5,7],"flairColorMode":"bombColor"},"trail":{"density":2,"length":2.6,"sparkle":0.3,"thickness":0.85},"flair":{"enabled":true},"crackle":{"enabled":false,"probability":0,"sound":"crackle"},"strobe":{"enabled":false,"frequencyHz":12,"dutyCycle":0.45},"split":{"enabled":false,"fragments":4,"speed":1.55,"delayRatio":0.42},"sound":{"launch":true,"boom":"light"},"mortar":{"sound":true,"smokeParticles":120},"stars":{"outer":{"enabled":true,"count":80,"burst":{"speed":[0.8,1.8],"gravity":[-1.3,-0.7],"life":[5,7],"flairColorMode":"bombColor"},"head":{"visible":true,"size":500,"glowStrength":1.9,"glowPadding":150,"whiteCoreSizePercent":20,"whiteCoreBlurPercent":15,"coreSoftness":55,"coreBrightness":50,"coreOpacityFalloff":60,"glowSize":90,"glowSoftness":100,"glowOpacityFalloff":100,"glowBlur":45,"backgroundGlowOpacityFalloff":75,"backgroundGlowSoftness":50,"brightnessHoldPercent":82,"brightnessHoldExponent":0.8},"colourPattern":{"mode":"solid","axis":"vertical","count":1,"colours":[]},"burstTrail":{"preset":"willowHang","enabled":true,"particlesPerStar":110,"width":{"front":1.4,"tail":2.8,"curve":1.5},"lifetime":{"percent":0.42,"baseSeconds":3.2,"afterglowSeconds":0.45},"intensity":{"brightness":1.1,"fadeSoftness":1.6},"motion":{"gravity":-0.16,"drag":0.7},"colourMode":"gold"}},"core":{"enabled":false}}}}'::jsonb, 40, 'reference'),
  ('palm', 'Palm', 'A thick golden rising trunk then a sparse burst of large heavy arms that arc into fronds.', 'aerial_burst', 'palm', '{"version":3,"geometry":"radial_arms","trailProfile":"thick_tail","renderDefaults":{"pattern":"fibonacci","geometry":"radial_arms","trailProfile":"thick_tail","size":12,"liftVelocity":22,"shellLife":6,"burst":{"speed":[2.2,3.8],"gravity":[-1.2,-0.6],"life":[3,5],"flairColorMode":"bombColor"},"trail":{"density":2.2,"length":1.6,"sparkle":0.45,"thickness":1.7},"flair":{"enabled":true},"crackle":{"enabled":false,"probability":0,"sound":"crackle"},"strobe":{"enabled":false,"frequencyHz":12,"dutyCycle":0.45},"split":{"enabled":false,"fragments":4,"speed":1.55,"delayRatio":0.42},"sound":{"launch":true,"boom":"heavy"},"mortar":{"sound":true,"smokeParticles":120},"stars":{"outer":{"enabled":true,"count":12,"burst":{"speed":[2.2,3.8],"gravity":[-1.2,-0.6],"life":[3,5],"flairColorMode":"bombColor"},"head":{"visible":true,"size":600,"glowStrength":2.2,"glowPadding":150,"whiteCoreSizePercent":20,"whiteCoreBlurPercent":15,"coreSoftness":55,"coreBrightness":50,"coreOpacityFalloff":60,"glowSize":90,"glowSoftness":100,"glowOpacityFalloff":100,"glowBlur":45,"backgroundGlowOpacityFalloff":75,"backgroundGlowSoftness":50,"brightnessHoldPercent":82,"brightnessHoldExponent":0.8},"colourPattern":{"mode":"solid","axis":"vertical","count":1,"colours":[]},"burstTrail":{"preset":"cometTail","enabled":true,"particlesPerStar":120,"width":{"front":3.2,"tail":1,"curve":0.7},"lifetime":{"percent":0.24,"baseSeconds":1.5,"afterglowSeconds":0.25},"intensity":{"brightness":1.25,"fadeSoftness":0.9},"motion":{"gravity":-0.03,"drag":1.3},"colourMode":"gold"}},"core":{"enabled":false}}}}'::jsonb, 50, 'reference'),
  ('ring', 'Ring', 'A perfectly symmetrical halo of stars expanding as a flat tilted circle.', 'aerial_burst', 'ring', '{"version":3,"geometry":"ring","trailProfile":"none","renderDefaults":{"pattern":"fibonacci","geometry":"ring","trailProfile":"none","size":60,"liftVelocity":22,"shellLife":3.2,"burst":{"speed":[1.4,1.9],"gravity":[-0.15,0.05],"life":[1.8,2.6],"flairColorMode":"bombColor"},"flair":{"enabled":false},"crackle":{"enabled":false,"probability":0,"sound":"crackle"},"strobe":{"enabled":false,"frequencyHz":12,"dutyCycle":0.45},"split":{"enabled":false,"fragments":4,"speed":1.55,"delayRatio":0.42},"sound":{"launch":true,"boom":"light"},"mortar":{"sound":true,"smokeParticles":95},"stars":{"outer":{"enabled":true,"count":60,"burst":{"speed":[1.4,1.9],"gravity":[-0.15,0.05],"life":[1.8,2.6],"flairColorMode":"bombColor"},"head":{"visible":true,"size":200,"glowStrength":1.6,"glowPadding":150,"whiteCoreSizePercent":20,"whiteCoreBlurPercent":15,"coreSoftness":55,"coreBrightness":50,"coreOpacityFalloff":60,"glowSize":90,"glowSoftness":100,"glowOpacityFalloff":100,"glowBlur":45,"backgroundGlowOpacityFalloff":75,"backgroundGlowSoftness":50,"brightnessHoldPercent":82,"brightnessHoldExponent":0.8},"colourPattern":{"mode":"solid","axis":"vertical","count":1,"colours":[]},"burstTrail":{"preset":"none","enabled":false,"particlesPerStar":0}},"core":{"enabled":false}}}}'::jsonb, 60, 'reference'),
  ('saturn', 'Saturn', 'A central peony planet core framed by a separate equatorial ring of stars.', 'aerial_burst', 'saturn', '{"version":3,"geometry":"ring","trailProfile":"none","renderDefaults":{"pattern":"fibonacci","geometry":"ring","trailProfile":"none","size":65,"liftVelocity":21,"shellLife":5,"burst":{"speed":[1,2.8],"gravity":[-0.3,0],"life":[1.6,3],"flairColorMode":"bombColor"},"flair":{"enabled":false},"crackle":{"enabled":false,"probability":0,"sound":"crackle"},"strobe":{"enabled":false,"frequencyHz":12,"dutyCycle":0.45},"split":{"enabled":false,"fragments":4,"speed":1.55,"delayRatio":0.42},"sound":{"launch":true,"boom":"auto"},"mortar":{"sound":true,"smokeParticles":100},"stars":{"outer":{"enabled":true,"count":65,"burst":{"speed":[1,2.8],"gravity":[-0.3,0],"life":[1.6,3],"flairColorMode":"bombColor"},"head":{"visible":true,"size":200,"glowStrength":1.6,"glowPadding":150,"whiteCoreSizePercent":20,"whiteCoreBlurPercent":15,"coreSoftness":55,"coreBrightness":50,"coreOpacityFalloff":60,"glowSize":90,"glowSoftness":100,"glowOpacityFalloff":100,"glowBlur":45,"backgroundGlowOpacityFalloff":75,"backgroundGlowSoftness":50,"brightnessHoldPercent":82,"brightnessHoldExponent":0.8},"colourPattern":{"mode":"solid","axis":"vertical","count":1,"colours":[]},"burstTrail":{"preset":"none","enabled":false,"particlesPerStar":0}},"core":{"enabled":true,"count":1,"burst":{"speed":[0,0],"gravity":[0,0],"life":[1.6,3],"flairColorMode":"bombColor"},"head":{"visible":true,"size":560,"glowStrength":1.8,"glowPadding":150,"whiteCoreSizePercent":20,"whiteCoreBlurPercent":15,"coreSoftness":55,"coreBrightness":50,"coreOpacityFalloff":60,"glowSize":90,"glowSoftness":100,"glowOpacityFalloff":100,"glowBlur":45,"backgroundGlowOpacityFalloff":75,"backgroundGlowSoftness":50,"brightnessHoldPercent":82,"brightnessHoldExponent":0.8},"colourPattern":{"mode":"solid","axis":"vertical","count":1,"colours":[]},"burstTrail":{"preset":"none","enabled":false,"particlesPerStar":0}}}}}'::jsonb, 65, 'reference'),
  ('crossette', 'Crossette', 'Large comet stars that radiate outward then fracture mid-flight into crossing fragments.', 'aerial_burst', 'crossette', '{"version":3,"geometry":"split_cross","trailProfile":"thick_tail","renderDefaults":{"pattern":"fibonacci","geometry":"split_cross","trailProfile":"thick_tail","size":40,"liftVelocity":20,"shellLife":3,"burst":{"speed":[1.6,2.4],"gravity":[-0.3,0],"life":[1.6,2.4],"flairColorMode":"bombColor"},"flair":{"enabled":true},"crackle":{"enabled":false,"probability":0,"sound":"crackle"},"strobe":{"enabled":false,"frequencyHz":12,"dutyCycle":0.45},"split":{"enabled":true,"fragments":4,"speed":1.8,"delayRatio":0.55},"sound":{"launch":true,"boom":"light"},"mortar":{"sound":true,"smokeParticles":110},"stars":{"outer":{"enabled":true,"count":40,"burst":{"speed":[1.6,2.4],"gravity":[-0.3,0],"life":[1.6,2.4],"flairColorMode":"bombColor"},"head":{"visible":true,"size":220,"glowStrength":1.5,"glowPadding":150,"whiteCoreSizePercent":20,"whiteCoreBlurPercent":15,"coreSoftness":55,"coreBrightness":50,"coreOpacityFalloff":60,"glowSize":90,"glowSoftness":100,"glowOpacityFalloff":100,"glowBlur":45,"backgroundGlowOpacityFalloff":75,"backgroundGlowSoftness":50,"brightnessHoldPercent":82,"brightnessHoldExponent":0.8},"colourPattern":{"mode":"solid","axis":"vertical","count":1,"colours":[]},"burstTrail":{"preset":"cometTail","enabled":true,"particlesPerStar":90,"width":{"front":3.2,"tail":1,"curve":0.7},"lifetime":{"percent":0.24,"baseSeconds":1.5,"afterglowSeconds":0.25},"intensity":{"brightness":1.25,"fadeSoftness":0.9},"motion":{"gravity":-0.03,"drag":1.3},"colourMode":"starFade"}},"core":{"enabled":false}}}}'::jsonb, 70, 'reference'),
  ('double_break', 'Double Break', 'A shell that breaks, then breaks again into a second cloud of contrasting fragments.', 'aerial_burst', 'double_break', '{"version":3,"geometry":"split_cross","trailProfile":"spark","renderDefaults":{"pattern":"fibonacci","geometry":"split_cross","trailProfile":"spark","size":70,"liftVelocity":26,"shellLife":7,"burst":{"speed":[1.4,2.8],"gravity":[-0.6,-0.1],"life":[1.4,2.6],"flairColorMode":"bombColor"},"flair":{"enabled":true},"crackle":{"enabled":false,"probability":0,"sound":"crackle"},"strobe":{"enabled":false,"frequencyHz":12,"dutyCycle":0.45},"split":{"enabled":true,"fragments":6,"speed":2.2,"delayRatio":0.58},"sound":{"launch":true,"boom":"heavy"},"mortar":{"sound":true,"smokeParticles":120},"stars":{"outer":{"enabled":true,"count":70,"burst":{"speed":[1.4,2.8],"gravity":[-0.6,-0.1],"life":[1.4,2.6],"flairColorMode":"bombColor"},"head":{"visible":true,"size":240,"glowStrength":1.7,"glowPadding":150,"whiteCoreSizePercent":20,"whiteCoreBlurPercent":15,"coreSoftness":55,"coreBrightness":50,"coreOpacityFalloff":60,"glowSize":90,"glowSoftness":100,"glowOpacityFalloff":100,"glowBlur":45,"backgroundGlowOpacityFalloff":75,"backgroundGlowSoftness":50,"brightnessHoldPercent":82,"brightnessHoldExponent":0.8},"colourPattern":{"mode":"solid","axis":"vertical","count":1,"colours":[]},"burstTrail":{"preset":"solidStreaks","enabled":true,"particlesPerStar":96,"width":{"front":2.4,"tail":2.4,"curve":1},"lifetime":{"percent":0.22,"baseSeconds":1.7,"afterglowSeconds":0.32},"intensity":{"brightness":1.15,"fadeSoftness":1},"motion":{"gravity":-0.02,"drag":1.4},"colourMode":"starFade"}},"core":{"enabled":false}}}}'::jsonb, 75, 'reference'),
  ('bowtie', 'Bow Tie', 'Two opposed lobes fired in a flat plane, a cross or figure-eight shell.', 'aerial_burst', 'bowtie', '{"version":3,"geometry":"bowtie","trailProfile":"spark","renderDefaults":{"pattern":"fibonacci","geometry":"bowtie","trailProfile":"spark","size":32,"liftVelocity":20,"shellLife":5,"burst":{"speed":[1.8,3.4],"gravity":[-0.6,-0.1],"life":[1.6,3],"flairColorMode":"bombColor"},"flair":{"enabled":true},"crackle":{"enabled":false,"probability":0,"sound":"crackle"},"strobe":{"enabled":false,"frequencyHz":12,"dutyCycle":0.45},"split":{"enabled":true,"fragments":4,"speed":1.8,"delayRatio":0.45},"sound":{"launch":true,"boom":"light"},"mortar":{"sound":true,"smokeParticles":100},"stars":{"outer":{"enabled":true,"count":32,"burst":{"speed":[1.8,3.4],"gravity":[-0.6,-0.1],"life":[1.6,3],"flairColorMode":"bombColor"},"head":{"visible":true,"size":300,"glowStrength":1.8,"glowPadding":150,"whiteCoreSizePercent":20,"whiteCoreBlurPercent":15,"coreSoftness":55,"coreBrightness":50,"coreOpacityFalloff":60,"glowSize":90,"glowSoftness":100,"glowOpacityFalloff":100,"glowBlur":45,"backgroundGlowOpacityFalloff":75,"backgroundGlowSoftness":50,"brightnessHoldPercent":82,"brightnessHoldExponent":0.8},"colourPattern":{"mode":"solid","axis":"vertical","count":1,"colours":[]},"burstTrail":{"preset":"solidStreaks","enabled":true,"particlesPerStar":90,"width":{"front":2.4,"tail":2.4,"curve":1},"lifetime":{"percent":0.22,"baseSeconds":1.7,"afterglowSeconds":0.32},"intensity":{"brightness":1.15,"fadeSoftness":1},"motion":{"gravity":-0.02,"drag":1.4},"colourMode":"starFade"}},"core":{"enabled":false}}}}'::jsonb, 78, 'reference'),
  ('horsetail', 'Horsetail', 'A directional break whose heavy tailed stars travel only a short distance then cascade downward.', 'aerial_burst', 'horsetail', '{"version":3,"geometry":"falling_tail","trailProfile":"waterfall","renderDefaults":{"pattern":"fibonacci","geometry":"falling_tail","trailProfile":"waterfall","size":50,"liftVelocity":18,"shellLife":6,"burst":{"speed":[0.6,1.4],"gravity":[-1.5,-1],"life":[4,6.5],"flairColorMode":"bombColor"},"trail":{"density":1.8,"length":2.6,"sparkle":0.3,"thickness":0.9},"flair":{"enabled":true},"crackle":{"enabled":true,"probability":0.05,"sound":"crackle"},"strobe":{"enabled":false,"frequencyHz":12,"dutyCycle":0.45},"split":{"enabled":false,"fragments":4,"speed":1.55,"delayRatio":0.42},"sound":{"launch":true,"boom":"light"},"mortar":{"sound":true,"smokeParticles":100},"stars":{"outer":{"enabled":true,"count":50,"burst":{"speed":[0.6,1.4],"gravity":[-1.5,-1],"life":[4,6.5],"flairColorMode":"bombColor"},"head":{"visible":true,"size":400,"glowStrength":1.8,"glowPadding":150,"whiteCoreSizePercent":20,"whiteCoreBlurPercent":15,"coreSoftness":55,"coreBrightness":50,"coreOpacityFalloff":60,"glowSize":90,"glowSoftness":100,"glowOpacityFalloff":100,"glowBlur":45,"backgroundGlowOpacityFalloff":75,"backgroundGlowSoftness":50,"brightnessHoldPercent":82,"brightnessHoldExponent":0.8},"colourPattern":{"mode":"solid","axis":"vertical","count":1,"colours":[]},"burstTrail":{"preset":"willowHang","enabled":true,"particlesPerStar":96,"width":{"front":1.4,"tail":2.8,"curve":1.5},"lifetime":{"percent":0.34,"baseSeconds":2.7,"afterglowSeconds":0.45},"intensity":{"brightness":0.95,"fadeSoftness":1.6},"motion":{"gravity":-0.12,"drag":0.8},"colourMode":"gold"}},"core":{"enabled":false}}}}'::jsonb, 80, 'reference'),
  ('comet', 'Comet', 'A single large bright tailed star launched skyward leaving a long thick spark trail.', 'ascending', 'comet', '{"version":3,"geometry":"single_tail","trailProfile":"thick_tail","renderDefaults":{"pattern":"fibonacci","geometry":"single_tail","trailProfile":"thick_tail","size":6,"liftVelocity":30,"shellLife":8,"burst":{"speed":[0.4,0.8],"gravity":[-0.2,0.1],"life":[3,5],"flairColorMode":"bombColor"},"trail":{"density":2.4,"length":1.6,"sparkle":0.5,"thickness":1.8},"flair":{"enabled":true},"crackle":{"enabled":false,"probability":0,"sound":"crackle"},"strobe":{"enabled":false,"frequencyHz":12,"dutyCycle":0.45},"split":{"enabled":false,"fragments":4,"speed":1.55,"delayRatio":0.42},"sound":{"launch":true,"boom":"none"},"mortar":{"sound":true,"smokeParticles":65},"stars":{"outer":{"enabled":true,"count":6,"burst":{"speed":[0.4,0.8],"gravity":[-0.2,0.1],"life":[3,5],"flairColorMode":"bombColor"},"head":{"visible":true,"size":800,"glowStrength":2.6,"glowPadding":150,"whiteCoreSizePercent":20,"whiteCoreBlurPercent":15,"coreSoftness":55,"coreBrightness":50,"coreOpacityFalloff":60,"glowSize":90,"glowSoftness":100,"glowOpacityFalloff":100,"glowBlur":45,"backgroundGlowOpacityFalloff":75,"backgroundGlowSoftness":50,"brightnessHoldPercent":82,"brightnessHoldExponent":0.8},"colourPattern":{"mode":"solid","axis":"vertical","count":1,"colours":[]},"burstTrail":{"preset":"cometTail","enabled":true,"particlesPerStar":120,"width":{"front":3.2,"tail":1,"curve":0.7},"lifetime":{"percent":0.24,"baseSeconds":1.5,"afterglowSeconds":0.25},"intensity":{"brightness":1.25,"fadeSoftness":0.9},"motion":{"gravity":-0.03,"drag":1.3},"colourMode":"starFade"}},"core":{"enabled":false}}}}'::jsonb, 90, 'reference'),
  ('mine', 'Mine', 'A near-instantaneous upward blast of stars from ground level forming a wide cone plume.', 'ground', 'mine', '{"version":3,"geometry":"upward_fan","trailProfile":"glitter","renderDefaults":{"pattern":"fibonacci","geometry":"upward_fan","trailProfile":"glitter","size":70,"liftVelocity":16,"shellLife":8,"burst":{"speed":[1.8,3.2],"gravity":[-1.2,-0.6],"life":[1,1.8],"flairColorMode":"mixed"},"flair":{"enabled":true},"crackle":{"enabled":true,"probability":0.08,"sound":"lightBoom"},"strobe":{"enabled":false,"frequencyHz":12,"dutyCycle":0.45},"split":{"enabled":false,"fragments":4,"speed":1.55,"delayRatio":0.42},"sound":{"launch":true,"boom":"light"},"mortar":{"sound":true,"smokeParticles":80},"stars":{"outer":{"enabled":true,"count":70,"burst":{"speed":[1.8,3.2],"gravity":[-1.2,-0.6],"life":[1,1.8],"flairColorMode":"bombColor"},"head":{"visible":true,"size":160,"glowStrength":1.4,"glowPadding":150,"whiteCoreSizePercent":20,"whiteCoreBlurPercent":15,"coreSoftness":55,"coreBrightness":50,"coreOpacityFalloff":60,"glowSize":90,"glowSoftness":100,"glowOpacityFalloff":100,"glowBlur":45,"backgroundGlowOpacityFalloff":75,"backgroundGlowSoftness":50,"brightnessHoldPercent":82,"brightnessHoldExponent":0.8},"colourPattern":{"mode":"solid","axis":"vertical","count":1,"colours":[]},"burstTrail":{"preset":"cometTail","enabled":true,"particlesPerStar":60,"width":{"front":3.2,"tail":1,"curve":0.7},"lifetime":{"percent":0.24,"baseSeconds":1.5,"afterglowSeconds":0.25},"intensity":{"brightness":1.25,"fadeSoftness":0.9},"motion":{"gravity":-0.03,"drag":1.3},"colourMode":"starFade"}},"core":{"enabled":false}}}}'::jsonb, 100, 'reference'),
  ('pearls', 'Pearls', 'Large slow-burning stars arranged in a ring, each a glowing pearl.', 'aerial_burst', 'pearls', '{"version":3,"geometry":"pearls","trailProfile":"pearls","renderDefaults":{"pattern":"fibonacci","geometry":"pearls","trailProfile":"pearls","size":60,"liftVelocity":22,"shellLife":4,"burst":{"speed":[1,2],"gravity":[-0.4,0],"life":[1.6,3.6],"flairColorMode":"bombColor"},"flair":{"enabled":false},"crackle":{"enabled":false,"probability":0,"sound":"crackle"},"strobe":{"enabled":false,"frequencyHz":12,"dutyCycle":0.45},"split":{"enabled":false,"fragments":4,"speed":1.55,"delayRatio":0.42},"sound":{"launch":true,"boom":"light"},"mortar":{"sound":true,"smokeParticles":95},"stars":{"outer":{"enabled":true,"count":60,"burst":{"speed":[1,2],"gravity":[-0.4,0],"life":[1.6,3.6],"flairColorMode":"bombColor"},"head":{"visible":true,"size":430,"glowStrength":1.6,"glowPadding":150,"whiteCoreSizePercent":20,"whiteCoreBlurPercent":15,"coreSoftness":55,"coreBrightness":50,"coreOpacityFalloff":60,"glowSize":90,"glowSoftness":100,"glowOpacityFalloff":100,"glowBlur":45,"backgroundGlowOpacityFalloff":75,"backgroundGlowSoftness":50,"brightnessHoldPercent":82,"brightnessHoldExponent":0.8},"colourPattern":{"mode":"solid","axis":"vertical","count":1,"colours":[]},"burstTrail":{"preset":"sparkDust","enabled":true,"particlesPerStar":24,"width":{"front":1.5,"tail":2.6,"curve":1.2},"lifetime":{"percent":0.18,"baseSeconds":1.1,"afterglowSeconds":0.18},"intensity":{"brightness":0.95,"fadeSoftness":1.3},"motion":{"gravity":-0.04,"drag":2.1},"colourMode":"star"}},"core":{"enabled":false}}}}'::jsonb, 105, 'reference'),
  ('pistil', 'Pistil', 'A coloured outer burst around a contrasting glowing central core, two concentric colour layers.', 'aerial_burst', 'pistil', '{"version":3,"geometry":"sphere","trailProfile":"spark","renderDefaults":{"pattern":"fibonacci","geometry":"sphere","trailProfile":"spark","size":60,"liftVelocity":20,"shellLife":5,"burst":{"speed":[0.8,2.6],"gravity":[-0.4,0],"life":[1.4,2.6],"flairColorMode":"bombColor"},"flair":{"enabled":true},"crackle":{"enabled":false,"probability":0,"sound":"crackle"},"strobe":{"enabled":false,"frequencyHz":12,"dutyCycle":0.45},"split":{"enabled":false,"fragments":4,"speed":1.55,"delayRatio":0.42},"sound":{"launch":true,"boom":"auto"},"mortar":{"sound":true,"smokeParticles":105},"stars":{"outer":{"enabled":true,"count":60,"burst":{"speed":[1.4,2.6],"gravity":[-0.4,0],"life":[1.4,2.6],"flairColorMode":"bombColor"},"head":{"visible":true,"size":200,"glowStrength":1.5,"glowPadding":150,"whiteCoreSizePercent":20,"whiteCoreBlurPercent":15,"coreSoftness":55,"coreBrightness":50,"coreOpacityFalloff":60,"glowSize":90,"glowSoftness":100,"glowOpacityFalloff":100,"glowBlur":45,"backgroundGlowOpacityFalloff":75,"backgroundGlowSoftness":50,"brightnessHoldPercent":82,"brightnessHoldExponent":0.8},"colourPattern":{"mode":"solid","axis":"vertical","count":1,"colours":[]},"burstTrail":{"preset":"sparkDust","enabled":true,"particlesPerStar":56,"width":{"front":1.5,"tail":2.6,"curve":1.2},"lifetime":{"percent":0.18,"baseSeconds":1.1,"afterglowSeconds":0.18},"intensity":{"brightness":0.95,"fadeSoftness":1.3},"motion":{"gravity":-0.04,"drag":2.1},"colourMode":"starFade"}},"core":{"enabled":true,"count":30,"burst":{"speed":[0.4,1],"gravity":[-0.4,0],"life":[1,2.2],"flairColorMode":"bombColor"},"head":{"visible":true,"size":320,"glowStrength":1.7,"glowPadding":150,"whiteCoreSizePercent":20,"whiteCoreBlurPercent":15,"coreSoftness":55,"coreBrightness":50,"coreOpacityFalloff":60,"glowSize":90,"glowSoftness":100,"glowOpacityFalloff":100,"glowBlur":45,"backgroundGlowOpacityFalloff":75,"backgroundGlowSoftness":50,"brightnessHoldPercent":82,"brightnessHoldExponent":0.8},"colourPattern":{"mode":"solid","axis":"vertical","count":1,"colours":[]},"burstTrail":{"preset":"none","enabled":false,"particlesPerStar":0}}}}}'::jsonb, 108, 'reference'),
  ('nishiki', 'Nishiki', 'A brocade-style trailing crown threaded with a contrasting coloured pistil core (diadem).', 'aerial_burst', 'nishiki', '{"version":3,"geometry":"sphere","trailProfile":"glitter","renderDefaults":{"pattern":"fibonacci","geometry":"sphere","trailProfile":"glitter","size":82,"liftVelocity":23,"shellLife":6,"burst":{"speed":[1.1,2.3],"gravity":[-1,-0.4],"life":[4,6],"flairColorMode":"bombColor"},"trail":{"density":2.4,"length":2.2,"sparkle":0.6,"thickness":1},"flair":{"enabled":true},"crackle":{"enabled":true,"probability":0.05,"sound":"crackle"},"strobe":{"enabled":false,"frequencyHz":12,"dutyCycle":0.45},"split":{"enabled":false,"fragments":4,"speed":1.55,"delayRatio":0.42},"sound":{"launch":true,"boom":"heavy"},"mortar":{"sound":true,"smokeParticles":100},"stars":{"outer":{"enabled":true,"count":82,"burst":{"speed":[1.1,2.3],"gravity":[-1,-0.4],"life":[4,6],"flairColorMode":"bombColor"},"head":{"visible":true,"size":480,"glowStrength":2,"glowPadding":150,"whiteCoreSizePercent":20,"whiteCoreBlurPercent":15,"coreSoftness":55,"coreBrightness":50,"coreOpacityFalloff":60,"glowSize":90,"glowSoftness":100,"glowOpacityFalloff":100,"glowBlur":45,"backgroundGlowOpacityFalloff":75,"backgroundGlowSoftness":50,"brightnessHoldPercent":82,"brightnessHoldExponent":0.8},"colourPattern":{"mode":"solid","axis":"vertical","count":1,"colours":[]},"burstTrail":{"preset":"solidStreaks","enabled":true,"particlesPerStar":120,"width":{"front":2.4,"tail":2.4,"curve":1},"lifetime":{"percent":0.22,"baseSeconds":1.7,"afterglowSeconds":0.32},"intensity":{"brightness":1.15,"fadeSoftness":1},"motion":{"gravity":-0.02,"drag":1.4},"colourMode":"gold"}},"core":{"enabled":true,"count":24,"burst":{"speed":[0.5,1],"gravity":[-0.9,-0.2],"life":[1,2.6],"flairColorMode":"bombColor"},"head":{"visible":true,"size":400,"glowStrength":1.7,"glowPadding":150,"whiteCoreSizePercent":20,"whiteCoreBlurPercent":15,"coreSoftness":55,"coreBrightness":50,"coreOpacityFalloff":60,"glowSize":90,"glowSoftness":100,"glowOpacityFalloff":100,"glowBlur":45,"backgroundGlowOpacityFalloff":75,"backgroundGlowSoftness":50,"brightnessHoldPercent":82,"brightnessHoldExponent":0.8},"colourPattern":{"mode":"solid","axis":"vertical","count":1,"colours":[]},"burstTrail":{"preset":"none","enabled":false,"particlesPerStar":0}}}}}'::jsonb, 110, 'reference'),
  ('strobe', 'Strobe', 'A spherical field of stars that oscillate between dark smoulder and sharp bright flashes.', 'aerial_burst', 'strobe', '{"version":3,"geometry":"sphere","trailProfile":"blink","renderDefaults":{"pattern":"strobe","geometry":"sphere","trailProfile":"blink","size":70,"liftVelocity":20,"shellLife":3,"burst":{"speed":[1,1.8],"gravity":[-0.4,0],"life":[2.5,4],"flairColorMode":"mixed"},"flair":{"enabled":true},"crackle":{"enabled":false,"probability":0,"sound":"crackle"},"strobe":{"enabled":true,"frequencyHz":8,"dutyCycle":0.35},"split":{"enabled":false,"fragments":4,"speed":1.55,"delayRatio":0.42},"sound":{"launch":true,"boom":"light"},"mortar":{"sound":true,"smokeParticles":120},"stars":{"outer":{"enabled":true,"count":70,"burst":{"speed":[1,1.8],"gravity":[-0.4,0],"life":[2.5,4],"flairColorMode":"bombColor"},"head":{"visible":true,"size":200,"glowStrength":1.4,"glowPadding":150,"whiteCoreSizePercent":20,"whiteCoreBlurPercent":15,"coreSoftness":55,"coreBrightness":50,"coreOpacityFalloff":60,"glowSize":90,"glowSoftness":100,"glowOpacityFalloff":100,"glowBlur":45,"backgroundGlowOpacityFalloff":75,"backgroundGlowSoftness":50,"brightnessHoldPercent":82,"brightnessHoldExponent":0.8},"colourPattern":{"mode":"solid","axis":"vertical","count":1,"colours":[]},"burstTrail":{"preset":"sparkDust","enabled":true,"particlesPerStar":32,"width":{"front":1.5,"tail":2.6,"curve":1.2},"lifetime":{"percent":0.18,"baseSeconds":1.1,"afterglowSeconds":0.18},"intensity":{"brightness":0.95,"fadeSoftness":1.3},"motion":{"gravity":-0.04,"drag":2.1},"colourMode":"star"}},"core":{"enabled":false}}}}'::jsonb, 115, 'reference'),
  ('crackle', 'Crackle', 'A dense cloud of small pellets that pop in rapid succession with sharp bright flashes.', 'noise', 'crackle', '{"version":3,"geometry":"fragment_cloud","trailProfile":"crackle","renderDefaults":{"pattern":"fibonacci","geometry":"fragment_cloud","trailProfile":"crackle","size":80,"liftVelocity":18,"shellLife":2.8,"burst":{"speed":[1.2,2.2],"gravity":[-0.5,-0.1],"life":[1.2,2.2],"flairColorMode":"mixed"},"flair":{"enabled":true},"crackle":{"enabled":true,"probability":0.12,"sound":"crackle"},"strobe":{"enabled":false,"frequencyHz":12,"dutyCycle":0.45},"split":{"enabled":false,"fragments":4,"speed":1.55,"delayRatio":0.42},"sound":{"launch":true,"boom":"light"},"mortar":{"sound":true,"smokeParticles":130},"stars":{"outer":{"enabled":true,"count":80,"burst":{"speed":[1.2,2.2],"gravity":[-0.5,-0.1],"life":[1.2,2.2],"flairColorMode":"bombColor"},"head":{"visible":true,"size":140,"glowStrength":1.4,"glowPadding":150,"whiteCoreSizePercent":20,"whiteCoreBlurPercent":15,"coreSoftness":55,"coreBrightness":50,"coreOpacityFalloff":60,"glowSize":90,"glowSoftness":100,"glowOpacityFalloff":100,"glowBlur":45,"backgroundGlowOpacityFalloff":75,"backgroundGlowSoftness":50,"brightnessHoldPercent":82,"brightnessHoldExponent":0.8},"colourPattern":{"mode":"solid","axis":"vertical","count":1,"colours":[]},"burstTrail":{"preset":"sparkDust","enabled":true,"particlesPerStar":48,"width":{"front":1.5,"tail":2.6,"curve":1.2},"lifetime":{"percent":0.18,"baseSeconds":1.1,"afterglowSeconds":0.18},"intensity":{"brightness":0.95,"fadeSoftness":1.3},"motion":{"gravity":-0.04,"drag":2.1},"colourMode":"starFade"}},"core":{"enabled":false}}}}'::jsonb, 120, 'reference'),
  ('silverFish', 'Silver Fish', 'A swarm of self-propelled silver micro-stars that dart and swim through the sky like fish.', 'aerial_burst', 'silverFish', '{"version":3,"geometry":"fish","trailProfile":"fish","renderDefaults":{"pattern":"fibonacci","geometry":"fish","trailProfile":"fish","size":50,"liftVelocity":18,"shellLife":3,"burst":{"speed":[1.2,2.5],"gravity":[-0.2,0.1],"life":[1.8,3],"flairColorMode":"mixed"},"flair":{"enabled":true},"crackle":{"enabled":true,"probability":0.06,"sound":"crackle"},"strobe":{"enabled":false,"frequencyHz":12,"dutyCycle":0.45},"split":{"enabled":false,"fragments":4,"speed":1.55,"delayRatio":0.42},"sound":{"launch":true,"boom":"light"},"mortar":{"sound":true,"smokeParticles":100},"stars":{"outer":{"enabled":true,"count":50,"burst":{"speed":[1.2,2.5],"gravity":[-0.2,0.1],"life":[1.8,3],"flairColorMode":"bombColor"},"head":{"visible":true,"size":170,"glowStrength":1.2,"glowPadding":150,"whiteCoreSizePercent":20,"whiteCoreBlurPercent":15,"coreSoftness":55,"coreBrightness":50,"coreOpacityFalloff":60,"glowSize":90,"glowSoftness":100,"glowOpacityFalloff":100,"glowBlur":45,"backgroundGlowOpacityFalloff":75,"backgroundGlowSoftness":50,"brightnessHoldPercent":82,"brightnessHoldExponent":0.8},"colourPattern":{"mode":"solid","axis":"vertical","count":1,"colours":[]},"burstTrail":{"preset":"sparkDust","enabled":true,"particlesPerStar":36,"width":{"front":1.5,"tail":2.6,"curve":1.2},"lifetime":{"percent":0.18,"baseSeconds":1.1,"afterglowSeconds":0.18},"intensity":{"brightness":0.95,"fadeSoftness":1.3},"motion":{"gravity":-0.04,"drag":2.1},"colourMode":"silver"}},"core":{"enabled":false}}}}'::jsonb, 125, 'reference'),
  ('waterfall', 'Waterfall', 'Trailing stars that spread wide then cascade slowly downward like a shimmering gold curtain.', 'aerial_burst', 'waterfall', '{"version":3,"geometry":"waterfall","trailProfile":"waterfall","renderDefaults":{"pattern":"fibonacci","geometry":"waterfall","trailProfile":"waterfall","size":80,"liftVelocity":18,"shellLife":3,"burst":{"speed":[0.6,1.2],"gravity":[-1.5,-1],"life":[3.5,6],"flairColorMode":"bombColor"},"trail":{"density":2.2,"length":2.8,"sparkle":0.22,"thickness":0.85},"flair":{"enabled":true},"crackle":{"enabled":false,"probability":0,"sound":"crackle"},"strobe":{"enabled":false,"frequencyHz":12,"dutyCycle":0.45},"split":{"enabled":false,"fragments":4,"speed":1.55,"delayRatio":0.42},"sound":{"launch":true,"boom":"light"},"mortar":{"sound":true,"smokeParticles":100},"stars":{"outer":{"enabled":true,"count":80,"burst":{"speed":[0.6,1.2],"gravity":[-1.5,-1],"life":[3.5,6],"flairColorMode":"bombColor"},"head":{"visible":true,"size":120,"glowStrength":0.9,"glowPadding":150,"whiteCoreSizePercent":20,"whiteCoreBlurPercent":15,"coreSoftness":55,"coreBrightness":50,"coreOpacityFalloff":60,"glowSize":90,"glowSoftness":100,"glowOpacityFalloff":100,"glowBlur":45,"backgroundGlowOpacityFalloff":75,"backgroundGlowSoftness":50,"brightnessHoldPercent":82,"brightnessHoldExponent":0.8},"colourPattern":{"mode":"solid","axis":"vertical","count":1,"colours":[]},"burstTrail":{"preset":"willowHang","enabled":true,"particlesPerStar":96,"width":{"front":1.4,"tail":2.8,"curve":1.5},"lifetime":{"percent":0.34,"baseSeconds":2.7,"afterglowSeconds":0.45},"intensity":{"brightness":0.95,"fadeSoftness":1.6},"motion":{"gravity":-0.12,"drag":0.8},"colourMode":"gold"}},"core":{"enabled":false}}}}'::jsonb, 130, 'reference'),
  ('whirl', 'Whirl', 'A spinning corkscrew shower of sparks that rotates and ascends into a spiral column.', 'aerial_burst', 'whirl', '{"version":3,"geometry":"whirl","trailProfile":"whirl","renderDefaults":{"pattern":"wave","geometry":"whirl","trailProfile":"whirl","size":60,"liftVelocity":16,"shellLife":4,"burst":{"speed":[1,2],"gravity":[-0.8,-0.3],"life":[2,3.5],"flairColorMode":"mixed"},"flair":{"enabled":true},"crackle":{"enabled":false,"probability":0,"sound":"crackle"},"strobe":{"enabled":false,"frequencyHz":12,"dutyCycle":0.45},"split":{"enabled":false,"fragments":4,"speed":1.55,"delayRatio":0.42},"sound":{"launch":true,"boom":"light"},"mortar":{"sound":true,"smokeParticles":100},"stars":{"outer":{"enabled":true,"count":60,"burst":{"speed":[1,2],"gravity":[-0.8,-0.3],"life":[2,3.5],"flairColorMode":"bombColor"},"head":{"visible":true,"size":220,"glowStrength":1.4,"glowPadding":150,"whiteCoreSizePercent":20,"whiteCoreBlurPercent":15,"coreSoftness":55,"coreBrightness":50,"coreOpacityFalloff":60,"glowSize":90,"glowSoftness":100,"glowOpacityFalloff":100,"glowBlur":45,"backgroundGlowOpacityFalloff":75,"backgroundGlowSoftness":50,"brightnessHoldPercent":82,"brightnessHoldExponent":0.8},"colourPattern":{"mode":"solid","axis":"vertical","count":1,"colours":[]},"burstTrail":{"preset":"cometTail","enabled":true,"particlesPerStar":80,"width":{"front":3.2,"tail":1,"curve":0.7},"lifetime":{"percent":0.24,"baseSeconds":1.5,"afterglowSeconds":0.25},"intensity":{"brightness":1.25,"fadeSoftness":0.9},"motion":{"gravity":-0.03,"drag":1.3},"colourMode":"starFade"}},"core":{"enabled":false}}}}'::jsonb, 135, 'reference'),
  ('roman_candle', 'Roman Candle', 'A ground tube that spits a cadenced sequence of glowing coloured stars that arc and flare.', 'ascending', 'roman_candle', '{"version":3,"geometry":"roman_candle","trailProfile":"thick_tail","renderDefaults":{"pattern":"fibonacci","geometry":"roman_candle","trailProfile":"thick_tail","size":30,"liftVelocity":14,"shellLife":14,"burst":{"speed":[0.6,1.2],"gravity":[-0.4,0],"life":[1,1.8],"flairColorMode":"bombColor"},"trail":{"density":1.8,"length":1.4,"sparkle":0.4,"thickness":1.4},"flair":{"enabled":true},"crackle":{"enabled":false,"probability":0,"sound":"crackle"},"strobe":{"enabled":false,"frequencyHz":12,"dutyCycle":0.45},"split":{"enabled":false,"fragments":4,"speed":1.55,"delayRatio":0.42},"sound":{"launch":true,"boom":"none"},"mortar":{"sound":true,"smokeParticles":50},"stars":{"outer":{"enabled":true,"count":30,"burst":{"speed":[0.6,1.2],"gravity":[-0.4,0],"life":[1,1.8],"flairColorMode":"bombColor"},"head":{"visible":true,"size":240,"glowStrength":1.6,"glowPadding":150,"whiteCoreSizePercent":20,"whiteCoreBlurPercent":15,"coreSoftness":55,"coreBrightness":50,"coreOpacityFalloff":60,"glowSize":90,"glowSoftness":100,"glowOpacityFalloff":100,"glowBlur":45,"backgroundGlowOpacityFalloff":75,"backgroundGlowSoftness":50,"brightnessHoldPercent":82,"brightnessHoldExponent":0.8},"colourPattern":{"mode":"solid","axis":"vertical","count":1,"colours":[]},"burstTrail":{"preset":"cometTail","enabled":true,"particlesPerStar":90,"width":{"front":3.2,"tail":1,"curve":0.7},"lifetime":{"percent":0.24,"baseSeconds":1.5,"afterglowSeconds":0.25},"intensity":{"brightness":1.25,"fadeSoftness":0.9},"motion":{"gravity":-0.03,"drag":1.3},"colourMode":"starFade"}},"core":{"enabled":false}}}}'::jsonb, 140, 'reference'),
  ('fountain', 'Fountain', 'A sustained ground-origin column of glittering sparks rising in a narrow cone and cascading back.', 'ground', 'fountain', '{"version":3,"geometry":"fountain","trailProfile":"glitter","renderDefaults":{"pattern":"fibonacci","geometry":"fountain","trailProfile":"glitter","size":90,"liftVelocity":8,"shellLife":30,"burst":{"speed":[0.8,1.6],"gravity":[-1.4,-0.8],"life":[1.2,2.4],"flairColorMode":"bombColor"},"trail":{"density":2,"length":0.9,"sparkle":0.85,"thickness":0.8},"flair":{"enabled":true},"crackle":{"enabled":true,"probability":0.05,"sound":"crackle"},"strobe":{"enabled":false,"frequencyHz":12,"dutyCycle":0.45},"split":{"enabled":false,"fragments":4,"speed":1.55,"delayRatio":0.42},"sound":{"launch":false,"boom":"none"},"mortar":{"sound":false,"smokeParticles":30},"stars":{"outer":{"enabled":true,"count":90,"burst":{"speed":[0.8,1.6],"gravity":[-1.4,-0.8],"life":[1.2,2.4],"flairColorMode":"bombColor"},"head":{"visible":true,"size":90,"glowStrength":1.2,"glowPadding":150,"whiteCoreSizePercent":20,"whiteCoreBlurPercent":15,"coreSoftness":55,"coreBrightness":50,"coreOpacityFalloff":60,"glowSize":90,"glowSoftness":100,"glowOpacityFalloff":100,"glowBlur":45,"backgroundGlowOpacityFalloff":75,"backgroundGlowSoftness":50,"brightnessHoldPercent":82,"brightnessHoldExponent":0.8},"colourPattern":{"mode":"solid","axis":"vertical","count":1,"colours":[]},"burstTrail":{"preset":"sparkDust","enabled":true,"particlesPerStar":28,"width":{"front":1.5,"tail":2.6,"curve":1.2},"lifetime":{"percent":0.18,"baseSeconds":1.1,"afterglowSeconds":0.18},"intensity":{"brightness":0.95,"fadeSoftness":1.3},"motion":{"gravity":-0.04,"drag":2.1},"colourMode":"gold"}},"core":{"enabled":false}}}}'::jsonb, 145, 'reference')
on conflict (slug) do update set
  name = excluded.name,
  description = excluded.description,
  family = excluded.family,
  pattern_key = excluded.pattern_key,
  model_json = excluded.model_json,
  sort_order = excluded.sort_order,
  source = excluded.source,
  updated_at = now();

-- Reseed coloured firework variants (default plus contrast colours per effect).
insert into public.fireworks (
  firework_effect_id, slug, name, description, primary_color, secondary_color,
  color_palette, duration_seconds, height_meters, variant_json, render_overrides_json,
  source, confidence
)
select
  fe.id,
  v.slug, v.name, v.description, v.primary_color, v.secondary_color,
  v.color_palette, v.duration_seconds, v.height_meters, v.variant_json, v.render_overrides_json,
  v.source, v.confidence
from (values
  ('peony', 'peony-default', 'Peony Default', 'Catalogue variant for Peony Default.', '#ff2d55', '#ff5a4d', array['#ff2d55', '#ff5a4d', '#ff7a6b']::text[], 5, 220, '{"shellType":"peony","spreadSize":4.6,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#ff2d55","colorPalette":["#ff2d55","#ff5a4d","#ff7a6b"],"glitter":"light","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('peony', 'peony-crimson', 'Peony Crimson', 'Catalogue variant for Peony Crimson.', '#ff2d55', '#ff5a4d', array['#ff2d55', '#ff5a4d', '#ff7a6b']::text[], 5, 220, '{"shellType":"peony","spreadSize":4.6,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#ff2d55","colorPalette":["#ff2d55","#ff5a4d","#ff7a6b"],"glitter":"light","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('peony', 'peony-azure', 'Peony Azure', 'Catalogue variant for Peony Azure.', '#1e7fff', '#7fd0ff', array['#1e7fff', '#7fd0ff', '#f5f7fa']::text[], 5, 220, '{"shellType":"peony","spreadSize":4.6,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#1e7fff","colorPalette":["#1e7fff","#7fd0ff","#f5f7fa"],"glitter":"light","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('chrysanthemum', 'chrysanthemum-default', 'Chrysanthemum Default', 'Catalogue variant for Chrysanthemum Default.', '#ffd166', '#ffcf6b', array['#ffd166', '#ffcf6b', '#ffe9a8']::text[], 5, 220, '{"shellType":"chrysanthemum","spreadSize":4.6,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#ffd166","colorPalette":["#ffd166","#ffcf6b","#ffe9a8"],"glitter":"light","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('chrysanthemum', 'chrysanthemum-crimson', 'Chrysanthemum Crimson', 'Catalogue variant for Chrysanthemum Crimson.', '#ff2d55', '#ff5a4d', array['#ff2d55', '#ff5a4d', '#ff7a6b']::text[], 5, 220, '{"shellType":"chrysanthemum","spreadSize":4.6,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#ff2d55","colorPalette":["#ff2d55","#ff5a4d","#ff7a6b"],"glitter":"light","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('chrysanthemum', 'chrysanthemum-azure', 'Chrysanthemum Azure', 'Catalogue variant for Chrysanthemum Azure.', '#1e7fff', '#7fd0ff', array['#1e7fff', '#7fd0ff', '#f5f7fa']::text[], 5, 220, '{"shellType":"chrysanthemum","spreadSize":4.6,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#1e7fff","colorPalette":["#1e7fff","#7fd0ff","#f5f7fa"],"glitter":"light","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('brocade', 'brocade-default', 'Brocade Default', 'Catalogue variant for Brocade Default.', '#fff7de', '#ffe9a8', array['#fff7de', '#ffe9a8', '#ffd166', '#ffae3d', '#9c5a17']::text[], 5, 220, '{"shellType":"brocade","spreadSize":4.6,"starLifeMs":3000,"starLifeVariation":0.18,"starDensity":1,"color":"#fff7de","colorPalette":["#fff7de","#ffe9a8","#ffd166","#ffae3d","#9c5a17"],"glitter":"heavy","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('brocade', 'brocade-crimson', 'Brocade Crimson', 'Catalogue variant for Brocade Crimson.', '#ff2d55', '#ff5a4d', array['#ff2d55', '#ff5a4d', '#ff7a6b']::text[], 5, 220, '{"shellType":"brocade","spreadSize":4.6,"starLifeMs":3000,"starLifeVariation":0.18,"starDensity":1,"color":"#ff2d55","colorPalette":["#ff2d55","#ff5a4d","#ff7a6b"],"glitter":"heavy","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('brocade', 'brocade-azure', 'Brocade Azure', 'Catalogue variant for Brocade Azure.', '#1e7fff', '#7fd0ff', array['#1e7fff', '#7fd0ff', '#f5f7fa']::text[], 5, 220, '{"shellType":"brocade","spreadSize":4.6,"starLifeMs":3000,"starLifeVariation":0.18,"starDensity":1,"color":"#1e7fff","colorPalette":["#1e7fff","#7fd0ff","#f5f7fa"],"glitter":"heavy","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('kamuro', 'kamuro-default', 'Kamuro Default', 'Catalogue variant for Kamuro Default.', '#ffd166', '#fff3c4', array['#ffd166', '#fff3c4', '#f5f7fa', '#fff7de']::text[], 5, 220, '{"shellType":"kamuro","spreadSize":4.6,"starLifeMs":5200,"starLifeVariation":0.18,"starDensity":1,"color":"#ffd166","colorPalette":["#ffd166","#fff3c4","#f5f7fa","#fff7de"],"glitter":"heavy","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('kamuro', 'kamuro-crimson', 'Kamuro Crimson', 'Catalogue variant for Kamuro Crimson.', '#ff2d55', '#ff5a4d', array['#ff2d55', '#ff5a4d', '#ff7a6b']::text[], 5, 220, '{"shellType":"kamuro","spreadSize":4.6,"starLifeMs":5200,"starLifeVariation":0.18,"starDensity":1,"color":"#ff2d55","colorPalette":["#ff2d55","#ff5a4d","#ff7a6b"],"glitter":"heavy","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('kamuro', 'kamuro-azure', 'Kamuro Azure', 'Catalogue variant for Kamuro Azure.', '#1e7fff', '#7fd0ff', array['#1e7fff', '#7fd0ff', '#f5f7fa']::text[], 5, 220, '{"shellType":"kamuro","spreadSize":4.6,"starLifeMs":5200,"starLifeVariation":0.18,"starDensity":1,"color":"#1e7fff","colorPalette":["#1e7fff","#7fd0ff","#f5f7fa"],"glitter":"heavy","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('willow', 'willow-default', 'Willow Default', 'Catalogue variant for Willow Default.', '#ffd166', '#ffcf6b', array['#ffd166', '#ffcf6b', '#ffae3d', '#9c5a17']::text[], 5, 220, '{"shellType":"willow","spreadSize":4.6,"starLifeMs":5200,"starLifeVariation":0.18,"starDensity":1,"color":"#ffd166","colorPalette":["#ffd166","#ffcf6b","#ffae3d","#9c5a17"],"glitter":"willow","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('willow', 'willow-crimson', 'Willow Crimson', 'Catalogue variant for Willow Crimson.', '#ff2d55', '#ff5a4d', array['#ff2d55', '#ff5a4d', '#ff7a6b']::text[], 5, 220, '{"shellType":"willow","spreadSize":4.6,"starLifeMs":5200,"starLifeVariation":0.18,"starDensity":1,"color":"#ff2d55","colorPalette":["#ff2d55","#ff5a4d","#ff7a6b"],"glitter":"willow","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('willow', 'willow-azure', 'Willow Azure', 'Catalogue variant for Willow Azure.', '#1e7fff', '#7fd0ff', array['#1e7fff', '#7fd0ff', '#f5f7fa']::text[], 5, 220, '{"shellType":"willow","spreadSize":4.6,"starLifeMs":5200,"starLifeVariation":0.18,"starDensity":1,"color":"#1e7fff","colorPalette":["#1e7fff","#7fd0ff","#f5f7fa"],"glitter":"willow","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('palm', 'palm-default', 'Palm Default', 'Catalogue variant for Palm Default.', '#ffd166', '#ffae3d', array['#ffd166', '#ffae3d', '#14fc56']::text[], 5, 220, '{"shellType":"palm","spreadSize":4.6,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#ffd166","colorPalette":["#ffd166","#ffae3d","#14fc56"],"glitter":"willow","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('palm', 'palm-crimson', 'Palm Crimson', 'Catalogue variant for Palm Crimson.', '#ff2d55', '#ff5a4d', array['#ff2d55', '#ff5a4d', '#ff7a6b']::text[], 5, 220, '{"shellType":"palm","spreadSize":4.6,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#ff2d55","colorPalette":["#ff2d55","#ff5a4d","#ff7a6b"],"glitter":"willow","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('palm', 'palm-azure', 'Palm Azure', 'Catalogue variant for Palm Azure.', '#1e7fff', '#7fd0ff', array['#1e7fff', '#7fd0ff', '#f5f7fa']::text[], 5, 220, '{"shellType":"palm","spreadSize":4.6,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#1e7fff","colorPalette":["#1e7fff","#7fd0ff","#f5f7fa"],"glitter":"willow","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('ring', 'ring-default', 'Ring Default', 'Catalogue variant for Ring Default.', '#1e7fff', '#f5f7fa', array['#1e7fff', '#f5f7fa', '#7fd0ff']::text[], 5, 220, '{"shellType":"ring","spreadSize":4.6,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#1e7fff","colorPalette":["#1e7fff","#f5f7fa","#7fd0ff"],"glitter":"none","crackle":false,"strobe":false,"ring":true,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('ring', 'ring-crimson', 'Ring Crimson', 'Catalogue variant for Ring Crimson.', '#ff2d55', '#ff5a4d', array['#ff2d55', '#ff5a4d', '#ff7a6b']::text[], 5, 220, '{"shellType":"ring","spreadSize":4.6,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#ff2d55","colorPalette":["#ff2d55","#ff5a4d","#ff7a6b"],"glitter":"none","crackle":false,"strobe":false,"ring":true,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('ring', 'ring-azure', 'Ring Azure', 'Catalogue variant for Ring Azure.', '#1e7fff', '#7fd0ff', array['#1e7fff', '#7fd0ff', '#f5f7fa']::text[], 5, 220, '{"shellType":"ring","spreadSize":4.6,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#1e7fff","colorPalette":["#1e7fff","#7fd0ff","#f5f7fa"],"glitter":"none","crackle":false,"strobe":false,"ring":true,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('saturn', 'saturn-default', 'Saturn Default', 'Catalogue variant for Saturn Default.', '#c800ff', '#39d98a', array['#c800ff', '#39d98a', '#c89bff', '#7dffbb']::text[], 5, 220, '{"shellType":"saturn","spreadSize":4.6,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#c800ff","colorPalette":["#c800ff","#39d98a","#c89bff","#7dffbb"],"glitter":"none","crackle":false,"strobe":false,"ring":true,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('saturn', 'saturn-crimson', 'Saturn Crimson', 'Catalogue variant for Saturn Crimson.', '#ff2d55', '#ff5a4d', array['#ff2d55', '#ff5a4d', '#ff7a6b']::text[], 5, 220, '{"shellType":"saturn","spreadSize":4.6,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#ff2d55","colorPalette":["#ff2d55","#ff5a4d","#ff7a6b"],"glitter":"none","crackle":false,"strobe":false,"ring":true,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('saturn', 'saturn-azure', 'Saturn Azure', 'Catalogue variant for Saturn Azure.', '#1e7fff', '#7fd0ff', array['#1e7fff', '#7fd0ff', '#f5f7fa']::text[], 5, 220, '{"shellType":"saturn","spreadSize":4.6,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#1e7fff","colorPalette":["#1e7fff","#7fd0ff","#f5f7fa"],"glitter":"none","crackle":false,"strobe":false,"ring":true,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('crossette', 'crossette-default', 'Crossette Default', 'Catalogue variant for Crossette Default.', '#f5f7fa', '#ffd166', array['#f5f7fa', '#ffd166', '#fff3c4']::text[], 5, 220, '{"shellType":"crossette","spreadSize":4.6,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#f5f7fa","colorPalette":["#f5f7fa","#ffd166","#fff3c4"],"glitter":"medium","crackle":false,"strobe":false,"ring":false,"crossette":true,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('crossette', 'crossette-crimson', 'Crossette Crimson', 'Catalogue variant for Crossette Crimson.', '#ff2d55', '#ff5a4d', array['#ff2d55', '#ff5a4d', '#ff7a6b']::text[], 5, 220, '{"shellType":"crossette","spreadSize":4.6,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#ff2d55","colorPalette":["#ff2d55","#ff5a4d","#ff7a6b"],"glitter":"medium","crackle":false,"strobe":false,"ring":false,"crossette":true,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('crossette', 'crossette-azure', 'Crossette Azure', 'Catalogue variant for Crossette Azure.', '#1e7fff', '#7fd0ff', array['#1e7fff', '#7fd0ff', '#f5f7fa']::text[], 5, 220, '{"shellType":"crossette","spreadSize":4.6,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#1e7fff","colorPalette":["#1e7fff","#7fd0ff","#f5f7fa"],"glitter":"medium","crackle":false,"strobe":false,"ring":false,"crossette":true,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('double_break', 'double_break-default', 'Double Break Default', 'Catalogue variant for Double Break Default.', '#14fc56', '#1e7fff', array['#14fc56', '#1e7fff', '#7dffbb', '#7fd0ff']::text[], 5, 220, '{"shellType":"double_break","spreadSize":4.6,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#14fc56","colorPalette":["#14fc56","#1e7fff","#7dffbb","#7fd0ff"],"glitter":"medium","crackle":false,"strobe":false,"ring":false,"crossette":true,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('double_break', 'double_break-crimson', 'Double Break Crimson', 'Catalogue variant for Double Break Crimson.', '#ff2d55', '#ff5a4d', array['#ff2d55', '#ff5a4d', '#ff7a6b']::text[], 5, 220, '{"shellType":"double_break","spreadSize":4.6,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#ff2d55","colorPalette":["#ff2d55","#ff5a4d","#ff7a6b"],"glitter":"medium","crackle":false,"strobe":false,"ring":false,"crossette":true,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('double_break', 'double_break-azure', 'Double Break Azure', 'Catalogue variant for Double Break Azure.', '#1e7fff', '#7fd0ff', array['#1e7fff', '#7fd0ff', '#f5f7fa']::text[], 5, 220, '{"shellType":"double_break","spreadSize":4.6,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#1e7fff","colorPalette":["#1e7fff","#7fd0ff","#f5f7fa"],"glitter":"medium","crackle":false,"strobe":false,"ring":false,"crossette":true,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('bowtie', 'bowtie-default', 'Bow Tie Default', 'Catalogue variant for Bow Tie Default.', '#ff2d55', '#ff5a4d', array['#ff2d55', '#ff5a4d', '#ff8a5a']::text[], 5, 220, '{"shellType":"bowtie","spreadSize":4.6,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#ff2d55","colorPalette":["#ff2d55","#ff5a4d","#ff8a5a"],"glitter":"light","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('bowtie', 'bowtie-crimson', 'Bow Tie Crimson', 'Catalogue variant for Bow Tie Crimson.', '#ff2d55', '#ff5a4d', array['#ff2d55', '#ff5a4d', '#ff7a6b']::text[], 5, 220, '{"shellType":"bowtie","spreadSize":4.6,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#ff2d55","colorPalette":["#ff2d55","#ff5a4d","#ff7a6b"],"glitter":"light","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('bowtie', 'bowtie-azure', 'Bow Tie Azure', 'Catalogue variant for Bow Tie Azure.', '#1e7fff', '#7fd0ff', array['#1e7fff', '#7fd0ff', '#f5f7fa']::text[], 5, 220, '{"shellType":"bowtie","spreadSize":4.6,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#1e7fff","colorPalette":["#1e7fff","#7fd0ff","#f5f7fa"],"glitter":"light","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('horsetail', 'horsetail-default', 'Horsetail Default', 'Catalogue variant for Horsetail Default.', '#ffd166', '#ffae3d', array['#ffd166', '#ffae3d', '#fff3c4']::text[], 5, 220, '{"shellType":"horsetail","spreadSize":4.6,"starLifeMs":4000,"starLifeVariation":0.18,"starDensity":1,"color":"#ffd166","colorPalette":["#ffd166","#ffae3d","#fff3c4"],"glitter":"willow","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":true}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('horsetail', 'horsetail-crimson', 'Horsetail Crimson', 'Catalogue variant for Horsetail Crimson.', '#ff2d55', '#ff5a4d', array['#ff2d55', '#ff5a4d', '#ff7a6b']::text[], 5, 220, '{"shellType":"horsetail","spreadSize":4.6,"starLifeMs":4000,"starLifeVariation":0.18,"starDensity":1,"color":"#ff2d55","colorPalette":["#ff2d55","#ff5a4d","#ff7a6b"],"glitter":"willow","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":true}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('horsetail', 'horsetail-azure', 'Horsetail Azure', 'Catalogue variant for Horsetail Azure.', '#1e7fff', '#7fd0ff', array['#1e7fff', '#7fd0ff', '#f5f7fa']::text[], 5, 220, '{"shellType":"horsetail","spreadSize":4.6,"starLifeMs":4000,"starLifeVariation":0.18,"starDensity":1,"color":"#1e7fff","colorPalette":["#1e7fff","#7fd0ff","#f5f7fa"],"glitter":"willow","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":true}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('comet', 'comet-default', 'Comet Default', 'Catalogue variant for Comet Default.', '#ffd166', '#ffae3d', array['#ffd166', '#ffae3d', '#fff7de']::text[], 3.4, 160, '{"shellType":"comet","spreadSize":2.2,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#ffd166","colorPalette":["#ffd166","#ffae3d","#fff7de"],"glitter":"light","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('comet', 'comet-crimson', 'Comet Crimson', 'Catalogue variant for Comet Crimson.', '#ff2d55', '#ff5a4d', array['#ff2d55', '#ff5a4d', '#ff7a6b']::text[], 3.4, 160, '{"shellType":"comet","spreadSize":2.2,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#ff2d55","colorPalette":["#ff2d55","#ff5a4d","#ff7a6b"],"glitter":"light","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('comet', 'comet-azure', 'Comet Azure', 'Catalogue variant for Comet Azure.', '#1e7fff', '#7fd0ff', array['#1e7fff', '#7fd0ff', '#f5f7fa']::text[], 3.4, 160, '{"shellType":"comet","spreadSize":2.2,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#1e7fff","colorPalette":["#1e7fff","#7fd0ff","#f5f7fa"],"glitter":"light","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('mine', 'mine-default', 'Mine Default', 'Catalogue variant for Mine Default.', '#ff2d55', '#14fc56', array['#ff2d55', '#14fc56', '#ffae3d']::text[], 6, 60, '{"shellType":"mine","spreadSize":3.2,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#ff2d55","colorPalette":["#ff2d55","#14fc56","#ffae3d"],"glitter":"light","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('mine', 'mine-crimson', 'Mine Crimson', 'Catalogue variant for Mine Crimson.', '#ff2d55', '#ff5a4d', array['#ff2d55', '#ff5a4d', '#ff7a6b']::text[], 6, 60, '{"shellType":"mine","spreadSize":3.2,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#ff2d55","colorPalette":["#ff2d55","#ff5a4d","#ff7a6b"],"glitter":"light","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('mine', 'mine-azure', 'Mine Azure', 'Catalogue variant for Mine Azure.', '#1e7fff', '#7fd0ff', array['#1e7fff', '#7fd0ff', '#f5f7fa']::text[], 6, 60, '{"shellType":"mine","spreadSize":3.2,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#1e7fff","colorPalette":["#1e7fff","#7fd0ff","#f5f7fa"],"glitter":"light","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('pearls', 'pearls-default', 'Pearls Default', 'Catalogue variant for Pearls Default.', '#ffd166', '#f5f7fa', array['#ffd166', '#f5f7fa', '#1e7fff']::text[], 5, 220, '{"shellType":"pearls","spreadSize":4.6,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#ffd166","colorPalette":["#ffd166","#f5f7fa","#1e7fff"],"glitter":"none","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('pearls', 'pearls-crimson', 'Pearls Crimson', 'Catalogue variant for Pearls Crimson.', '#ff2d55', '#ff5a4d', array['#ff2d55', '#ff5a4d', '#ff7a6b']::text[], 5, 220, '{"shellType":"pearls","spreadSize":4.6,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#ff2d55","colorPalette":["#ff2d55","#ff5a4d","#ff7a6b"],"glitter":"none","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('pearls', 'pearls-azure', 'Pearls Azure', 'Catalogue variant for Pearls Azure.', '#1e7fff', '#7fd0ff', array['#1e7fff', '#7fd0ff', '#f5f7fa']::text[], 5, 220, '{"shellType":"pearls","spreadSize":4.6,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#1e7fff","colorPalette":["#1e7fff","#7fd0ff","#f5f7fa"],"glitter":"none","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('pistil', 'pistil-default', 'Pistil Default', 'Catalogue variant for Pistil Default.', '#ff2d55', '#14fc56', array['#ff2d55', '#14fc56', '#ff5a4d', '#7dffbb']::text[], 5, 220, '{"shellType":"pistil","spreadSize":4.6,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#ff2d55","colorPalette":["#ff2d55","#14fc56","#ff5a4d","#7dffbb"],"glitter":"light","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('pistil', 'pistil-crimson', 'Pistil Crimson', 'Catalogue variant for Pistil Crimson.', '#ff2d55', '#ff5a4d', array['#ff2d55', '#ff5a4d', '#ff7a6b']::text[], 5, 220, '{"shellType":"pistil","spreadSize":4.6,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#ff2d55","colorPalette":["#ff2d55","#ff5a4d","#ff7a6b"],"glitter":"light","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('pistil', 'pistil-azure', 'Pistil Azure', 'Catalogue variant for Pistil Azure.', '#1e7fff', '#7fd0ff', array['#1e7fff', '#7fd0ff', '#f5f7fa']::text[], 5, 220, '{"shellType":"pistil","spreadSize":4.6,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#1e7fff","colorPalette":["#1e7fff","#7fd0ff","#f5f7fa"],"glitter":"light","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('nishiki', 'nishiki-default', 'Nishiki Default', 'Catalogue variant for Nishiki Default.', '#ffd166', '#fff3c4', array['#ffd166', '#fff3c4', '#1e7fff', '#c800ff']::text[], 5, 220, '{"shellType":"nishiki","spreadSize":4.6,"starLifeMs":5200,"starLifeVariation":0.18,"starDensity":1,"color":"#ffd166","colorPalette":["#ffd166","#fff3c4","#1e7fff","#c800ff"],"glitter":"light","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('nishiki', 'nishiki-crimson', 'Nishiki Crimson', 'Catalogue variant for Nishiki Crimson.', '#ff2d55', '#ff5a4d', array['#ff2d55', '#ff5a4d', '#ff7a6b']::text[], 5, 220, '{"shellType":"nishiki","spreadSize":4.6,"starLifeMs":5200,"starLifeVariation":0.18,"starDensity":1,"color":"#ff2d55","colorPalette":["#ff2d55","#ff5a4d","#ff7a6b"],"glitter":"light","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('nishiki', 'nishiki-azure', 'Nishiki Azure', 'Catalogue variant for Nishiki Azure.', '#1e7fff', '#7fd0ff', array['#1e7fff', '#7fd0ff', '#f5f7fa']::text[], 5, 220, '{"shellType":"nishiki","spreadSize":4.6,"starLifeMs":5200,"starLifeVariation":0.18,"starDensity":1,"color":"#1e7fff","colorPalette":["#1e7fff","#7fd0ff","#f5f7fa"],"glitter":"light","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('strobe', 'strobe-default', 'Strobe Default', 'Catalogue variant for Strobe Default.', '#ffffff', '#f0f6ff', array['#ffffff', '#f0f6ff', '#9bf09b']::text[], 5, 220, '{"shellType":"strobe","spreadSize":4.6,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#ffffff","colorPalette":["#ffffff","#f0f6ff","#9bf09b"],"glitter":"medium","crackle":false,"strobe":true,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('strobe', 'strobe-crimson', 'Strobe Crimson', 'Catalogue variant for Strobe Crimson.', '#ff2d55', '#ff5a4d', array['#ff2d55', '#ff5a4d', '#ff7a6b']::text[], 5, 220, '{"shellType":"strobe","spreadSize":4.6,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#ff2d55","colorPalette":["#ff2d55","#ff5a4d","#ff7a6b"],"glitter":"medium","crackle":false,"strobe":true,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('strobe', 'strobe-azure', 'Strobe Azure', 'Catalogue variant for Strobe Azure.', '#1e7fff', '#7fd0ff', array['#1e7fff', '#7fd0ff', '#f5f7fa']::text[], 5, 220, '{"shellType":"strobe","spreadSize":4.6,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#1e7fff","colorPalette":["#1e7fff","#7fd0ff","#f5f7fa"],"glitter":"medium","crackle":false,"strobe":true,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('crackle', 'crackle-default', 'Crackle Default', 'Catalogue variant for Crackle Default.', '#ffffff', '#fff3c4', array['#ffffff', '#fff3c4', '#ffd166']::text[], 5, 220, '{"shellType":"crackle","spreadSize":4.6,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#ffffff","colorPalette":["#ffffff","#fff3c4","#ffd166"],"glitter":"medium","crackle":true,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('crackle', 'crackle-crimson', 'Crackle Crimson', 'Catalogue variant for Crackle Crimson.', '#ff2d55', '#ff5a4d', array['#ff2d55', '#ff5a4d', '#ff7a6b']::text[], 5, 220, '{"shellType":"crackle","spreadSize":4.6,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#ff2d55","colorPalette":["#ff2d55","#ff5a4d","#ff7a6b"],"glitter":"medium","crackle":true,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('crackle', 'crackle-azure', 'Crackle Azure', 'Catalogue variant for Crackle Azure.', '#1e7fff', '#7fd0ff', array['#1e7fff', '#7fd0ff', '#f5f7fa']::text[], 5, 220, '{"shellType":"crackle","spreadSize":4.6,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#1e7fff","colorPalette":["#1e7fff","#7fd0ff","#f5f7fa"],"glitter":"medium","crackle":true,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('silverFish', 'silverFish-default', 'Silver Fish Default', 'Catalogue variant for Silver Fish Default.', '#f5f7fa', '#ffd166', array['#f5f7fa', '#ffd166', '#ffffff']::text[], 5, 220, '{"shellType":"silverFish","spreadSize":4.6,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#f5f7fa","colorPalette":["#f5f7fa","#ffd166","#ffffff"],"glitter":"light","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('silverFish', 'silverFish-crimson', 'Silver Fish Crimson', 'Catalogue variant for Silver Fish Crimson.', '#ff2d55', '#ff5a4d', array['#ff2d55', '#ff5a4d', '#ff7a6b']::text[], 5, 220, '{"shellType":"silverFish","spreadSize":4.6,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#ff2d55","colorPalette":["#ff2d55","#ff5a4d","#ff7a6b"],"glitter":"light","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('silverFish', 'silverFish-azure', 'Silver Fish Azure', 'Catalogue variant for Silver Fish Azure.', '#1e7fff', '#7fd0ff', array['#1e7fff', '#7fd0ff', '#f5f7fa']::text[], 5, 220, '{"shellType":"silverFish","spreadSize":4.6,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#1e7fff","colorPalette":["#1e7fff","#7fd0ff","#f5f7fa"],"glitter":"light","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('waterfall', 'waterfall-default', 'Waterfall Default', 'Catalogue variant for Waterfall Default.', '#ffd166', '#ffd870', array['#ffd166', '#ffd870', '#f5f7fa']::text[], 5, 220, '{"shellType":"waterfall","spreadSize":4.6,"starLifeMs":4000,"starLifeVariation":0.18,"starDensity":1,"color":"#ffd166","colorPalette":["#ffd166","#ffd870","#f5f7fa"],"glitter":"willow","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('waterfall', 'waterfall-crimson', 'Waterfall Crimson', 'Catalogue variant for Waterfall Crimson.', '#ff2d55', '#ff5a4d', array['#ff2d55', '#ff5a4d', '#ff7a6b']::text[], 5, 220, '{"shellType":"waterfall","spreadSize":4.6,"starLifeMs":4000,"starLifeVariation":0.18,"starDensity":1,"color":"#ff2d55","colorPalette":["#ff2d55","#ff5a4d","#ff7a6b"],"glitter":"willow","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('waterfall', 'waterfall-azure', 'Waterfall Azure', 'Catalogue variant for Waterfall Azure.', '#1e7fff', '#7fd0ff', array['#1e7fff', '#7fd0ff', '#f5f7fa']::text[], 5, 220, '{"shellType":"waterfall","spreadSize":4.6,"starLifeMs":4000,"starLifeVariation":0.18,"starDensity":1,"color":"#1e7fff","colorPalette":["#1e7fff","#7fd0ff","#f5f7fa"],"glitter":"willow","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('whirl', 'whirl-default', 'Whirl Default', 'Catalogue variant for Whirl Default.', '#f5f7fa', '#ff2d55', array['#f5f7fa', '#ff2d55', '#ffd166']::text[], 5, 220, '{"shellType":"whirl","spreadSize":4.6,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#f5f7fa","colorPalette":["#f5f7fa","#ff2d55","#ffd166"],"glitter":"light","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('whirl', 'whirl-crimson', 'Whirl Crimson', 'Catalogue variant for Whirl Crimson.', '#ff2d55', '#ff5a4d', array['#ff2d55', '#ff5a4d', '#ff7a6b']::text[], 5, 220, '{"shellType":"whirl","spreadSize":4.6,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#ff2d55","colorPalette":["#ff2d55","#ff5a4d","#ff7a6b"],"glitter":"light","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('whirl', 'whirl-azure', 'Whirl Azure', 'Catalogue variant for Whirl Azure.', '#1e7fff', '#7fd0ff', array['#1e7fff', '#7fd0ff', '#f5f7fa']::text[], 5, 220, '{"shellType":"whirl","spreadSize":4.6,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#1e7fff","colorPalette":["#1e7fff","#7fd0ff","#f5f7fa"],"glitter":"light","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('roman_candle', 'roman_candle-default', 'Roman Candle Default', 'Catalogue variant for Roman Candle Default.', '#ff2d55', '#14fc56', array['#ff2d55', '#14fc56', '#1e7fff', '#ffd166']::text[], 6, 60, '{"shellType":"roman_candle","spreadSize":3,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#ff2d55","colorPalette":["#ff2d55","#14fc56","#1e7fff","#ffd166"],"glitter":"light","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('roman_candle', 'roman_candle-crimson', 'Roman Candle Crimson', 'Catalogue variant for Roman Candle Crimson.', '#ff2d55', '#ff5a4d', array['#ff2d55', '#ff5a4d', '#ff7a6b']::text[], 6, 60, '{"shellType":"roman_candle","spreadSize":3,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#ff2d55","colorPalette":["#ff2d55","#ff5a4d","#ff7a6b"],"glitter":"light","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('roman_candle', 'roman_candle-azure', 'Roman Candle Azure', 'Catalogue variant for Roman Candle Azure.', '#1e7fff', '#7fd0ff', array['#1e7fff', '#7fd0ff', '#f5f7fa']::text[], 6, 60, '{"shellType":"roman_candle","spreadSize":3,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#1e7fff","colorPalette":["#1e7fff","#7fd0ff","#f5f7fa"],"glitter":"light","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('fountain', 'fountain-default', 'Fountain Default', 'Catalogue variant for Fountain Default.', '#f8f8ff', '#ffd166', array['#f8f8ff', '#ffd166', '#fff3c4']::text[], 6, 60, '{"shellType":"fountain","spreadSize":3,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#f8f8ff","colorPalette":["#f8f8ff","#ffd166","#fff3c4"],"glitter":"light","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('fountain', 'fountain-crimson', 'Fountain Crimson', 'Catalogue variant for Fountain Crimson.', '#ff2d55', '#ff5a4d', array['#ff2d55', '#ff5a4d', '#ff7a6b']::text[], 6, 60, '{"shellType":"fountain","spreadSize":3,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#ff2d55","colorPalette":["#ff2d55","#ff5a4d","#ff7a6b"],"glitter":"light","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75),
  ('fountain', 'fountain-azure', 'Fountain Azure', 'Catalogue variant for Fountain Azure.', '#1e7fff', '#7fd0ff', array['#1e7fff', '#7fd0ff', '#f5f7fa']::text[], 6, 60, '{"shellType":"fountain","spreadSize":3,"starLifeMs":1700,"starLifeVariation":0.18,"starDensity":1,"color":"#1e7fff","colorPalette":["#1e7fff","#7fd0ff","#f5f7fa"],"glitter":"light","crackle":false,"strobe":false,"ring":false,"crossette":false,"horsetail":false}'::jsonb, '{}'::jsonb, 'catalogue', 0.75)
) as v(effect_slug, slug, name, description, primary_color, secondary_color, color_palette, duration_seconds, height_meters, variant_json, render_overrides_json, source, confidence)
join public.firework_effects fe on fe.slug = v.effect_slug
on conflict (slug) do update set
  firework_effect_id = excluded.firework_effect_id,
  name = excluded.name,
  description = excluded.description,
  primary_color = excluded.primary_color,
  secondary_color = excluded.secondary_color,
  color_palette = excluded.color_palette,
  duration_seconds = excluded.duration_seconds,
  height_meters = excluded.height_meters,
  variant_json = excluded.variant_json,
  render_overrides_json = excluded.render_overrides_json,
  source = excluded.source,
  confidence = excluded.confidence,
  updated_at = now();

-- Re-link dependents to the new catalogue default firework for each target effect.
update public.catalogue_items ci
  set firework_id = nf.id
  from _dep_effect_targets d
  join public.firework_effects te on te.slug = d.target_effect_slug
  join public.fireworks nf on nf.firework_effect_id = te.id and nf.slug = te.slug || '-default'
  where d.src = 'catalogue_item' and ci.id = d.dep_id;
update public.multishot_fireworks mf
  set firework_id = nf.id
  from _dep_effect_targets d
  join public.firework_effects te on te.slug = d.target_effect_slug
  join public.fireworks nf on nf.firework_effect_id = te.id and nf.slug = te.slug || '-default'
  where d.src = 'multishot_firework' and mf.id = d.dep_id;

-- Prune legacy fireworks no longer in the catalogue. Imported, manually
-- authored, and LLM-generated variants are intentionally preserved.
delete from public.fireworks where slug not in (
  'peony-default', 'peony-crimson', 'peony-azure', 'chrysanthemum-default', 'chrysanthemum-crimson', 'chrysanthemum-azure', 'brocade-default', 'brocade-crimson', 'brocade-azure', 'kamuro-default', 'kamuro-crimson', 'kamuro-azure', 'willow-default', 'willow-crimson', 'willow-azure', 'palm-default', 'palm-crimson', 'palm-azure', 'ring-default', 'ring-crimson', 'ring-azure', 'saturn-default', 'saturn-crimson', 'saturn-azure', 'crossette-default', 'crossette-crimson', 'crossette-azure', 'double_break-default', 'double_break-crimson', 'double_break-azure', 'bowtie-default', 'bowtie-crimson', 'bowtie-azure', 'horsetail-default', 'horsetail-crimson', 'horsetail-azure', 'comet-default', 'comet-crimson', 'comet-azure', 'mine-default', 'mine-crimson', 'mine-azure', 'pearls-default', 'pearls-crimson', 'pearls-azure', 'pistil-default', 'pistil-crimson', 'pistil-azure', 'nishiki-default', 'nishiki-crimson', 'nishiki-azure', 'strobe-default', 'strobe-crimson', 'strobe-azure', 'crackle-default', 'crackle-crimson', 'crackle-azure', 'silverFish-default', 'silverFish-crimson', 'silverFish-azure', 'waterfall-default', 'waterfall-crimson', 'waterfall-azure', 'whirl-default', 'whirl-crimson', 'whirl-azure', 'roman_candle-default', 'roman_candle-crimson', 'roman_candle-azure', 'fountain-default', 'fountain-crimson', 'fountain-azure'
)
and source in ('catalogue', 'legacy_migrated');

-- Prune legacy effects no longer in the catalogue only once no preserved
-- firework still references them.
delete from public.firework_effects where slug not in (
  'peony', 'chrysanthemum', 'brocade', 'kamuro', 'willow', 'palm', 'ring', 'saturn', 'crossette', 'double_break', 'bowtie', 'horsetail', 'comet', 'mine', 'pearls', 'pistil', 'nishiki', 'strobe', 'crackle', 'silverFish', 'waterfall', 'whirl', 'roman_candle', 'fountain'
)
and source in ('reference', 'legacy_migrated')
and not exists (
  select 1
  from public.fireworks fw
  where fw.firework_effect_id = public.firework_effects.id
);

drop table _dep_effect_targets;
drop table _effect_remap;
