INSERT INTO show_presets (
  slug, title, theme, description,
  duration_seconds, budget_cents, total_cents, effects_count, time_of_day, mood_tags,
  preview_cues, is_featured, sort_order, cover_shader
) VALUES
(
  'neon-sprint',
  'Neon Sprint',
  'Fast electric colour with a bright finish',
  'A short, high-energy show for pop tracks and party openers. Blue rings, crimson peonies, mines and whirls keep it moving from the first beat.',
  90,
  9000,
  7600,
  18,
  'Night',
  ARRAY['High energy','Colourful','Short'],
  '[{"timeSeconds":2,"fireworkSlug":"mine-default","description":"Opening mine"},{"timeSeconds":7,"fireworkSlug":"ring-azure","description":"Azure ring"},{"timeSeconds":12,"fireworkSlug":"peony-crimson","description":"Crimson peony"},{"timeSeconds":17,"fireworkSlug":"crossette-default","description":"Crossette pop"},{"timeSeconds":22,"fireworkSlug":"whirl-azure","description":"Azure whirl"},{"timeSeconds":27,"fireworkSlug":"strobe-default","description":"White strobe"},{"timeSeconds":32,"fireworkSlug":"comet-crimson","description":"Crimson comet"},{"timeSeconds":37,"fireworkSlug":"ring-azure","description":"Azure ring"},{"timeSeconds":42,"fireworkSlug":"peony-azure","description":"Azure peony"},{"timeSeconds":47,"fireworkSlug":"mine-default","description":"Pulse mine"},{"timeSeconds":52,"fireworkSlug":"crossette-default","description":"Crossette pop"},{"timeSeconds":57,"fireworkSlug":"whirl-azure","description":"Whirl lift"},{"timeSeconds":62,"fireworkSlug":"ring-crimson","description":"Crimson ring"},{"timeSeconds":67,"fireworkSlug":"peony-crimson","description":"Crimson peony"},{"timeSeconds":72,"fireworkSlug":"strobe-default","description":"Strobe lift"},{"timeSeconds":77,"fireworkSlug":"crossette-default","description":"Crossette"},{"timeSeconds":84,"fireworkSlug":"mine-default","description":"Final mine"},{"timeSeconds":88,"fireworkSlug":"whirl-azure","description":"Neon finish"}]'::jsonb,
  false,
  90,
  '{"kind":"mesh-gradient","colors":["#00e5ff","#8b5cf6","#ff3df2","#00ff9c"]}'::jsonb
),
(
  'aurora-field',
  'Aurora Field',
  'Cool blue-green waves with silver drift',
  'A flowing show for open spaces. Azure comets and waterfalls create a northern-light feel before silver strobes close the field.',
  150,
  14000,
  11850,
  22,
  'Night',
  ARRAY['Cool tones','Elegant','Open space'],
  '[{"timeSeconds":4,"fireworkSlug":"comet-azure","description":"Azure comet"},{"timeSeconds":11,"fireworkSlug":"pearls-azure","description":"Azure pearls"},{"timeSeconds":18,"fireworkSlug":"waterfall-azure","description":"Blue waterfall"},{"timeSeconds":25,"fireworkSlug":"willow-default","description":"Silver willow"},{"timeSeconds":32,"fireworkSlug":"peony-azure","description":"Azure peony"},{"timeSeconds":39,"fireworkSlug":"ring-azure","description":"Azure ring"},{"timeSeconds":46,"fireworkSlug":"comet-azure","description":"Comet sweep"},{"timeSeconds":53,"fireworkSlug":"waterfall-azure","description":"Waterfall"},{"timeSeconds":60,"fireworkSlug":"pearls-default","description":"Pearl shimmer"},{"timeSeconds":67,"fireworkSlug":"strobe-default","description":"White strobe"},{"timeSeconds":74,"fireworkSlug":"willow-default","description":"Willow drift"},{"timeSeconds":81,"fireworkSlug":"peony-azure","description":"Azure peony"},{"timeSeconds":88,"fireworkSlug":"ring-default","description":"Soft ring"},{"timeSeconds":95,"fireworkSlug":"waterfall-azure","description":"Waterfall"},{"timeSeconds":102,"fireworkSlug":"comet-azure","description":"Comet"},{"timeSeconds":109,"fireworkSlug":"pearls-azure","description":"Pearls"},{"timeSeconds":116,"fireworkSlug":"willow-default","description":"Willow"},{"timeSeconds":123,"fireworkSlug":"strobe-default","description":"Strobe"},{"timeSeconds":130,"fireworkSlug":"waterfall-default","description":"Silver fall"},{"timeSeconds":137,"fireworkSlug":"ring-azure","description":"Azure ring"},{"timeSeconds":144,"fireworkSlug":"strobe-default","description":"Final strobe"},{"timeSeconds":148,"fireworkSlug":"waterfall-azure","description":"Aurora finish"}]'::jsonb,
  true,
  100,
  '{"kind":"god-rays","colors":["#33fff5","#4d9fe8","#f4f1ea"]}'::jsonb
),
(
  'skyline-countdown',
  'Skyline Countdown',
  'A clean countdown build into a bright finale',
  'Built for the last three minutes before a big moment. The show starts tidy and rhythmic, then expands into palms, rings and strobes.',
  180,
  21000,
  18200,
  30,
  'Night',
  ARRAY['Grand finale focused','Rhythmic','Premium'],
  '[{"timeSeconds":5,"fireworkSlug":"comet-default","description":"Countdown comet"},{"timeSeconds":11,"fireworkSlug":"ring-default","description":"Clean ring"},{"timeSeconds":17,"fireworkSlug":"peony-default","description":"Gold peony"},{"timeSeconds":23,"fireworkSlug":"palm-default","description":"Gold palm"},{"timeSeconds":29,"fireworkSlug":"strobe-default","description":"White strobe"},{"timeSeconds":35,"fireworkSlug":"comet-crimson","description":"Crimson comet"},{"timeSeconds":41,"fireworkSlug":"ring-crimson","description":"Crimson ring"},{"timeSeconds":47,"fireworkSlug":"peony-crimson","description":"Crimson peony"},{"timeSeconds":53,"fireworkSlug":"palm-crimson","description":"Crimson palm"},{"timeSeconds":59,"fireworkSlug":"strobe-crimson","description":"Crimson strobe"},{"timeSeconds":65,"fireworkSlug":"ring-azure","description":"Azure ring"},{"timeSeconds":71,"fireworkSlug":"peony-azure","description":"Azure peony"},{"timeSeconds":77,"fireworkSlug":"comet-azure","description":"Azure comet"},{"timeSeconds":83,"fireworkSlug":"waterfall-azure","description":"Blue waterfall"},{"timeSeconds":89,"fireworkSlug":"strobe-default","description":"White strobe"},{"timeSeconds":95,"fireworkSlug":"palm-default","description":"Palm lift"},{"timeSeconds":101,"fireworkSlug":"brocade-default","description":"Brocade"},{"timeSeconds":107,"fireworkSlug":"willow-default","description":"Willow"},{"timeSeconds":113,"fireworkSlug":"nishiki-default","description":"Nishiki"},{"timeSeconds":119,"fireworkSlug":"double_break-default","description":"Double break"},{"timeSeconds":125,"fireworkSlug":"crossette-default","description":"Crossette"},{"timeSeconds":131,"fireworkSlug":"mine-default","description":"Mine"},{"timeSeconds":137,"fireworkSlug":"ring-default","description":"Ring"},{"timeSeconds":143,"fireworkSlug":"peony-default","description":"Peony"},{"timeSeconds":149,"fireworkSlug":"kamuro-default","description":"Kamuro"},{"timeSeconds":155,"fireworkSlug":"brocade-default","description":"Brocade"},{"timeSeconds":161,"fireworkSlug":"strobe-default","description":"Strobe"},{"timeSeconds":167,"fireworkSlug":"double_break-default","description":"Double break"},{"timeSeconds":174,"fireworkSlug":"strobe-default","description":"Final lift"},{"timeSeconds":178,"fireworkSlug":"double_break-default","description":"Countdown finale"}]'::jsonb,
  true,
  110,
  '{"kind":"warp","colors":["#ffd166","#ff4d6d","#4d9fe8","#f4f1ea"]}'::jsonb
),
(
  'willow-lanterns',
  'Willow Lanterns',
  'Slow gold willows and soft hanging tails',
  'A calmer show for dinners, weddings and small gatherings. Gold willows and kamuro crowns hang in the sky with a soft final shimmer.',
  120,
  11000,
  9350,
  18,
  'Dusk',
  ARRAY['Elegant','Warm tones','Calm'],
  '[{"timeSeconds":5,"fireworkSlug":"willow-default","description":"Willow drift"},{"timeSeconds":12,"fireworkSlug":"kamuro-default","description":"Kamuro crown"},{"timeSeconds":19,"fireworkSlug":"horsetail-default","description":"Horsetail"},{"timeSeconds":26,"fireworkSlug":"peony-default","description":"Gold peony"},{"timeSeconds":33,"fireworkSlug":"willow-default","description":"Willow"},{"timeSeconds":40,"fireworkSlug":"brocade-default","description":"Brocade"},{"timeSeconds":47,"fireworkSlug":"pearls-default","description":"Pearls"},{"timeSeconds":54,"fireworkSlug":"kamuro-default","description":"Kamuro"},{"timeSeconds":61,"fireworkSlug":"willow-default","description":"Willow"},{"timeSeconds":68,"fireworkSlug":"palm-default","description":"Palm"},{"timeSeconds":75,"fireworkSlug":"horsetail-default","description":"Horsetail"},{"timeSeconds":82,"fireworkSlug":"brocade-default","description":"Brocade"},{"timeSeconds":89,"fireworkSlug":"willow-default","description":"Willow"},{"timeSeconds":96,"fireworkSlug":"pearls-default","description":"Pearls"},{"timeSeconds":103,"fireworkSlug":"kamuro-default","description":"Kamuro"},{"timeSeconds":110,"fireworkSlug":"willow-default","description":"Willow"},{"timeSeconds":116,"fireworkSlug":"strobe-default","description":"Silver shimmer"},{"timeSeconds":118,"fireworkSlug":"horsetail-default","description":"Lantern finish"}]'::jsonb,
  false,
  120,
  '{"kind":"grain-gradient","colors":["#efb93f","#f4f1ea","#2ec487"]}'::jsonb
),
(
  'thunder-run',
  'Thunder Run',
  'Loud crackle, mines and red movement',
  'A compact show for loud tracks. Mines and crossettes kick through red crackle, with a heavy short finale.',
  75,
  9500,
  8100,
  18,
  'Night',
  ARRAY['Loud','High energy','Short'],
  '[{"timeSeconds":2,"fireworkSlug":"mine-default","description":"Mine hit"},{"timeSeconds":6,"fireworkSlug":"crackle-crimson","description":"Crimson crackle"},{"timeSeconds":10,"fireworkSlug":"crossette-crimson","description":"Red crossette"},{"timeSeconds":14,"fireworkSlug":"peony-crimson","description":"Crimson peony"},{"timeSeconds":18,"fireworkSlug":"mine-default","description":"Mine"},{"timeSeconds":22,"fireworkSlug":"strobe-crimson","description":"Red strobe"},{"timeSeconds":26,"fireworkSlug":"comet-crimson","description":"Red comet"},{"timeSeconds":30,"fireworkSlug":"crossette-default","description":"Crossette"},{"timeSeconds":34,"fireworkSlug":"crackle-crimson","description":"Crackle"},{"timeSeconds":38,"fireworkSlug":"mine-default","description":"Mine"},{"timeSeconds":42,"fireworkSlug":"ring-crimson","description":"Red ring"},{"timeSeconds":46,"fireworkSlug":"peony-crimson","description":"Peony"},{"timeSeconds":50,"fireworkSlug":"crackle-crimson","description":"Crackle"},{"timeSeconds":54,"fireworkSlug":"crossette-crimson","description":"Crossette"},{"timeSeconds":58,"fireworkSlug":"mine-default","description":"Mine"},{"timeSeconds":63,"fireworkSlug":"strobe-crimson","description":"Red strobe"},{"timeSeconds":69,"fireworkSlug":"crackle-crimson","description":"Final crackle"},{"timeSeconds":73,"fireworkSlug":"mine-default","description":"Thunder finish"}]'::jsonb,
  false,
  130,
  '{"kind":"simplex-noise","colors":["#e24b4a","#f08a3c","#ffd166","#0b1020"]}'::jsonb
),
(
  'pastel-garden',
  'Pastel Garden',
  'Soft rose, blue and floral breaks',
  'A gentle family show with floral bursts, pistils and soft rings. It keeps the colour playful without becoming too loud.',
  135,
  12000,
  10150,
  22,
  'Dusk',
  ARRAY['Family friendly','Floral','Soft'],
  '[{"timeSeconds":4,"fireworkSlug":"chrysanthemum-default","description":"Chrysanthemum"},{"timeSeconds":10,"fireworkSlug":"pistil-azure","description":"Azure pistil"},{"timeSeconds":16,"fireworkSlug":"peony-default","description":"Soft peony"},{"timeSeconds":22,"fireworkSlug":"ring-azure","description":"Blue ring"},{"timeSeconds":28,"fireworkSlug":"peony-crimson","description":"Rose peony"},{"timeSeconds":34,"fireworkSlug":"pearls-default","description":"Pearls"},{"timeSeconds":40,"fireworkSlug":"chrysanthemum-azure","description":"Blue mum"},{"timeSeconds":46,"fireworkSlug":"ring-default","description":"Ring"},{"timeSeconds":52,"fireworkSlug":"pistil-azure","description":"Pistil"},{"timeSeconds":58,"fireworkSlug":"peony-default","description":"Peony"},{"timeSeconds":64,"fireworkSlug":"nishiki-default","description":"Nishiki"},{"timeSeconds":70,"fireworkSlug":"pearls-azure","description":"Azure pearls"},{"timeSeconds":76,"fireworkSlug":"chrysanthemum-default","description":"Chrysanthemum"},{"timeSeconds":82,"fireworkSlug":"ring-crimson","description":"Rose ring"},{"timeSeconds":88,"fireworkSlug":"peony-azure","description":"Blue peony"},{"timeSeconds":94,"fireworkSlug":"pistil-azure","description":"Pistil"},{"timeSeconds":100,"fireworkSlug":"pearls-default","description":"Pearls"},{"timeSeconds":106,"fireworkSlug":"chrysanthemum-default","description":"Chrysanthemum"},{"timeSeconds":112,"fireworkSlug":"ring-azure","description":"Ring"},{"timeSeconds":120,"fireworkSlug":"peony-default","description":"Soft peony"},{"timeSeconds":130,"fireworkSlug":"nishiki-default","description":"Nishiki lift"},{"timeSeconds":133,"fireworkSlug":"pearls-azure","description":"Garden finish"}]'::jsonb,
  false,
  140,
  '{"kind":"mesh-gradient","colors":["#e86fa0","#ffd1e0","#4d9fe8","#7bc850"]}'::jsonb
),
(
  'festival-pop',
  'Festival Pop',
  'Colour hits for a crowd-friendly set',
  'A bright festival-style show with colour swaps every few seconds. Rings, peonies and crossettes make it easy to remix into pop music.',
  105,
  11500,
  9700,
  20,
  'Night',
  ARRAY['Crowd favourite','Colourful','High energy'],
  '[{"timeSeconds":3,"fireworkSlug":"peony-crimson","description":"Red pop"},{"timeSeconds":8,"fireworkSlug":"ring-azure","description":"Blue ring"},{"timeSeconds":13,"fireworkSlug":"chrysanthemum-default","description":"Gold mum"},{"timeSeconds":18,"fireworkSlug":"crossette-default","description":"Crossette"},{"timeSeconds":23,"fireworkSlug":"peony-azure","description":"Blue pop"},{"timeSeconds":28,"fireworkSlug":"ring-crimson","description":"Red ring"},{"timeSeconds":33,"fireworkSlug":"palm-default","description":"Gold palm"},{"timeSeconds":38,"fireworkSlug":"mine-default","description":"Mine hit"},{"timeSeconds":43,"fireworkSlug":"strobe-default","description":"White strobe"},{"timeSeconds":48,"fireworkSlug":"whirl-azure","description":"Whirl"},{"timeSeconds":53,"fireworkSlug":"peony-crimson","description":"Red peony"},{"timeSeconds":58,"fireworkSlug":"ring-azure","description":"Blue ring"},{"timeSeconds":63,"fireworkSlug":"crossette-default","description":"Crossette"},{"timeSeconds":68,"fireworkSlug":"chrysanthemum-azure","description":"Blue mum"},{"timeSeconds":73,"fireworkSlug":"palm-crimson","description":"Red palm"},{"timeSeconds":78,"fireworkSlug":"mine-default","description":"Mine"},{"timeSeconds":84,"fireworkSlug":"strobe-default","description":"Strobe"},{"timeSeconds":91,"fireworkSlug":"ring-default","description":"Gold ring"},{"timeSeconds":100,"fireworkSlug":"peony-default","description":"Final peony"},{"timeSeconds":103,"fireworkSlug":"crossette-default","description":"Festival finish"}]'::jsonb,
  true,
  150,
  '{"kind":"warp","colors":["#ff4d6d","#ffd166","#00e5ff","#8b5cf6"]}'::jsonb
),
(
  'quiet-sparks',
  'Quiet Sparks',
  'A tiny low-cost show with breathing room',
  'A restrained sixty-second option for testing, small yards or quiet tracks. Comets, pearls and a single finale keep it simple.',
  60,
  5000,
  3900,
  10,
  'Dusk',
  ARRAY['Budget friendly','Minimal','Calm'],
  '[{"timeSeconds":5,"fireworkSlug":"comet-default","description":"Comet"},{"timeSeconds":11,"fireworkSlug":"pearls-default","description":"Pearls"},{"timeSeconds":17,"fireworkSlug":"comet-azure","description":"Azure comet"},{"timeSeconds":23,"fireworkSlug":"peony-azure","description":"Soft peony"},{"timeSeconds":29,"fireworkSlug":"pearls-azure","description":"Blue pearls"},{"timeSeconds":35,"fireworkSlug":"comet-default","description":"Comet"},{"timeSeconds":41,"fireworkSlug":"ring-default","description":"Small ring"},{"timeSeconds":47,"fireworkSlug":"pearls-default","description":"Pearls"},{"timeSeconds":54,"fireworkSlug":"strobe-default","description":"Small shimmer"},{"timeSeconds":58,"fireworkSlug":"peony-azure","description":"Quiet finish"}]'::jsonb,
  false,
  160,
  '{"kind":"grain-gradient","colors":["#4d9fe8","#f4f1ea","#3fc4b0"]}'::jsonb
)
ON CONFLICT (slug) DO UPDATE SET
  title = excluded.title,
  theme = excluded.theme,
  description = excluded.description,
  duration_seconds = excluded.duration_seconds,
  budget_cents = excluded.budget_cents,
  total_cents = excluded.total_cents,
  effects_count = excluded.effects_count,
  time_of_day = excluded.time_of_day,
  mood_tags = excluded.mood_tags,
  preview_cues = excluded.preview_cues,
  is_featured = excluded.is_featured,
  sort_order = excluded.sort_order,
  cover_shader = COALESCE(show_presets.cover_shader, excluded.cover_shader),
  updated_at = now();
